#!/usr/bin/env python3
"""Emit `exp`'s constants and its 128-entry table from the *shipped* bytes.

The source of truth is `raw/exp_bytes.bin`, the 4096-byte dump of the live
`/usr/lib/system/libsystem_m.dylib` `exp` (written by `raw/dump_exp_data.c`). This script
reads that file, checks it against the layout the disassembly implies, and writes

  * `raw/apple_exp_table.h`  — the C constants + table (for the C transcription), and
  * `../appleExpTable.ts`    — the TypeScript module the port imports.

Nothing here is typed by hand, so the data cannot drift from the machine code:

    clang -O0 raw/dump_exp_data.c -o /tmp/dump_exp_data && (cd raw && /tmp/dump_exp_data)
    python3 raw/gen_exp_table.py
"""

import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, 'raw')
BIN = os.path.join(RAW, 'exp_bytes.bin')

# offsets, read off `objdump -d` of exp_bytes.bin (see dump_exp_data.c's header comment)
OFF_T_NEG = 0x118
OFF_T_HI = 0x120
OFF_T_S_TAIL = 0x128
OFF_T_O_MUL = 0x130
OFF_CONST = 0x140          # 7 doubles: ln2hiN, ln2loN, C0, C1, C2, C3, C4
OFF_TAB = 0x180            # 128 x {a, b}
N_TAB = 128


def u64(b: bytes, off: int) -> int:
    return struct.unpack_from('<Q', b, off)[0]


def dbl(b: bytes, off: int) -> float:
    return struct.unpack_from('<d', b, off)[0]


def main() -> None:
    with open(BIN, 'rb') as f:
        code = f.read()
    if len(code) < OFF_TAB + N_TAB * 16:
        sys.exit(f'{BIN} is only {len(code)} bytes; run dump_exp_data.c first')

    t_neg = u64(code, OFF_T_NEG)
    t_hi = u64(code, OFF_T_HI)
    s_tail = u64(code, OFF_T_S_TAIL)
    o_mul = u64(code, OFF_T_O_MUL)
    assert t_neg == 0xc0874a0000000000, hex(t_neg)
    assert t_hi == 0x40862e42fefa39f0, hex(t_hi)
    assert s_tail == 0x0010000000000000, hex(s_tail)
    assert o_mul == 0x7fefffffffffffff, hex(o_mul)

    const = [dbl(code, OFF_CONST + 8 * i) for i in range(7)]
    names = ['LN2HI_N', 'LN2LO_N', 'C0', 'C1', 'C2', 'C3', 'C4']
    tab = [(dbl(code, OFF_TAB + 16 * i), dbl(code, OFF_TAB + 16 * i + 8)) for i in range(N_TAB)]

    # the table is 2^(j/128) to ~2^-85: a is the double nearest 2^(j/128) and b the residual
    # *of a different split* (checked, not assumed -- see the PORT-NOTE)
    import math
    worst = 0.0
    for j, (a, b) in enumerate(tab):
        exact = 2.0 ** (j / 128.0)          # not the reference; only a magnitude check
        worst = max(worst, abs((a + b) - exact) / exact)
    print(f'table check: |(a+b) - 2^(j/128)| / 2^(j/128) <= {worst:.3e}')
    assert worst < 1e-13, worst

    hi = ['/* Generated by raw/gen_exp_table.py from raw/exp_bytes.bin -- do not edit. */',
          '#ifndef APPLE_EXP_TABLE_H',
          '#define APPLE_EXP_TABLE_H',
          '',
          '/* The constants of the shipped exp(), in load order (offsets 0x140..0x178). */']
    for n, v in zip(names, const):
        hi.append(f'#define AEXP_{n} {v!r}')
    hi.append('#define AEXP_T_NEG 0x%016xull' % 0xc0874a0000000000)
    hi.append('#define AEXP_T_HI  0x%016xull' % 0x40862e42fefa39f0)
    hi.append('#define AEXP_S_TAIL 0x%016xull' % 0x0010000000000000)
    hi.append('#define AEXP_O_MUL  0x%016xull' % 0x7fefffffffffffff)
    hi.append('')
    hi.append('/* EXP_TAB[j] = { 2^(j/128) high, low correction } */')
    hi.append('static const double AEXP_TAB[128][2] = {')
    for a, b in tab:
        hi.append(f'  {{ {a!r}, {b!r} }},')
    hi.append('};')
    hi.append('')
    hi.append('#endif')
    with open(os.path.join(RAW, 'apple_exp_table.h'), 'w') as f:
        f.write('\n'.join(hi) + '\n')

    ts = ['/**',
          ' * The constants and the 128-entry table of the oracle\'s `exp`, extracted from the',
          ' * shipped machine code (`src/model/rng/native/raw/exp_bytes.bin`, a 4096-byte dump of',
          ' * the live `/usr/lib/system/libsystem_m.dylib` symbol).',
          ' *',
          ' * GENERATED by `src/model/rng/native/raw/gen_exp_table.py` -- do not edit by hand.',
          ' * `EXP_TAB[j] = [ 2^(j/128), its low correction ]`.',
          ' */',
          '',
          f'export const EXP_LN2HI_N = {const[0]!r};',
          f'export const EXP_LN2LO_N = {const[1]!r};',
          f'export const EXP_C0 = {const[2]!r};',
          f'export const EXP_C1 = {const[3]!r};',
          f'export const EXP_C2 = {const[4]!r};',
          f'export const EXP_C3 = {const[5]!r};',
          f'export const EXP_C4 = {const[6]!r};',
          '',
          'export const EXP_TAB: readonly (readonly [number, number])[] = [']
    for a, b in tab:
        ts.append(f'  [{a!r}, {b!r}],')
    ts.append('];')
    ts.append('')
    ts_path = os.path.normpath(os.path.join(HERE, '..', 'appleExpTable.ts'))
    with open(ts_path, 'w') as f:
        f.write('\n'.join(ts) + '\n')

    print('wrote raw/apple_exp_table.h and ../appleExpTable.ts')
    print('constants:', ', '.join(f'{n}={v!r}' for n, v in zip(names, const)))


if __name__ == '__main__':
    main()
