/**
 * Lane W1c — C `printf`-compatible formatting for the datalib writer.
 *
 * The datalib writer is a byte-level contract: every column value goes through native
 * `sprintf( b, it->format, val )` (`utils/datalib.cc` `DataLibWriter::addRow`) and the
 * bytes that call produces are what the oracle compares. Two things therefore have to be
 * reproduced exactly, not approximately:
 *
 *   - the *format string* semantics (flags, width, precision, conversion) — including the
 *     default formats `__Column` picks when a logger passes none (`%d`, `%f`, `%s` and the
 *     padded `%-20d` / `%-20f` / `%-20s` variants for `randomAccess`);
 *   - glibc's `%f` rounding, which rounds the *exact* binary value of the (promoted)
 *     double to the requested number of decimal places with ties-to-even. That is not
 *     `Number.prototype.toFixed`, which resolves ties by picking the larger decimal
 *     (`(0.0078125).toFixed(6) === '0.007813'` but glibc prints `0.007812`). Since the
 *     model writes floats, a wrong tie rule is a silent one-byte divergence.
 *
 * PORT-NOTE(w1c/printf-float): `%f`/`%F` is implemented from the exact decimal expansion of
 * the IEEE-754 double (BigInt mantissa/exponent, see `exactDecimal`) with round-half-to-even,
 * matching glibc's default FE_TONEAREST behaviour. `tests/datalib.test.ts` pins it against
 * vectors generated by clang/glibc on this machine, including the tie cases.
 */

import { ColumnType } from '../types/datalib';

/** A value a column can hold (native `Variant` restricted to the datalib types). */
export type ColumnValue = number | string | boolean;

/**
 * PORT-NOTE(w1c/int32-wrap): native stores an `INT` column in a C `int`
 * (`TOVARIANT(int,int)` then `TOBUF(int)`), so the value written is the C conversion of
 * the incoming double. Out-of-range conversion is UB in C and platform-dependent (clang on
 * arm64 saturates via `fcvtzs`, x86 truncates); the port takes JS `ToInt32` (modulo 2^32,
 * NaN/±Infinity -> 0), which is what the model actually feeds for the in-range values
 * (steps, agent numbers, counts).
 */
export function toInt32(value: number): number {
  return value | 0;
}

/**
 * Scratch for the bit-level decomposition — one buffer viewed as a double and as its two
 * 32-bit words. `formatFixed` runs this millions of times per run (one `%.1f` per mutable gene
 * per step), so it is a module-level buffer with typed-array access: a fresh `ArrayBuffer` per
 * call is garbage (what the shape this replaces did), and a `DataView` method per access is a
 * builtin call where a typed-array element access inlines.
 */
const bitsBuffer = new ArrayBuffer(8);
const bitsFloat = new Float64Array(bitsBuffer);
const bitsWords = new Uint32Array(bitsBuffer);

/** `Uint32Array` reads words in platform order; the exponent lives in the high one. */
const LITTLE_ENDIAN = new Uint8Array(new Uint32Array([1]).buffer)[0] === 1;
const HIGH_WORD = LITTLE_ENDIAN ? 1 : 0;
const LOW_WORD = 1 - HIGH_WORD;

/** `2^i` as a double, for the trailing-zero reduction below (`i <= 52` is all it ever sees). */
const POW2 = Float64Array.from({ length: 64 }, (_, i) => 2 ** i);

/**
 * Exact value of a positive finite double as `mantissa * 2^exponent`, with `mantissa` an **odd**
 * integer (`abs === mantissa * 2^exponent` holds exactly).
 *
 * PORT-NOTE(w1c/printf-exact-small-bigint): reducing the mantissa to odd is what keeps every
 * BigInt in this file at the width of the value's *significant* bits (a double has 53 of them)
 * instead of carrying its trailing zero bits into a power of five. The previous shape returned
 * the exact value as `mantissa * 5^-e * 10^e`, which builds `5^1074` — a 2.5 kbit BigInt, via
 * exponentiation — for a subnormal, multiplies by it and then divides by it.
 *
 * The reduction counts the mantissa's trailing zero bits off the raw words instead of shifting
 * one bit at a time: the `%.1f` statistics `GeneStatsLog` writes are `float`s promoted to
 * doubles, so 29 of a mantissa's 52 low bits are always zero and a per-bit loop paid for all of
 * them, every call (28 % of the 25-agent step loop's profile, 2026-09-28).
 */
export function decomposeBinary(abs: number): { mantissa: number; exponent: number } {
  bitsFloat[0] = abs;
  const hi = bitsWords[HIGH_WORD]!;
  const lo = bitsWords[LOW_WORD]!;
  const rawExp = (hi >>> 20) & 0x7ff;
  // The fraction's high bits, with the implicit bit when the value is normal.
  const high = (hi & 0xfffff) | (rawExp === 0 ? 0 : 0x100000);

  // Both steps are exact in doubles: the fraction is below 2^52 and gains at most 2^52.
  let mantissa = (hi & 0xfffff) * 4294967296 + lo;
  let exponent: number;
  if (rawExp === 0) {
    exponent = -1074;
    if (mantissa === 0) return { mantissa: 0, exponent: 0 };
  } else {
    mantissa += 4503599627370496; // the implicit bit, 2^52
    exponent = rawExp - 1075;
  }

  // `x & -x` isolates the lowest set bit; `Math.clz32` turns it into a trailing-zero count.
  // A zero low word means the count is 32 plus the fraction's own, off the high word.
  const trailing = lo !== 0 ? 31 - Math.clz32((lo & -lo) >>> 0) : 32 + (31 - Math.clz32((high & -high) >>> 0));
  if (trailing > 0) {
    mantissa /= POW2[trailing]!;
    exponent += trailing;
  }

  return { mantissa, exponent };
}

/** `5^n` as a BigInt, cached — the power of five every exact decimal expansion needs. */
const POW5: bigint[] = [1n];

export function pow5(n: number): bigint {
  for (let i = POW5.length; i <= n; i++) POW5[i] = POW5[i - 1]! * 5n;
  return POW5[n]!;
}

/**
 * C `printf( "%<precision>f", value )` for a double, correctly rounded, ties-to-even.
 * Non-finite values print as glibc does (`inf`, `-inf`, `nan`).
 *
 * PORT-NOTE(w1c/printf-float-exact-shift): `value === mantissa * 2^e` with an odd mantissa, and
 * `10^p === 2^p * 5^p`, so the scaled value is
 *
 *     value * 10^p === mantissa * 5^p * 2^(e + p)
 *
 * — an exact integer when `e + p >= 0`, and otherwise one shift right by `2^-(e+p)` with
 * round-half-to-even, i.e. a mask and a compare. No division is involved: `mantissa * 5^p` is
 * ~53 + 2.3p bits, where the shape this replaces built `5^-e` (up to 2.5 kbit) and divided a
 * 2.5 kbit product by `10^-shift`. The digits and the tie rule are the ones `tests/datalib.test.ts`
 * pins against clang/glibc, including `0.0078125` at 6 (ties to even, not `toFixed`'s ties-up).
 */
export function formatFixed(value: number, precision: number): string {
  if (Number.isNaN(value)) return 'nan';
  if (value === Infinity) return 'inf';
  if (value === -Infinity) return '-inf';

  // glibc keeps the sign for negative values even when they round to zero ("-0.00").
  const negative = value < 0 || Object.is(value, -0);
  const abs = Math.abs(value);

  if (abs === 0) {
    return `${negative ? '-' : ''}0${precision > 0 ? `.${'0'.repeat(precision)}` : ''}`;
  }

  const { mantissa, exponent } = decomposeBinary(abs);
  const shift = exponent + precision;
  const leading = BigInt(mantissa) * pow5(precision);

  let scaled: bigint;
  if (shift >= 0) {
    // exact: the value has no bits below the requested decimal place
    scaled = leading << BigInt(shift);
  } else {
    const right = BigInt(-shift);
    const quotient = leading >> right;
    const remainder = leading - (quotient << right);
    const half = 1n << (right - 1n);
    if (remainder > half || (remainder === half && (quotient & 1n) === 1n)) scaled = quotient + 1n;
    else scaled = quotient;
  }

  let text = scaled.toString();
  if (precision > 0) {
    if (text.length <= precision) text = '0'.repeat(precision + 1 - text.length) + text;
    text = `${text.slice(0, text.length - precision)}.${text.slice(text.length - precision)}`;
  }
  return `${negative ? '-' : ''}${text}`;
}

/** C `printf( "%d", (int) value )`. */
export function formatInt(value: number): string {
  return String(toInt32(value));
}

/** C `printf( "%zu" )` / `"%lu"` — a non-negative byte count. */
export function formatSize(value: number): string {
  return String(Math.trunc(value));
}

/** C `printf( "%-<width>s" )` / `"%<width>s"` — space padding, never truncated. */
export function padField(text: string, width: number | undefined, left: boolean, padChar = ' '): string {
  if (width === undefined || text.length >= width) return text;
  const fill = padChar.repeat(width - text.length);
  return left ? text + fill : fill + text;
}

/** A parsed `%…` conversion. */
export interface FormatSpec {
  readonly conversion: string;
  readonly left: boolean;
  readonly zeroPad: boolean;
  readonly plus: boolean;
  readonly space: boolean;
  readonly width: number | undefined;
  readonly precision: number | undefined;
  /** Literal text before the conversion (`"%f"` -> `""`). */
  readonly prefix: string;
  /** Literal text after the conversion (`"%.2f m"` -> `" m"`). */
  readonly suffix: string;
}

/**
 * Parse a single-conversion printf format. Everything the native loggers use is accepted
 * (`%d`, `%f`, `%.2f`, `%s`, `%-20d`, `%-20f`, `%-20s`, `%zu`); anything else throws, so a
 * bad schema fails loudly instead of writing wrong bytes.
 */
export function parseFormatSpec(format: string): FormatSpec {
  const start = format.indexOf('%');
  if (start < 0) throw new Error(`datalib: column format has no conversion: ${JSON.stringify(format)}`);
  if (format[start + 1] === '%') {
    throw new Error(`datalib: '%%' is not a column format: ${JSON.stringify(format)}`);
  }

  const re = /^%([-+ 0#]*)(\d+)?(?:\.(\d+))?(?:hh|h|ll|l|j|z|t|L)?([diouxXeEfgGaAcsp])/;
  const m = re.exec(format.slice(start));
  if (!m) throw new Error(`datalib: unsupported column format: ${JSON.stringify(format)}`);

  const flags = m[1] ?? '';
  const conversion = m[4]!;
  if (conversion === 'e' || conversion === 'E' || conversion === 'g' || conversion === 'G') {
    throw new Error(`datalib: column format '${conversion}' is not used by native datalib and is not ported: ${JSON.stringify(format)}`);
  }
  if (conversion === 'x' || conversion === 'X' || conversion === 'o' || conversion === 'a' || conversion === 'A') {
    throw new Error(`datalib: column format '${conversion}' is not ported: ${JSON.stringify(format)}`);
  }

  return {
    conversion,
    left: flags.includes('-'),
    zeroPad: flags.includes('0'),
    plus: flags.includes('+'),
    space: flags.includes(' '),
    width: m[2] === undefined ? undefined : Number(m[2]),
    precision: m[3] === undefined ? undefined : Number(m[3]),
    prefix: format.slice(0, start),
    suffix: format.slice(start + m[0].length),
  };
}

/** Apply a parsed conversion to a column value (native `sprintf( b, fmt, val )`). */
export function applyFormatSpec(spec: FormatSpec, value: ColumnValue): string {
  let text: string;
  switch (spec.conversion) {
    case 'd':
    case 'i': {
      const n = typeof value === 'number' ? toInt32(value) : value ? 1 : 0;
      text = signedNumberText(spec, n);
      break;
    }
    case 'u':
    case 'o':
    case 'x':
    case 'X': {
      const n = typeof value === 'number' ? toInt32(value) : 0;
      text = String(n >>> 0);
      break;
    }
    case 'f':
    case 'F': {
      const n = typeof value === 'number' ? value : Number(value);
      const body = formatFixed(n, spec.precision ?? 6);
      text = body.startsWith('-') ? body : withSignPrefix(spec, body);
      return spec.prefix + padNumeric(text, spec) + spec.suffix;
    }
    case 'c': {
      text = typeof value === 'string' ? String.fromCharCode(value.charCodeAt(0) & 0xff) : String.fromCharCode((Number(value) | 0) & 0xff);
      break;
    }
    case 's': {
      text = typeof value === 'string' ? value : String(value);
      return spec.prefix + padField(text, spec.width, spec.left) + spec.suffix;
    }
    case 'p': {
      throw new Error('datalib: %p is not a valid column format');
    }
    default:
      throw new Error(`datalib: unsupported conversion '%${spec.conversion}'`);
  }
  return spec.prefix + padNumeric(text, spec) + spec.suffix;
}

function withSignPrefix(spec: FormatSpec, body: string): string {
  if (spec.plus) return `+${body}`;
  if (spec.space) return ` ${body}`;
  return body;
}

function signedNumberText(spec: FormatSpec, n: number): string {
  if (n < 0) return String(n);
  return withSignPrefix(spec, String(n));
}

/** Width/flags for the numeric conversions; zero padding goes after the sign. */
function padNumeric(text: string, spec: FormatSpec): string {
  if (spec.width === undefined || text.length >= spec.width) return text;
  if (spec.left) return text + ' '.repeat(spec.width - text.length);
  if (spec.zeroPad) {
    const sign = text.startsWith('-') || text.startsWith('+') ? text[0]! : '';
    const body = sign ? text.slice(1) : text;
    return sign + '0'.repeat(spec.width - text.length) + body;
  }
  return ' '.repeat(spec.width - text.length) + text;
}

/**
 * The format a column is written with. Native `__Column::__Column` (`datalib.cc`): an
 * explicit logger format wins, otherwise the type default, left-padded to 20 columns when
 * the file is `randomAccess` (`pad`).
 */
export function defaultColumnFormat(type: ColumnType, pad: boolean): string {
  switch (type) {
    case ColumnType.INT:
    case ColumnType.BOOL:
      return pad ? '%-20d' : '%d';
    case ColumnType.FLOAT:
      return pad ? '%-20f' : '%f';
    case ColumnType.STRING:
      return pad ? '%-20s' : '%s';
    default:
      throw new Error(`datalib: no default format for column type ${type}`);
  }
}

/**
 * The value native stores for a column: `addRow()` converts the argument to the column's C
 * type before the row is formatted (`TOVARIANT`), and `addRow(Variant*)` converts again on
 * the way out (`TOBUF`). A `FLOAT` column therefore holds a `float` (32-bit) — see
 * PORT_SPEC "Floats".
 *
 * PORT-NOTE(w1c/float32-columns): float columns are rounded to float32 (`Math.fround`)
 * before formatting, because native stores/prints a C `float`; the promoted-to-double
 * `%f` in `TOBUF` then prints those float32 bits.
 */
export function columnValueForType(type: ColumnType, value: ColumnValue): ColumnValue {
  switch (type) {
    case ColumnType.INT:
      return toInt32(typeof value === 'number' ? value : Number(value));
    case ColumnType.FLOAT:
      return Math.fround(typeof value === 'number' ? value : Number(value));
    case ColumnType.STRING:
      return typeof value === 'string' ? value : String(value);
    case ColumnType.BOOL:
      return typeof value === 'boolean' ? (value ? 1 : 0) : (Number(value) ? 1 : 0);
    default:
      throw new Error(`datalib: cannot write column of type ${type}`);
  }
}

/**
 * Parsed column formats, keyed by the format string. `formatColumn` runs once per cell of every
 * datalib row and the format is fixed when the table is opened (`DataLibWriter.beginTable`), so
 * the regex in `parseFormatSpec` belongs to the schema, not to the row.
 */
const formatSpecCache = new Map<string, FormatSpec>();

function cachedFormatSpec(format: string): FormatSpec {
  const cached = formatSpecCache.get(format);
  if (cached !== undefined) return cached;

  const spec = parseFormatSpec(format);
  // Column formats are literals; the cap is only here so a caller that builds formats
  // dynamically cannot grow the cache without bound.
  if (formatSpecCache.size >= 4096) formatSpecCache.clear();
  formatSpecCache.set(format, spec);
  return spec;
}

/** Format one column value with its format string (`sprintf( b, format, val )`). */
export function formatColumn(format: string, type: ColumnType, value: ColumnValue): string {
  return applyFormatSpec(cachedFormatSpec(format), columnValueForType(type, value));
}
