#!/usr/bin/env python3
"""Record what the native interpreter (`src/library/proplib/interpreter.py`) answered.

Native proplib evaluates a worldfile expression by piping the Python source text
`interpreter.cc::ExpressionEvaluator::evaluate` generated to a `python3` child, which replies
with `str( eval( text ) )`. Lane L4 ports that language; this script records the native side
of the contract so the port can be compared against it instead of against my reading of
CPython's docs.

Two vector sets land in `vectors/pythonExpressions.json`:

* `vectors` — `source` (the Python text) with the `python3` outcome: `value` = `str(eval)`, or
  `error` = `str(exc)` with `errorType` and `syntax` (a `SyntaxError`'s text is not ported
  verbatim, the port only has to fail loudly). The sources are:
    - `CORPUS`: every Python text lane L4's `generatePythonExpression` produced while building
      the four recorded scenarios (both worldfiles x `--Vision False` / no override) with the
      validation pass on. Re-collect by running the port with a recording evaluator over
      `oracle/<scenario>/run/original.{wf,wfs}` (see `tests/proplib.test.ts`, band 4);
    - `CURATED`: the language's own cases — integer/float semantics and `str()` of floats,
      comparisons, boolean operators, the conditional expression, strings and escapes,
      builtins, containers and subscripts, and the runtime failures native reported as
      `[Python] <message>`.
* `unsupportedByPort` — grammar CPython evaluates but the port *refuses on purpose*
  (`lambda`, comprehensions, f-strings, `bytes`, complex literals, `%`-formatting, walrus).
  No worldfile reaches them; the fixture records that they are rejected loudly rather than
  evaluated wrongly (PORT_SPEC rule 1: never silently disagree).

Usage: `python3 src/model/proplib/native/record_python_vectors.py [--out PATH]`
"""

import argparse
import json
import sys

CORPUS = [
    "\"All\"",
    "\"All\" if True else \"False\"",
    "\"Approximate\" if True else \"False\"",
    "\"Array\"",
    "\"B\"",
    "\"Bit\"",
    "\"Bool\"",
    "\"Color\"",
    "\"Enum\"",
    "\"F\"",
    "\"Field\"",
    "\"Fight\"",
    "\"FindEnergyPolarity\"",
    "\"Float\"",
    "\"Gene\"",
    "\"Groups\"",
    "\"I\"",
    "\"Int\"",
    "\"L\"",
    "\"Legacy\"",
    "\"Mate\"",
    "\"MaxIndependent\"",
    "\"NeurGroup\" if \"Groups\" == \"Groups\" else \"None\"",
    "\"Normal\"",
    "\"Null\"",
    "\"O\"",
    "\"Object\"",
    "\"Oppose\"",
    "\"P\"",
    "\"Permutations\"",
    "\"R\"",
    "\"Sheet\"",
    "\"Standard\"",
    "\"String\"",
    "\"U\"",
    "(  0.3333 if True else  (0.3333 * 25) )",
    "(  0.6667 if True else  (0.6667 * 25) )",
    "( (-1.0 == -1.0) or (-1.0 >= 0.0) )",
    "( (0.8 == -1.0) or (0.8 >= 0.0) )",
    "( (1.0 == -1.0) or (1.0 >= 0.0) )",
    "( -0.1    if True else -0.1*25 )",
    "( -1.0    if True else -25 )",
    "( -1.0 if True else -25 )",
    "( 0.01 if \"Bit\" == \"Bit\" else 0.08 )",
    "( 0.05 if \"Bit\" == \"Bit\" else 0.4 )",
    "( 0.2 if False else 0.5 )",
    "( 1.0 if True else 25 )",
    "( 10 if 10 > 0 else 90 )",
    "( 22 == 22 )",
    "( 25 >= 0 and 25 <= 25 ) or False",
    "( 25 >= 20 and 25 <= 25 ) or False",
    "( True if \"F\" == \"S\" else False )",
    "( True or False )",
    "( not False or True or False )",
    "-1",
    "-1.0",
    "-180.0",
    "-30",
    "-7.5",
    "-80",
    "-90.0",
    "0",
    "0.0",
    "0.0 > 0.0 or not False",
    "0.001",
    "0.01",
    "0.05",
    "0.1",
    "0.15",
    "0.2",
    "0.25",
    "0.3",
    "0.35",
    "0.4",
    "0.5",
    "0.6",
    "0.75",
    "0.8",
    "0.99",
    "1",
    "1.0",
    "1.5",
    "10",
    "10.0",
    "100",
    "100.0",
    "1000",
    "1000.0",
    "140.0",
    "16",
    "180.0",
    "2",
    "2.0",
    "2.5",
    "20",
    "20.0",
    "200",
    "200.0",
    "22",
    "25",
    "25.0",
    "255",
    "3",
    "30",
    "301",
    "33",
    "400.0",
    "42",
    "5",
    "5.0",
    "500",
    "500.0",
    "6.0",
    "7.5",
    "8.0",
    "90",
    "90.0",
    "False",
    "True",
    "not False or not False",
    "not True or ( not False and ( 0 == 0 ) and ( True or False ) )"
]

CURATED = [
    "1 + 2",
    "2 - 3",
    "2 * 3",
    "7 / 2",
    "7 // 2",
    "-7 // 2",
    "7 % 3",
    "-7 % 3",
    "7 % -3",
    "2 ** 10",
    "2 ** 0",
    "0 ** 0",
    "2 ** -1",
    "10 / 5",
    "1 + 2 * 3",
    "( 1 + 2 ) * 3",
    "- - 5",
    "+ 5",
    "~ 5",
    "5 & 3",
    "5 | 3",
    "5 ^ 3",
    "1 << 10",
    "1024 >> 3",
    "10000000000000000000000 * 3",
    "2 ** 200",
    "0x1f + 1",
    "9999999999999999999 + 1",
    "1.0",
    "0.5",
    "1 / 3",
    "0.1 + 0.2",
    "1e16",
    "1e15",
    "1e-4",
    "1e-5",
    "0.0001",
    "0.00001",
    "-0.0",
    "1e308",
    "1e309",
    "-1e309",
    "float(\"nan\")",
    "float(\"inf\")",
    "float(\"-inf\")",
    "3.0 // 2",
    "3.0 % 2",
    "7.5 % 2",
    "-7.5 % 2",
    "2.5 ** 2",
    "10.0 / 4",
    "float(1) / 3",
    ".5",
    "1.",
    "25.0",
    "0.3333 * 25",
    "0.6667 * 25",
    "-0.1 * 25",
    "round(2.5)",
    "round(3.5)",
    "round(-2.5)",
    "round(0.5)",
    "round(1.5)",
    "round(2.675, 2)",
    "round(1234.5678, -2)",
    "round(7)",
    "round(2.675)",
    "round(-0.5)",
    "1 < 2",
    "1 < 2 < 3",
    "1 < 2 > 3",
    "2 > 1",
    "2 >= 2",
    "2 <= 1",
    "1 == 1.0",
    "1 == \"1\"",
    "True == 1",
    "1 != 2",
    "\"a\" < \"b\"",
    "\"a\" == \"a\"",
    "not True",
    "not 0",
    "not \"\"",
    "1 and 2",
    "0 and 2",
    "1 or 2",
    "0 or 2",
    "0 or \"\" or 3",
    "None == None",
    "None is None",
    "\"a\" in \"abc\"",
    "\"z\" in \"abc\"",
    "3 in [ 1, 2, 3 ]",
    "4 not in ( 1, 2 )",
    "'k' in { 'k' : 1 }",
    "1 if True else 2",
    "1 if False else 2",
    "0.3333 if True else 0.3333 * 25",
    "25 if False else 10",
    "1 if 1 else 2",
    "\"\" if False else \"x\"",
    "\"a\" if 1 == 1 else \"b\"",
    "- 1.0 if True else - 25",
    "1 if 0 else 2 if 0 else 3",
    "\"abc\"",
    "'abc'",
    "\"a\\nb\"",
    "\"a\\tb\"",
    "\"q\\\"q\"",
    "\"a\\\\b\"",
    "\"\"",
    "\"a\" + \"b\"",
    "\"ab\" * 3",
    "len(\"abcd\")",
    "len(\"\")",
    "str(1)",
    "str(1.0)",
    "str(True)",
    "str(None)",
    "str(1.5)",
    "str(\"x\")",
    "repr(\"a\")",
    "repr(\"a'b\")",
    "repr(1.5)",
    "repr(None)",
    "repr([ 1, \"a\" ])",
    "int(\"42\")",
    "int(3.9)",
    "int(-3.9)",
    "int(True)",
    "int(\"42\", 16)",
    "float(\"2.5\")",
    "float(2)",
    "bool(0)",
    "bool(\"\")",
    "bool([1])",
    "abs(-3)",
    "abs(-3.5)",
    "min(3, 1, 2)",
    "max(3, 1, 2)",
    "min([ 3, 1, 2 ])",
    "max(\"a\", \"b\")",
    "sum([ 1, 2, 3 ])",
    "sum([ 1.5, 2 ])",
    "sorted([ 3, 1, 2 ])",
    "list(\"ab\")",
    "tuple([ 1, 2 ])",
    "divmod(7, 2)",
    "ord(\"a\")",
    "chr(97)",
    "pow(2, 8)",
    "pow(2, 8, 5)",
    "[ 1, 2 ]",
    "( 1, 2 )",
    "( 1, )",
    "[]",
    "()",
    "{}",
    "{ 1, 2 }",
    "[ 1, \"a\", True ]",
    "{ \"a\": 1 }",
    "[ 1, 2 ][0]",
    "[ 1, 2 ][-1]",
    "\"abc\"[1]",
    "\"abc\"[-1]",
    "{ \"a\": 1 }[\"a\"]",
    "len([ 1, 2, 3 ])",
    "2 ** 3 ** 2",
    "- 2 ** 2",
    "- - 1",
    "not not 1",
    "\"a\" * 0",
    "[ 1 ] * 0",
    "True + True",
    "1 == True",
    "True is True",
    "True is 1",
    "None is not None",
    "0.1 == 0.1",
    "float(1) / 3 * 3",
    "int(\"  42  \")",
    "\"x\" in [ \"x\" ]",
    "( 1, 2 ) < ( 1, 3 )",
    "sorted([ \"b\", \"a\" ])",
    "len(r\"a\\nb\")",
    "abs(-0.0)",
    "-0.0 == 0.0",
    "divmod(-7, 2)",
    "10 // 3",
    "sum([])",
    "min([ 1 ])",
    "chr(0)",
    "str([ 1, \"a\" ])",
    "repr(1e16)",
    "\"ab\" < \"b\"",
    "1e400",
    "5 // 2.0",
    "None if 0 else 1",
    "1.0 if True else 2",
    "int(1e20)",
    "2 ** 100 * 2",
    "float(\"1e400\")",
    "( 1 if True else 2 ) + 3",
    "str(2 ** 3 ** 2)",
    "round(-0.5)",
    "int(-2.9)",
    "pow(2, -1)",
    "abs(-2 ** 31)",
    "min(\"a\", \"b\", \"c\")",
    "sorted([ 3, 1, 2 ])[0]",
    "[ 1, 2, 3 ][1:]",
    "[ 1, 2, 3 ][:2]",
    "[ 1, 2, 3 ][:]",
    "[ 1, 2, 3 ][::-1]",
    "[ 1, 2, 3 ][-1:]",
    "[ 1, 2, 3 ][:-1]",
    "[ 1, 2, 3 ][::2]",
    "[ 1, 2, 3 ][1:99]",
    "[ 1, 2, 3 ][-99:99]",
    "\"abcdef\"[1:3]",
    "\"abcdef\"[::-1]",
    "\"abcdef\"[-2:]",
    "( 1, 2, 3 )[1:]",
    "[ 1, 2, 3 ][2:1]",
    "len(\"abcdef\"[1:3])",
    "sorted([ 3, 1, 2 ])[:1]",
    "1 if True else 2, 3",
    "1 ,",
    "r\"a\\nb\"",
    "r'a\\tb'",
    "(  0.3333 if True else  (0.3333 * 25) )",
    " 25 ",
    "  1.0",
    "- 25",
    "-0.1*25",
    "1 / 0",
    "1.0 / 0",
    "1 // 0",
    "1 % 0",
    "undefined_name",
    "undefined_name + 1",
    "len(1)",
    "int(\"x\")",
    "float(\"x\")",
    "\"a\" + 1",
    "1 < \"a\"",
    "\"a\" - \"b\"",
    "[ 1 ][5]",
    "\"a\"[3]",
    "{ 1: 2 }[3]",
    "abs(\"x\")",
    "min([])",
    "ord(\"ab\")",
    "chr(-1)",
    "None + 1",
    "True + None",
    "1 +",
    "( 1",
    "1 if 2",
    "1 2",
    "\"unterminated"
]

UNSUPPORTED = [
    "lambda: 1",
    "[ x for x in [ 1 ] ]",
    "[ x for x in [ 1 ] if x ]",
    "{ k: 1 for k in [ 1 ] }",
    "{ x for x in [ 1 ] }",
    "( x for x in [ 1 ] )",
    "f\"{1}\"",
    "b\"x\"",
    "rb\"x\"",
    "1j",
    "\"%d\" % 3",
    "\"%s\" % \"x\"",
    "x := 1",
    "1 .real",
    "( 1 ).real"
]


def record(source):
    try:
        return {"source": source, "value": str(eval(source))}
    except Exception as exc:  # noqa: BLE001 - the point is to record whatever it was
        return {
            "source": source,
            "error": str(exc),
            "errorType": type(exc).__name__,
            "syntax": isinstance(exc, SyntaxError),
        }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out",
        default="src/model/proplib/native/vectors/pythonExpressions.json",
    )
    args = parser.parse_args()

    sources = []
    seen = set()
    for source in CORPUS + CURATED:
        if source in seen:
            continue
        seen.add(source)
        sources.append(source)

    fixture = {
        "formatVersion": 1,
        "python": sys.version.split()[0],
        "interpreter": "str( eval( text ) ) via src/library/proplib/interpreter.py",
        "corpusCount": len(CORPUS),
        "vectors": [record(source) for source in sources],
        "unsupportedByPort": UNSUPPORTED,
    }

    with open(args.out, "w") as handle:
        json.dump(fixture, handle, indent=2, sort_keys=False)
        handle.write("\n")

    failures = sum(1 for vector in fixture["vectors"] if "error" in vector)
    print(
        "%s: %d vectors (%d corpus, %d curated), %d runtime/syntax failures, python %s"
        % (args.out, len(fixture["vectors"]), len(CORPUS), len(CURATED), failures, fixture["python"])
    )


if __name__ == "__main__":
    main()
