/**
 * The constants and tables of the oracle's `sin`/`cos`, extracted from the shipped
 * machine code (`src/model/rng/native/raw/sincos_bytes.bin`, a 5120-byte dump of the
 * live `/usr/lib/system/libsystem_m.dylib` `sin` symbol; `cos` shares the unit).
 *
 * GENERATED by `src/model/rng/native/gen_sincos_table.py` -- do not edit by hand.
 * `TAB[15-j]` is the 1/pi word the Payne-Hanek walk reads for `e >> 6 == j`.
 */

export const PI4 = 0.7853981633974483;
export const THRESH = 524288.6169851497;
export const INV_PI2 = 0.6366197723675814;
export const PI2_HI = 1.5707963267923333;
export const PI2_MID = 2.5633441515839558e-12;
export const PI2_LO = 1.0562999066987428e-23;
export const MAGIC_PI2 = 0xc90fdaa22168c235n;

export const TAB: readonly bigint[] = [
  0x35fdafd88fc6ae84n,
  0x9e839cfbc5294975n,
  0xba93dd63f5f2f8bdn,
  0xa7a31fb34f2ff516n,
  0xb69b3f6793e584dbn,
  0xf79788c5ad05368fn,
  0x8ffc4bffef02cc07n,
  0x4e422fc5defc941dn,
  0x9cc8eb1cc1a99cfan,
  0x74ce38135a2fbf20n,
  0x74411afa975da242n,
  0x7f0ef58e5894d39fn,
  0x0324977504e8c90en,
  0xdb92371d2126e970n,
  0xff28b1d5ef5de2b0n,
  0x6db14acc9e21c820n,
  0xfe13abe8fa9a6ee0n,
  0x517cc1b727220a94n,
  0x0000000000000000n,
];

export const SIN_POLY: readonly number[] = [
  1.5896230157654656e-10,
  -2.5050747762857807e-08,
  2.7557313621385722e-06,
  -0.0001984126982958954,
  0.008333333333322118,
  -0.1666666666666663,
];

export const COS_POLY: readonly number[] = [
  -1.1358536521387682e-11,
  2.087570084197473e-09,
  -2.755731417929674e-07,
  2.4801587288851704e-05,
  -0.0013888888888873056,
  0.041666666666666595,
  -0.5,
];

