/**
 * The constants of the oracle's arm64 `atan2f` (lane W1e -> L1 libm transcription).
 *
 * GENERATED by `src/model/rng/native/gen_atan2f_table.py` from
 * `src/model/rng/native/raw/atan2f_bytes.bin` -- do not edit by hand.  The offsets are
 * `atan2f`-relative; the script decodes the displacements of the `adr`/`adrp`+`add`/
 * `ldr <label>` instructions that read these words and refuses to emit if any of them
 * stops pointing at the offsets below.
 *
 * `ATAN2F_POLY` is the ratio polynomial, evaluated as a product of four quadratics in
 * `u = r*r` (see `libm.ts`'s `atan2f`): `atan(r) ~ T8*(u^2+T0 u+T2)*(u^2+T4 u+T6)*
 * (u^2+T1 u+T3)*(u^2+T5 u+T7)*r`, each fused step a single rounding.  It approximates
 * `atan(r)` to 0.36 float32 ulp over [-1, 1] -- the implementation is
 * *float* accurate, which is why the shipped `atan2f` disagrees with the correctly
 * rounded `f32(atan2)` on ~15-20 % of arguments.
 */

/** the `|y/x|` threshold `2^-22`: below it the `x < 0` arm answers `+-ATAN2F_PI_HI` */
export const ATAN2F_SMALL = 2.384185791015625e-07;

/**
 * The four quadratics' coefficients, in memory order (`+0x220`..`+0x260`).  The code
 * groups them as `(u^2 + T0*u + T2)`, `(u^2 + T1*u + T3)`, `(u^2 + T4*u + T6)`,
 * `(u^2 + T5*u + T7)` -- the "+u" and the constant alternate -- and scales the product
 * by `T8`, so the evaluated quantity is `T8 * ... * r`.
 */
export const ATAN2F_POLY: readonly number[] = [
  2.2971562298314634,
  -2.9466967515109825,
  2.4449692297316408,
  5.472844732445699,
  0.020743200300742098,
  -4.972107237621162,
  3.7888879287802704,
  6.719707622359238,
  0.0029352921857004597,
];

/** `+-pi` (`+0x270`, a two-entry table the code indexes with the sign of `y`) */
export const ATAN2F_PI = 3.141592653589793;
export const ATAN2F_NEG_PI = -3.141592653589793;

/** `+-pi/2` (`+0x280`/`+0x288`) */
export const ATAN2F_HPI = 1.5707963267948966;
export const ATAN2F_NEG_HPI = -1.5707963267948966;

/**
 * The small-`|y/x|` arm's `pi`: `f32(pi)` rounded toward zero plus exactly `2**-32`,
 * i.e. `0x1.921fb4008p+1`.  It is the reason arm64's `atan2f(0, -1)` is `0x40490fda`
 * (the correctly rounded `f32(atan2)` is `0x40490fdb`) -- the census' +-pi behaviour.
 */
export const ATAN2F_PI_HI = 3.141592502826825;

/** `+-3pi/4` (`+0x298`/`+0x2a0`), and `+-pi/4` (`+0x2a8`/`+0x2b0`) */
export const ATAN2F_3PI4 = 2.356194490192345;
export const ATAN2F_NEG_3PI4 = -2.356194490192345;
export const ATAN2F_PI4 = 0.7853981633974483;
export const ATAN2F_NEG_PI4 = -0.7853981633974483;
