/**
 * Lane W1d — `log`, transcribed from the oracle's libm.
 *
 * PORT-NOTE(W1d/log-is-transcribed-not-approximated): `nrand()` (`utils/misc.cc`) and
 * `gsl_ran_ugaussian()` both feed `log()` a value in (0,1) and the result goes straight into
 * the model's arithmetic, so a 1-ulp difference changes logged bytes. Measured against the
 * oracle (macOS 26.5.2, arm64, this machine's libSystem), over the corpora in
 * `tests/rng.test.ts` plus a 180,000-value sweep:
 *
 *   `Math.log` (V8)                — 1 ulp off native on ~4.6% of sampled inputs
 *   fdlibm `e_log.c`               — ~5.7% off
 *   Arm optimized-routines `log`   — ~0.1% off (all 12 order/fma variants tried)
 *   a *correctly rounded* `log`    — still 1 ulp off on 0.06% (179,891/180,000); the
 *                                    oracle's libm is very accurate but not correctly rounded
 *
 * No approximation matches, so this is a transcription of the shipped function, instruction
 * by instruction, plus its data tables (`./appleLogTable.ts`, extracted from the running
 * libSystem — see `src/model/rng/native/README.md` for the extraction and verification
 * chain, which includes the C transcription that was diffed against the native `log` first).
 *
 * The algorithm: k = floor(log2 x) + 1, z = x / 2^(k-1) in [1,2); table index
 * `(2^44 + mantissa) >> 45` in 0..128 picks `invc ~ 1/c` and a two-part log(c) (for i >= 64
 * the stored value is log(c) - ln2 — that is what makes the k = 0 branch, i.e. x in
 * [0.5, 2), work); r = z*invc - 1 with one fused rounding; a factored polynomial
 * r^2(c0 + c1 r)(c2 + c3 r + r^2)(c4 + c5 r + r^2); and a split final sum. The k = 0 branch
 * masks r to 25 mantissa bits and adds the exact product error back, so nothing is lost to
 * rounding near log(x) = 0.
 *
 * JS has no `fma`, and the original's single-rounding fused steps are load bearing. `fma()`
 * below emulates it: Dekker/Knuth two-product gives the exact product, two-sum the exact
 * error of `+ c`, and both error terms are folded back in. Verified 0 mismatches against the
 * hardware `fma` on 2,000,000 random triples in these ranges, and the port reproduces the
 * native `log` bit-for-bit on every sampled input (203,640 of them).
 *
 * `sqrt` needs no such treatment: IEEE-754 requires it to be correctly rounded, and V8's is.
 *
 * PORT-NOTE(W1d/log-is-platform-specific): this is *this* platform's libSystem. A golden
 * recorded on another OS/CPU (glibc, or Apple Intel) could differ by an ulp, so the port
 * follows the machine the oracle was recorded on — the same rule `rand`/`drand48` follow.
 *
 * ---------------------------------------------------------------------------------------
 * `exp` (W1d follow-up): same story, measured the same way, and the numbers are in PARITY.md
 * (the libm census). The oracle's `exp` is **not** correctly rounded — over 8,261 corpus
 * values it matches the correctly rounded `e^x` on 8,255 (99.93 %), and V8's `Math.exp`
 * matches it on 7,876 (95.4 %) — so it is transcribed too, from its own machine code
 * (`native/raw/dump_exp_data.c`, `raw/expdis.s`). The algorithm is
 *
 *   t = x * 184.66496523378731 (128/ln2, high), n = floor(t), z = t - n
 *   tail = the exact residual of that reduction (two fused steps, one per half of 128/ln2)
 *   r = z + (table[n & 127].b + tail)
 *   p = C4 * r * (r*(z + C0) + C2) * (r*(z + C1) + C3)          -- e^(r*ln2/128) - 1
 *   exp(x) = table[n & 127].a * (1 + p) * 2^(n >> 7)
 *
 * with the 2^q scale applied by *adding q to the exponent field* (`q << 52` added to the bit
 * pattern — `asuint64` arithmetic, not an FP add) and a separate branch that computes the
 * subnormal results in the 2^-1022 domain. Two traps, both documented in
 * `native/raw/apple_exp_impl.h`: the exponent-field add is an integer add, and LLVM's
 * `fmsub Dd,Dn,Dm,Da` is `Da - Dn*Dm` while `fnmsub` is `Dn*Dm - Da` (settled by compiling
 * all three spellings and reading the encodings back — `raw/fmaenc2.c`).
 *
 * Verified: the C transcription of the same disassembly is bit-exact on the whole corpus and
 * on a 320,121-value sweep, and this port reproduces every corpus value (`tests/rng.test.ts`).
 *
 * ---------------------------------------------------------------------------------------
 * `sin` / `cos` (W1d follow-up: the rest of the libm census).  Both are on the model's
 * *frozen* motion path (`agent.cc:1150-1151` computes `dx = -dpos*sin(yaw()*DEGTORAD)`,
 * `dz = -dpos*cos(...)`) and in the camera (`CameraController.cc:78-80`), the census says
 * neither is correctly rounded (96.10 % / 96.14 %, max 1 ulp, against a `decimal` reference
 * at +40 digits), so they are transcribed the same way -- from the shipped machine code
 * (`native/raw/dump_libm2.c` -> `raw/sincos_bytes.bin`, tables generated by
 * `native/gen_sincos_table.py`, C transcription `raw/apple_sincos_impl.h` diffed against the
 * corpus before this port).  The algorithm, and the four traps:
 *
 *   |x| <= pi/4            sin(x) = x + x^3*poly_sin(x^2)
 *   |x| < 524288.61698514968   r = x - n*(pi/2) with a three-part pi/2 (exact subtraction),
 *                              reduced through a 6-coefficient sin or 7-coefficient cos tail
 *   else                   Payne-Hanek: a 1/pi fixed-point table (walked *backwards* by
 *                          `e >> 6`), a 192x64-bit product via `umulh`/`mul`/`adc`, then
 *                          the quadrant's tail and a `pi/2 * 2^63` fixed-point multiply
 *
 *  * the mask+normalise is not a scale change: after dropping the three quadrant bits the
 *    value is normalised to [2^63, 2^64) with `clz`, and the continuations undo that factor
 *    by subtracting `clz << 52` from the *bit pattern* of the converted double -- an integer
 *    subtract on a double register, i.e. an exact division by a power of two.  The cos
 *    continuation subtracts `2 * clz << 52`, because its value is squared.
 *  * the Payne-Hanek windows are little-endian slices of 1/pi (`ASC_TAB[15-k .. 18-k]`).
 *  * both sign flips are bit-pattern XORs (`eor.16b`, and `add d0, d0, +-0.0` for cos),
 *    never FP operations.
 *  * the flip is applied exactly once, where the machine code applies it.
 *
 * ---------------------------------------------------------------------------------------
 * `pow` (W1d follow-up: the last function of the libm census).  `pow` is on three genome
 * paths and in `utils/distributions.cc` (`Patch::setPoint`'s GAUSSIAN), the census says the
 * oracle's `pow` is not correctly rounded (4,373/4,471 = 97.81 %, V8 4,084 = 91.3 %), so it
 * gets the same treatment: a transcription of the shipped machine code
 * (`native/raw/dump_libm2.c` -> `raw/pow_bytes.bin` + `raw/pow_tables.bin`, tables extracted
 * and checked by `native/gen_pow_table.py`, C transcription `raw/apple_pow_impl.h` diffed
 * against the corpus before this port, 4,471/4,471 and 189,368/189,368 of a wide sweep).
 *
 * Unlike `exp`/`log`, `pow` does not call them: it inlines its *own* log reduction and its own
 * exp, with its own tables (both ~170 kB away from its code, reached by `adrp`+`add`):
 *
 *   log2 x (the 129-entry table, index = the rounded top 7 mantissa bits)
 *     k = ((int64)(bits x + 0xc018100000000000)) >> 52      ; floor(log2 x) + 1
 *     invc = LOG_INVC[i]; z = 1.f; r = invc*z - 1 (+ its exact product error)
 *     log2(1+r)/r = A + B r + C r^2 + r^3*(... poly ...)    ; A = 1/ln2, B = -1/(2 ln2), ...
 *     loghi = ((k + LOG_LOGC[i]) + <two terms>)             ; then `& 0xfffffffffffffffe`
 *     loglo = ((k - loghi + LOG_LOGC[i] + <two terms>)) + LOG_LOGC_LO[i] + <low part>
 *
 *   exp2(y*log2 x)
 *     t = (y*128) * loghi, residual = its exact product error + (y*128)*loglo
 *     n = floor(t), z = t - n, j = n & 127
 *     r = z + (residual - EXP_TAB[j].corr)                  ; *subtracted*, unlike `exp`
 *     poly = r * ((((c0*z + c1)*z + c2)*r + c3)*r + c4)
 *     result = (2^(n>>8) + EXP_TAB[j].x) * (1 + poly) * 2^((n>>7) - (n>>8))
 *
 * Three traps, all settled by experiment on the corpus rather than by reading:
 *
 *  * the exp assembly is bit-pattern arithmetic, not floating point: the `2^(n>>8)` term is
 *    the *pattern* `(n << 44) & 0xfff0000000000000` (a bare exponent field, biased later by
 *    adding the table entry's *pattern* -- the integer add also supplies the +1023 bias), the
 *    final scale is `((n << 45) & mask) - ((n << 44) & mask)` added to 1.0's pattern, and the
 *    negative base's sign is XORed into the first of those patterns.  Swapping that integer
 *    add for an FP multiply moves 4,262 of the 4,471 corpus values.
 *  * the log table's entries are *not* two little-endian doubles: the first 8 bytes are two
 *    32-bit halves packed `{ high word of invc, high word of logc_lo }` and the code reads
 *    only those halves (the low halves are zero by construction).  `invc` is a coarse
 *    hand-chosen reciprocal (within 2.4e-4 of 1/(1+i/128)) that only has to keep |r| under
 *    1/256; the accuracy lives in `logc_hi + logc_lo`, which is the *exact* `-log2(invc)`
 *    (minus 1 for the index >= 64 entries, the usual `k = floor(log2 x) + 1` convention).
 *    Dropping the logc_lo column moves 108 corpus values, dropping the exp table's correction
 *    1,055, and dropping the `& 0xfffffffffffffffe` on loghi 28.
 *  * the fast path is only for a positive normal `x` and a `y` in [2^-65, 2^64) (its second
 *    guard is an unsigned 64-bit subtract, so every negative `y` takes the ladder), and the
 *    *signed* `y` then drives the exponent arithmetic -- `t` is negative for a negative `y`
 *    and the two-shift exponent assembly handles a negative `n` directly, so no reciprocal is
 *    needed.  The ladder's `|y|` is only used for the range tests and the parity test
 *    (`fcvtzs` of `|y|` clamped to 2^53), which is what makes `y` is an odd integer`
 *    answerable for a negative base.
 *
 * ---------------------------------------------------------------------------------------
 * `powf` (the same follow-up: the *float* overload, which is what the two `_powf` sites in
 * the model really call -- `distributions.cc:41`'s `pow( e, rightTop/rightBottom )` inside
 * `normalPDF`/`getNormal`, and `Genome.cc:502`'s `pow( fabs(cosa), MISC_INVIS_SLOPE )`).
 * `pow` is **not** a stand-in for it: measured on the two sites' own argument domains, the
 * double transcription and V8's `Math.pow` are bit-identical to *each other* on all 797,034
 * pairs and each disagrees with the shipped `powf` on 0.13-0.90 % of them, all 1 ulp -- the
 * same "the float overload is its own function" finding `sinf`/`cosf` produced.  So `powf`
 * is transcribed from its own machine code (`native/raw/dump_libm4.c` -> `raw/powf_bytes.bin`
 * + `raw/powf_tables.bin`, tables extracted and checked by `native/gen_powf_table.py`, C
 * transcription `raw/apple_powf_impl.h` diffed against the 7,325-row corpus before this port).
 *
 * The shape is the same as `pow`'s -- an inlined log reduction with a table, an inlined exp
 * with another, everything in *double* until one `fcvt` at the end -- but every constant is
 * 128-scaled and the float side is only ever an *index*:
 *
 *   m = bits(x) - 0x3f338000
 *   i = (m >> 16) & 0x7f                      ; the 7-bit bin index
 *   k = asr32(m & 0xff800000, 16)             ; 128 * the binade (plus the bin's carry)
 *   w4 = bits(x) - (m & 0xff800000)           ; the residual as a *float* pattern, 1.mantissa
 *   z = (double) float(w4); r = z*invc[i] - 1 ; an `fnmsub` -- LLVM's `Dn*Dm - Da` order
 *   L = k + logc[i] + ((c0*r + c1)*r^2 + (c2*r + c3))*r
 *     = 128*log2(x)                           ; `logc[i]` is exactly `-128*log2(invc[i])`,
 *                                             ; so `L`'s terms cancel nothing
 *   t = (double)y * L, clamped to +-2^15; n = rinta(t); f = t - n; j = n & 0x7f
 *   bits = POWF_EXP_TAB[j] + (n << 45)        ; ONE 64-bit integer add, in % 2^64
 *   result = float( (double)bits * (1 + f*(e0*f + e1)) )   ; then `eor.8b` applies the sign
 *
 * Three traps:
 *
 *  * `L` is 128-scaled, so `powf` computes `2^(t/128)`, not `2^t`: the exp table's entries are
 *    `bits(2^(j/128)) - (j << 45)`, which is what makes the single `+ (n << 45)` exact (the
 *    subtraction never borrows, because `2^(j/128) - 1 > j/128` on [0,127]).
 *  * `fnmsub d0, d2, d0, d3` is `z*invc - 1`, the opposite of what the ARM manual's naming
 *    suggests (the same trap the `exp`/`pow` transcriptions document).  Written as
 *    `1 - z*invc` the correction has the wrong sign: measured on the corpus, that moves
 *    rows whose `z` is not exactly on the lattice (the model's own domain included).
 *  * the fast path never forms a reciprocal for a negative base and has no `|y|` at all: the
 *    sign for "negative base, odd integer exponent" is XORed into the *result pattern*
 *    (`eor.8b`) after the narrowing, and the ladder's answer for `|x| == 1` is `+-1.0f` with
 *    `y = +-inf`, `+0`/`-0`, `+inf`/`-inf` answered by a *bit mask*, not by arithmetic.
 *
 * PORT-NOTE(W1d-fu/math-pow-is-engine-version-dependent) — `pow` and `powf` above: how *far*
 * these transcriptions sit from V8's `Math.pow` is a property of V8, not of the port, and V8
 * moved under this repo.  Measured by walking the two committed corpora (`tests/rng.test.ts`
 * re-derives it on every run; `tools/measure_powf.ts` prints the `powf` line), rows on which
 * `Math.pow` disagrees with the *recorded oracle* bits:
 *
 *            `Math.pow` != oracle          V8 12.4   V8 13.6   V8 14.6
 *            `pow`  (4,471 rows)               387         9         9
 *            `powf` (7,325 rows)               196        42        42
 *
 * (node 22.22.2 / 24.21.0 / 26.7.0 — the first is the runtime an agent session gets, the other
 * two what a login shell resolves to through nvm's `default -> 24`.)  Both ports are off on
 * **0 rows under all three**: the transcription is the oracle's function whatever the engine
 * does.  The lane's tests therefore assert the *differential* contract — the oracle bit-for-bit
 * on every recorded row, and the oracle's side (never the engine's) wherever the engine
 * disagrees — with the engine-pinned counts left as a direction (`> 0`) rather than an equality.
 * An equality here is a claim about V8, and it is what turned `tests/rng.test.ts` red when the
 * shell's node switched from 22 to 24 with no change in this file.  (`native/raw/libm_census.out`
 * and the census' `V8` columns in `PARITY.md` are the same kind of number: a record of what one
 * V8 build did at census time, not a live assertion.)
 */

import { LOG_POLY, LOG_TAB_INVC, LOG_TAB_LOGC_HI, LOG_TAB_LOGC_LO } from './appleLogTable';
import {
  EXP_C0,
  EXP_C1,
  EXP_C2,
  EXP_C3,
  EXP_C4,
  EXP_LN2HI_N,
  EXP_LN2LO_N,
  EXP_TAB,
} from './appleExpTable';
import {
  COS_POLY,
  INV_PI2,
  MAGIC_PI2,
  PI2_HI,
  PI2_LO,
  PI2_MID,
  PI4,
  SIN_POLY,
  TAB,
  THRESH,
} from './appleSinCosTable';
import {
  SINF_C2M26,
  SINF_C2P26B,
  SINF_COS_POLY,
  SINF_INF_BITS,
  SINF_INV_PI2,
  SINF_PI2_HI,
  SINF_PI2_LO,
  SINF_SINCOS_POLY,
  SINF_SINPI_POLY,
  SINF_SIN_POLY,
  SINF_TAB,
} from './appleSinfTable';
import {
  POW_EXP_POLY,
  POW_EXP_TAB,
  POW_K_BIAS,
  POW_LOG_A,
  POW_LOG_A_LO,
  POW_LOG_H0,
  POW_LOG_H0_LO,
  POW_LOG_H1,
  POW_LOG_H1_LO,
  POW_LOG_HI_MASK,
  POW_LOG_INVC,
  POW_LOG_LOGC,
  POW_LOG_LOGC_LO,
  POW_LOG_POLY,
  POW_OVER_MUL,
  POW_SCALE,
  POW_T_MAX,
  POW_T_MIN,
  POW_UNDER_MUL,
  POW_Y_HUGE,
  POW_Y_TINY,
  POW_ZERO_BIAS,
} from './applePowTable';
import {
  POWF_EXP_POLY,
  POWF_EXP_TAB,
  POWF_FLT_MAX_BITS,
  POWF_LOG_BIAS,
  POWF_LOG_INVC,
  POWF_LOG_LOGC,
  POWF_LOG_POLY,
  POWF_T_CLAMP,
} from './applePowfTable';
import {
  ATAN2F_3PI4,
  ATAN2F_HPI,
  ATAN2F_NEG_3PI4,
  ATAN2F_NEG_HPI,
  ATAN2F_NEG_PI,
  ATAN2F_NEG_PI4,
  ATAN2F_PI,
  ATAN2F_PI4,
  ATAN2F_PI_HI,
  ATAN2F_POLY,
  ATAN2F_SMALL,
} from './appleAtan2fTable';

const DV = new DataView(new ArrayBuffer(8));

/** High 32 bits of a double's IEEE-754 pattern. */
function hiWord(x: number): number {
  DV.setFloat64(0, x, true);
  return DV.getUint32(4, true);
}

/** Low 32 bits of a double's IEEE-754 pattern. */
function loWord(x: number): number {
  DV.setFloat64(0, x, true);
  return DV.getUint32(0, true);
}

/** The double with the given 32-bit halves. */
function fromWords(hi: number, lo: number): number {
  DV.setUint32(0, lo >>> 0, true);
  DV.setUint32(4, hi >>> 0, true);
  return DV.getFloat64(0, true);
}

/** High word of `0xc018100000000000` — the exponent-bias constant. */
const K_BIAS_HI = 0xc0181000;
/** High word of `0xfffffffff8000000` — truncates a mantissa to its top 25 bits. */
const D6_MASK_HI = 0xfffffff8;
/** ln2 in two parts, as the algorithm uses it (`C6 + C7 === ln2`). */
const C6 = fromWords(0x3fe62e42, 0xf0000000);
const C7 = fromWords(0x3e5df473, 0xde6af279);
/** 2^44 and 2^45, for the table index `(2^44 + mantissa) >> 45`. */
const TWO44 = 17592186044416;
const TWO45 = 35184372088832;

/** Dekker's exact two-product error: `a*b === p + twoProdErr(a, b)`. */
function twoProdErr(a: number, b: number): number {
  const p = a * b;
  const ca = 134217729 * a; // 2^27 + 1
  const cb = 134217729 * b;
  const ah = ca - (ca - a);
  const bh = cb - (cb - b);
  const al = a - ah;
  const bl = b - bh;
  return (ah * bh - p + ah * bl + al * bh) + al * bl;
}

/**
 * `fma(a, b, c)` — the correctly rounded `a*b + c`, which JS lacks. Overflow-free for the
 * magnitudes this lane feeds it (|a*b| stays far inside the double range).
 *
 * Also used by `nrand.ts`/`mt19937.ts`, where the oracle's build *contracted* `u*u + v*v`
 * into `fma(u, u, v*v)` — see the PORT-NOTE there.
 */
export function fma(a: number, b: number, c: number): number {
  const p = a * b;
  const e = twoProdErr(a, b);
  const s = p + c;
  const bb = s - p;
  const t = p - (s - bb) + (c - bb); // exact error of fl(p + c)
  return s + (t + e);
}

/**
 * Natural logarithm, bit-identical to the oracle's libm `log()`.
 *
 * Edge cases follow the C library: `log(±0)` is -Infinity, `log(negative)` and `log(NaN)`
 * are NaN, `log(+Infinity)` is +Infinity.
 */
export function log(x: number): number {
  let ixHi = hiWord(x);
  let ixLo = loWord(x);

  // bits(x) - 2^52: negative, subnormal, inf and nan all land in the slow path
  const x2Hi = (ixHi - 0x00100000) >>> 0;
  if (x2Hi >= 0x7fe00000) {
    if (Number.isNaN(x)) return x;
    if (x === 0) return -Infinity;
    if (x < 0) return NaN;
    if ((x2Hi | 0) >= 0) return x; // +Infinity
    // subnormal: force the exponent to 1, subtract one, continue with those bits
    const shifted = fromWords(0x3ff00000 | ixHi, ixLo) - 1.0;
    ixHi = (hiWord(shifted) + 0xc0200000) >>> 0;
    ixLo = loWord(shifted);
  }

  // k = floor(log2 x) + 1, i.e. the 64-bit sum's arithmetic shift by 52, done on the high word
  const k = ((ixHi + K_BIAS_HI) | 0) >> 20;

  const mantHi = ixHi & 0x000fffff;
  const mant = mantHi * 4294967296 + ixLo; // exact: < 2^52
  const idx = Math.floor((TWO44 + mant) / TWO45);
  const invc = LOG_TAB_INVC[idx]!;
  const logcHi = LOG_TAB_LOGC_HI[idx]!;
  const logcLo = LOG_TAB_LOGC_LO[idx]!;
  const z = fromWords(0x3ff00000 | mantHi, ixLo);

  const d1 = fma(z, invc, -1.0); // r, product rounded once
  const d16 = fma(d1, LOG_POLY[1]!, LOG_POLY[0]!);
  const d19 = d1 + LOG_POLY[3]!;
  const d21 = d1 + LOG_POLY[5]!;
  let d4 = d1 * d1;
  const d18 = fma(d1, d19, LOG_POLY[2]!);
  const d20 = fma(d1, d21, LOG_POLY[4]!);
  d4 = d4 * d16;
  d4 = d4 * d18;
  d4 = d4 * d20;

  if (k === 0) {
    // x in [0.5, 2): split r so nothing is lost to rounding
    const d5 = invc * z;
    const d6 = d5 - 1.0;
    const d5e = fma(invc, z, -d5); // exact error of the product
    const rHi = fromWords(hiWord(d6) & D6_MASK_HI, 0);
    let d2 = d5e + (d6 - rHi);
    let out = rHi + logcHi;
    d2 = d2 + logcLo;
    d2 = d2 + d4;
    out = out + d2;
    return out;
  }

  const kf = k;
  let d2 = fma(kf, C7, logcLo);
  const d3 = fma(kf, C6, logcHi);
  d2 = d2 + d4;
  return d3 + (d1 + d2);
}

/** `0xc0874a0000000000` as the shipped code compares it: a *signed* 64-bit comparison. */
const T_NEG_HI_SIGNED = 0xc0874a00 | 0; // -1065005056
/** High word of `0x40862e42fefa39f0` — the dispatch threshold (its low word below). */
const T_HI_HI = 0x40862e42;
const T_HI_LO = 0xfefa39f0;
/** High word of `0x0010000000000000` (2^-1022), the subnormal path's tail scale. */
const S_TAIL_HI = 0x00100000;
/** 2^-1022, the double the subnormal path multiplies by at the end. */
const TWO_M1022 = fromWords(S_TAIL_HI, 0);
/** `0x7fefffffffffffff` — DBL_MAX, the overflow path's multiplier. */
const DBL_MAX = fromWords(0x7fefffff, 0xffffffff);
/** 2^20: a `q << 52` on the 64-bit pattern is `(q << 20)` on its high word. */
const Q_SHIFT_HI = 1048576;

/**
 * Natural exponential, bit-identical to the oracle's libm `exp()`.
 *
 * Transcribed from the shipped machine code; the algorithm and the two traps (an *integer*
 * add of the bit patterns for the `2^q` scale, and the two fused halves of `128/ln2`) are
 * documented in this file's header and in `src/model/rng/native/raw/apple_exp_impl.h`.
 *
 * Edge cases follow the C library: `exp(+Infinity)` is `+Infinity`, `exp(-Infinity)` is 0,
 * `exp(NaN)` is NaN, `exp(±0)` is 1, and results below `2^-1022` are subnormals (`exp(x)`
 * underflows to 0 for `x < -745.25`).
 */
export function exp(x: number): number {
  const hi = hiWord(x);
  const lo = loWord(x);

  // if (bits(x) >= 0x40862e42fefa39f0) — unsigned, so this also catches every negative x
  if (hi > T_HI_HI || (hi === T_HI_HI && lo >= T_HI_LO)) {
    // if (signed(bits(x)) >= signed(0xc0874a0000000000)) — i.e. x > -745.25, +inf, any NaN
    if ((hi | 0) >= T_NEG_HI_SIGNED) {
      if (!(x < 0)) return x * DBL_MAX;
      // the csel: -inf gets a zero (no underflow flag), any other huge negative 2^-1022
      const s = hi >= 0xfff00000 ? 0 : S_TAIL_HI;
      const d = fromWords(s, 0);
      return d * d;
    }
  }

  const t = x * EXP_LN2HI_N;
  // fcvtms + scvtf: the conversion to an integer and back drops -0's sign
  const n = Math.floor(t) + 0;
  const z = t - n;
  const e1 = fma(-x, EXP_LN2HI_N, t); // t - x*ln2hiN, fused (fmsub)
  const tail = fma(x, EXP_LN2LO_N, -e1); // x*ln2loN - e1, fused (fnmsub)

  const j = n & 127;
  const tab = EXP_TAB[j]!;
  const a = tab[0];
  const b = tab[1];

  const d16 = z + EXP_C0;
  const s1 = b + tail;
  const d17 = z + EXP_C1;
  const r = z + s1;
  const d18 = fma(r, d16, EXP_C2);
  const d19 = fma(r, d17, EXP_C3);
  let p = r * EXP_C4;
  p = p * d18;
  p = p * d19;

  const q = n >> 7;

  if (q + 1022 < 0) {
    // subnormal result: the shipped code computes it in the 2^-1022 domain and scales at the
    // end, so the exponent-field add here is `(q + 1022) << 52` (an integer add of patterns)
    const d0 = fromWords((hiWord(a) + Math.imul(q + 1022, Q_SHIFT_HI)) >>> 0, loWord(a));
    const d3 = d0 + 1.0;
    let d4 = d0 - (d3 - 1.0);
    d4 = fma(d0, p, d4);
    return (d3 + d4 - 1.0) * TWO_M1022;
  }

  const scaled = fma(p, a, a); // a * (1 + p)
  return fromWords((hiWord(scaled) + Math.imul(q, Q_SHIFT_HI)) >>> 0, loWord(scaled));
}

/* ---------------------------------------------------------------- sin / cos (see above) */

const M64 = (1n << 64n) - 1n;
const SIGN64 = 1n << 63n;
const DV64 = new DataView(new ArrayBuffer(8));

/** The 64-bit IEEE-754 pattern of `x`. */
function phBits(x: number): bigint {
  DV64.setFloat64(0, x, true);
  return DV64.getBigUint64(0, true);
}

/** The double with the given 64-bit pattern. */
function phFrom(u: bigint): number {
  DV64.setBigUint64(0, u & M64, true);
  return DV64.getFloat64(0, true);
}

/** The high 64 bits of `a * b` — the machine code's `umulh`. */
function umulh(a: bigint, b: bigint): bigint {
  return ((a & M64) * (b & M64)) >> 64n;
}

/**
 * `sub Dd, Dd, Xscale` with `Xscale = clz << 52`: an *integer* subtract of the double's bit
 * pattern, which is the exact division by 2^clz the machine code uses to undo the
 * normalisation of the Payne-Hanek mantissa (the same trick `exp` uses in reverse).
 */
function unscale(v: number, clz: bigint): number {
  return phFrom(phBits(v) - (clz << 52n));
}

/**
 * `ucvtf Dd, Xn, #fbits`: the correctly rounded `x / 2^fbits`.  JS has no exact
 * bigint->double conversion with a defined tie rule, and `Number(bigint)` would be the wrong
 * operation anyway (a bit pattern is not a value), so the rounding is done here by hand:
 * nearest, ties to even, exactly as the instruction does.
 */
function ucvtf(x: bigint, fbits: number): number {
  if (x === 0n) return 0;
  if (x < 1n << 53n) return Number(x) / 2 ** fbits;
  const shift = BigInt(x.toString(2).length - 53); // keep the top 53 bits, round on the rest
  const top = x >> shift;
  const rest = x & ((1n << shift) - 1n);
  const half = 1n << (shift - 1n);
  const m = rest > half || (rest === half && (top & 1n) === 1n) ? top + 1n : top;
  return (Number(m) * 2 ** Number(shift)) / 2 ** fbits;
}

/** The sign toggle both tails end with. */
function flip(v: number, x10: bigint): number {
  return phFrom(phBits(v) ^ (x10 & SIGN64));
}

/** `1 + z * poly_cos(z)` — the cos polynomial, in its own variable. */
function cosPoly(z: number): number {
  let p = COS_POLY[0]!;
  for (let i = 1; i < 7; i++) p = fma(z, p, COS_POLY[i]!);
  return fma(z, p, 1);
}

/** The medium-path cos tail: z = 2*(d6*d7) + d6^2, then the polynomial. */
function cosEval(d6: number, d7: number): number {
  return cosPoly(fma(d6, d6, 2 * (d6 * d7)));
}

/** The sin tail: r + r*(r^2*poly_sin(r^2)), with the reduced argument's split hi/lo. */
function sinEval(r: number, d6: number, d7: number): number {
  const z = r * r;
  let p = SIN_POLY[0]!;
  for (let i = 1; i < 6; i++) p = fma(z, p, SIN_POLY[i]!);
  return d6 + fma(r, z * p, d7);
}

/** The cos-poly Payne-Hanek continuation (0x78c): the product is squared. */
function phCosTail(x: bigint, clz: bigint, x10: bigint): number {
  const x3a = umulh(MAGIC_PI2, x);
  const x3 = umulh(x3a, x3a);
  return flip(cosPoly(unscale(ucvtf(x3, 58), clz + clz)), x10);
}

/** The sin-poly Payne-Hanek continuation (0x674). */
function phSinTail(x: bigint, clz: bigint, x10: bigint): number {
  const x4 = umulh(MAGIC_PI2, x);
  return flip(
    sinEval(
      unscale(ucvtf(x4, 61), clz),
      unscale(ucvtf(x4 & 0xffff000000000000n, 61), clz),
      unscale(ucvtf(x4 & 0x0000ffffffffffffn, 61), clz),
    ),
    x10,
  );
}

/**
 * The shared Payne-Hanek reduction for `|x| >= 524288.61698514968`.  `ux` is `bits(x)` for
 * `sin` (which extracts the sign itself) and `bits(|x|)` for `cos`; `wantSin` selects sin's
 * `b.mi` / cos's `b.pl` continuation choice.
 */
function phReduce(ux: bigint, wantSin: boolean): number {
  const e = Number(((ux & ~SIGN64) >> 52n) - 0x3ffn);
  const x9 = (SIGN64 | (ux << 11n)) & M64;
  const k = e >> 6;
  const s = e & 63;
  const w0 = TAB[15 - k]!;
  const w1 = TAB[16 - k]!;
  const w2 = TAB[17 - k]!;
  const w3 = TAB[18 - k]!;
  let x4: bigint;
  let x5: bigint;
  let x6: bigint;
  if (s) {
    const t = BigInt(64 - s);
    x4 = ((w0 >> t) | (w1 << BigInt(s))) & M64;
    x5 = ((w1 >> t) | (w2 << BigInt(s))) & M64;
    x6 = ((w2 >> t) | (w3 << BigInt(s))) & M64;
  } else {
    x4 = w1;
    x5 = w2;
    x6 = w3;
  }
  // the 192x64-bit product's top 128 bits: `umulh`/`mul`/`adc`
  const h4 = umulh(x4, x9);
  const l5 = (x5 * x9) & M64;
  const a = h4 + l5;
  const x0 = a & M64;
  const x1 = (umulh(x5, x9) + ((x6 * x9) & M64) + (a > M64 ? 1n : 0n)) & M64;
  // the quadrant: the one's complement, the sign-to-apply, and which tail runs
  const x2c = ((x1 >> 61n) & 1n) === 1n ? M64 : 0n;
  const x10 = (wantSin ? ux ^ x1 : x1 ^ ((x1 << 1n) & M64)) & SIGN64;
  const test = (((x1 << 2n) ^ (x1 << 1n)) & SIGN64) !== 0n;
  const cosTail = wantSin ? test : !test;
  const v = (x1 ^ x2c) & 0x1fffffffffffffffn;
  // v is never 0 here (the product's top word is >= 83000 for |x| >= 2^19), so clz <= 61
  const clz = BigInt(64 - v.toString(2).length);
  const x1n = ((v << clz) | ((x0 ^ x2c) >> (64n - clz))) & M64;
  return cosTail ? phCosTail(x1n, clz, x10) : phSinTail(x1n, clz, x10);
}

/** `frintn`: round to nearest, ties to even (JS's `Math.round` breaks ties away from zero). */
function rint(x: number): number {
  const f = Math.floor(x);
  const d = x - f;
  if (d > 0.5) return f + 1;
  if (d < 0.5) return f;
  return f % 2 === 0 ? f : f + 1;
}

/**
 * `rint` followed by the machine code's integer conversion (`fcvtns`/`fcvtzs`): an out-of-range
 * operand **saturates** on ARM, and the shipped float functions depend on it — past ~2^63 the
 * reduced argument is meaningless and only the quadrant's low bits are read at all.  A plain
 * `BigInt(value)` would keep the whole magnitude and read *different* parity bits, which is
 * visible for `|x| > 1e19` (e.g. `sincosf(3.4e38)`).
 */
function toInt64(v: number): bigint {
  if (v >= 9223372036854775808) return 9223372036854775807n;
  if (v <= -9223372036854775809) return -9223372036854775808n;
  return BigInt(v);
}

/**
 * Sine, bit-identical to the oracle's libm `sin()`.
 *
 * Edge cases follow the C library: `sin(±0)` is ±0, `sin(±Infinity)` and `sin(NaN)` are NaN
 * (`x - x`).
 */
export function sin(x: number): number {
  if (x === 0) return x;
  const ax = Math.abs(x);
  if (ax <= PI4) return sinEval(x, 0, x);
  if (ax < THRESH) {
    const n = rint(x * INV_PI2);
    const i = BigInt(n);
    const r = x - n * PI2_HI;
    const d6 = r - n * PI2_MID;
    const d7 = r - d6 - n * PI2_MID - n * PI2_LO;
    const x10 = (i << 62n) & SIGN64;
    const d = i & 1n ? cosEval(d6, d7) : sinEval(d6 + d7, d6, d7);
    return flip(d, x10);
  }
  if (!(ax < Infinity)) return x - x;
  return phReduce(phBits(x), true);
}

/**
 * Cosine, bit-identical to the oracle's libm `cos()`.
 *
 * Edge cases follow the C library: `cos(±0)` is 1, `cos(±Infinity)` and `cos(NaN)` are NaN.
 */
export function cos(x: number): number {
  const ax = Math.abs(x);
  if (ax <= PI4) return cosEval(ax, 0);
  if (ax < THRESH) {
    const n = rint(ax * INV_PI2);
    const i = BigInt(n);
    const r = ax - n * PI2_HI;
    const d6 = r - n * PI2_MID;
    const d7 = r - d6 - n * PI2_MID - n * PI2_LO;
    const x10 = ((i ^ (i >> 1n)) << 63n) & SIGN64;
    const d = i & 1n ? sinEval(d6 + d7, d6, d7) : cosEval(d6, d7);
    return flip(d, x10);
  }
  if (!(ax < Infinity)) return ax - ax;
  return phReduce(phBits(ax), false);
}

/* ---------------------------------------------------------------- sinf / cosf (see above) */

const DV32 = new DataView(new ArrayBuffer(4));

/** The float32 bit pattern of `x` (`x` must already be float32-valued). */
function f32Bits(x: number): number {
  DV32.setFloat32(0, x, true);
  return DV32.getUint32(0, true);
}

/** The float32 with the given bit pattern. */
function f32From(u: number): number {
  DV32.setUint32(0, u >>> 0, true);
  return DV32.getFloat32(0, true);
}

/** `eor` on the double's bit pattern — a sign toggle when the mask is 2^63. */
function xorBits(v: number, mask: bigint): number {
  return phFrom(phBits(v) ^ mask);
}

/** The shipped `sin(r)` tail: `r + r^3*c2 + r^5*(c1 + r^2*c0)`, the machine code's steps. */
function sinfSinPoly(r: number): number {
  const z = r * r;
  const r3 = r * z;
  const a = fma(z, SINF_SIN_POLY[0]!, SINF_SIN_POLY[1]!);
  const r5 = z * r3;
  const b = fma(r3, SINF_SIN_POLY[2]!, r);
  return fma(r5, a, b);
}

/** The shipped `cos(r)` tail: `1 + z*(z^2*(z*c0 + c1) + (z*c2 + c3))`, `z = r^2`. */
function sinfCosPoly(r: number): number {
  const z = r * r;
  const a = fma(z, SINF_COS_POLY[0]!, SINF_COS_POLY[1]!);
  const b = fma(z, SINF_COS_POLY[2]!, SINF_COS_POLY[3]!);
  const c = z * z;
  const d = fma(c, a, b);
  return fma(z, d, 1);
}

/** The pi/2-reduction tail: tail by bit 0 of the quadrant, sign flip by bit 1. */
function sinfQuadrant(r: number, i: bigint): number {
  const mask = ((i >> 1n) << 63n) & SIGN64;
  const out = (i & 1n) !== 0n ? sinfCosPoly(r) : sinfSinPoly(r);
  return Math.fround(xorBits(out, mask));
}

/**
 * The large-argument (mod pi) tail both table paths share.  `d4` is `x*hi` (plus the `0.5`
 * cosf adds), `d5` is `x*lo`.  The sign is an XOR of `r`'s *pattern*, so it rides through the
 * polynomial as a `±r` factor.
 */
function sinfPiTail(d4: number, d5: number): number {
  const nd = rint(d4);
  const n = toInt64(nd);
  const r = d4 - nd + d5;
  const sr = xorBits(r, (BigInt.asUintN(64, n) << 63n) & SIGN64);
  const z = r * r;
  const a = z + SINF_SINPI_POLY[0]!;
  const b = z + SINF_SINPI_POLY[1]!;
  const p = fma(z, a, SINF_SINPI_POLY[2]!);
  const q = fma(z, b, SINF_SINPI_POLY[3]!);
  return Math.fround(sr * p * (SINF_SINPI_POLY[4]! * q));
}

/**
 * Sine of a float32 argument, bit-identical to the oracle's libm `sinf()` — the C++ `float`
 * overload `CameraController.cc:78-80` actually calls.
 *
 * This is not `Math.fround( sin( x ) )`: the double transcription rounded to float32 disagrees
 * with the shipped `sinf` on 304 of the 5,016 corpus arguments (6.1 %), because the float32
 * argument can sit close enough to a midpoint of the float result that the intermediate double
 * rounding decides it.  The algorithm (see `src/model/rng/native/raw/apple_sinf_impl.h`):
 *
 *   |x| < 2^-12     fmaf(x, 2^26, x) * 2^-26, all in single precision
 *   |x| < pi/4      r + r^3*c2 + r^5*(c1 + r^2*c0), 3 coefficients, in double
 *   |x| < 120       n = rint(x * 2/pi), r = x - n*pi/2 (one fused step), then the quadrant
 *   otherwise       the 1/pi table: `n = rint(x*hi)`, `r = frac + x*lo`, then `sin(pi*r)/r`
 *
 * Unlike the double `sin`, the medium reduction uses a *single-part* pi/2 (there is no
 * Payne-Hanek path at all) and the large-argument reduction multiplies by the per-exponent
 * `1/pi - A/2^s` from `SINF_TAB`, never by `1/pi` itself — see the table module and the
 * PORT-NOTE in this file's header.
 *
 * Edge cases follow the C library: `sinf(±0)` is ±0, `sinf(±Infinity)` and `sinf(NaN)` are NaN.
 */
export function sinf(x: number): number {
  const w0 = f32Bits(x) & 0x7fffffff;
  if (w0 >= 0x42f00000) {
    // |x| >= 120.0f: the table reduction (no Payne-Hanek, no two-part pi/2)
    if (w0 >= SINF_INF_BITS) return Math.fround(x - x);
    const e = SINF_TAB[(w0 >>> 24) - 0x40]!;
    return sinfPiTail(x * e[0], x * e[1]);
  }
  if (w0 < 0x3f490fdb) {
    // |x| < pi/4 (the float32 neighbour of pi/4 is the boundary the shipped code compares)
    if (w0 < 0x39800000) {
      // |x| < 2^-12: the shipped `fmadd s0, s0, s2, s0` + `fmul s0, s0, s4`, single precision.
      // `x*2^26 + x` is *exact* in double (an exponent gap of 26 below 24 significand bits),
      // so the plain expression rounds exactly once, like the fused step -- and, unlike the
      // emulated `fma`, it keeps the sign of `sinf(-0)`.
      return Math.fround((x * SINF_C2P26B + x) * SINF_C2M26);
    }
    return Math.fround(sinfSinPoly(x));
  }
  const t = x * SINF_INV_PI2;
  const nd = rint(t);
  return sinfQuadrant(fma(-nd, SINF_PI2_HI, x), toInt64(nd));
}

/**
 * Cosine of a float32 argument, bit-identical to the oracle's libm `cosf()`.
 *
 * The same shape as `sinf` with `|x|` from the start, and two differences: the table path
 * starts at 2^26 (120..2^26 subtracts a *two-part* pi/2 instead) and the quadrant index is
 * `n + 1`, because `cos(x) = sin(x + pi/2)` and only the index's low two bits are ever read.
 * The large-argument path adds the `0.5` that makes the reduction land on `x/pi + 1/2`.
 *
 * `Math.fround( cos( x ) )` disagrees with the shipped `cosf` on 135 of the corpus's 5,016
 * arguments (2.7 %).
 *
 * Edge cases follow the C library: `cosf(±0)` is 1, `cosf(±Infinity)` and `cosf(NaN)` are NaN.
 */
export function cosf(x: number): number {
  const ax = Math.abs(x);
  const w0 = f32Bits(ax);
  if (w0 >= 0x42f00000) {
    if (w0 >= 0x4c800000) {
      // |x| >= 2^26: the table reduction, with the +1/2 of the cos identity
      if (w0 >= SINF_INF_BITS) return Math.fround(ax - ax);
      const e = SINF_TAB[(w0 >>> 24) - 0x40]!;
      const d4 = ax * e[0] + 0.5;
      return sinfPiTail(d4, ax * e[1]);
    }
    // 120 <= |x| < 2^26: a two-part pi/2, still one index away
    const t = ax * SINF_INV_PI2;
    const nd = rint(t);
    return sinfQuadrant(fma(-nd, SINF_PI2_LO, fma(-nd, SINF_PI2_HI, ax)), toInt64(nd) + 1n);
  }
  if (w0 < 0x3f490fdb) {
    if (w0 < 0x39800000) {
      // |x| < 2^-12: (2^26 - |x|) * 2^-26 in single precision, i.e. 1.0f
      return Math.fround(Math.fround(SINF_C2P26B - ax) * SINF_C2M26);
    }
    return Math.fround(sinfCosPoly(ax));
  }
  const t = ax * SINF_INV_PI2;
  const nd = rint(t);
  return sinfQuadrant(fma(-nd, SINF_PI2_HI, ax), toInt64(nd) + 1n);
}

/* ------------------------------------------------------------- sincosf (see above) */

/**
 * `__sincosf_stret`'s two-lane tail: `(sin, cos)` of `pi*(n + u)/2` for a reduced `u` and a
 * quadrant `n`.  The shipped code evaluates both lanes in one 2-vector pass and narrows them to
 * float32 *before* the sign is applied.
 */
function sincosfTail(u: number, n: bigint): readonly [number, number] {
  const z = u * u;
  const ev0 = fma(z, z + SINF_SINCOS_POLY[0]!, SINF_SINCOS_POLY[6]!);
  const ev1 = fma(z, z + SINF_SINCOS_POLY[1]!, SINF_SINCOS_POLY[7]!);
  const od0 = fma(z, z + SINF_SINCOS_POLY[2]!, SINF_SINCOS_POLY[8]!);
  const od1 = fma(z, z + SINF_SINCOS_POLY[3]!, SINF_SINCOS_POLY[9]!);
  let f0 = Math.fround(u * SINF_SINCOS_POLY[4]! * ev0 * od0);
  let f1 = Math.fround(SINF_SINCOS_POLY[5]! * ev1 * od1);
  if ((n & 2n) !== 0n) {
    f0 = -f0;
    f1 = -f1;
  }
  return (n & 1n) !== 0n ? [f1, -f0] : [f0, f1];
}

/**
 * `(sin x, cos x)` of a float32 argument, bit-identical to the oracle's `__sincosf_stret` — the
 * two-output entry point in the `sinf`/`cosf` unit (`sinf + 0x1ac`), **not** a pair of
 * `sinf`/`cosf` calls.
 *
 * This is the function the native `CameraController::setRotationAngle( float )` actually calls:
 * it has adjacent `sin(camrad)`/`cos(camrad)` calls and LLVM's sincos combine merges them, so
 * the shipped `libpolyworld.dylib` contains `bl ___sincosf_stret` (measured from the symbol
 * stub).  It is a *different* algorithm from the scalar pair — it reduces with the **doubled**
 * argument against the `SINF_TAB` entry (`2x*hi`, no `+0.5`), gives the medium path no `pi/2`
 * subtraction at all (`u = x*2/pi - rint(x*2/pi)`, the quadrant carries the rest) and evaluates
 * the sine and cosine lanes together — and it disagrees with `cosf` on ordinary arguments
 * (e.g. `x = -1.1122977733612061f`: `cosf` gives `0x3ee29cc2`, this gives `0x3ee29cc3`), which
 * is exactly what the recorded camera frames pin (see `L14`'s PORT-NOTE and PARITY.md).
 *
 * Edge cases follow the C library, except that the shipped code's `+-inf`/NaN row computes
 * `x - x` and then copies it into both outputs (`fsub s0, s0, s0` leaves NaN in `s0` = `v0[0]`,
 * and `mov s1, v0[0]` moves it into the cosine), so `sincosf(+-inf)` is `(NaN, NaN)`.
 */
export function sincosf(x: number): readonly [number, number] {
  const w0 = f32Bits(x) & 0x7fffffff;
  if (w0 >= 0x42f00000) {
    if (w0 >= SINF_INF_BITS) {
      const nan = Math.fround(x - x);
      return [nan, nan];
    }
    const e = SINF_TAB[(w0 >>> 24) - 0x40]!;
    const d0 = x + x; // fadd d0, d0, d0 -- the doubled argument, exact
    const d4 = d0 * e[0];
    const nd = rint(d4);
    return sincosfTail(d4 - nd + d0 * e[1], toInt64(nd));
  }
  if (w0 < 0x39800000) {
    // |x| < 2^-12, computed in single precision like the shipped code
    const cos = Math.fround(Math.fround(SINF_C2P26B - Math.abs(x)) * SINF_C2M26);
    const sin = Math.fround((x * SINF_C2P26B + x) * SINF_C2M26);
    return [sin, cos];
  }
  const t = x * SINF_INV_PI2;
  const nd = rint(t);
  return sincosfTail(t - nd, toInt64(nd));
}

/* ------------------------------------------------------------------- pow (see above) */
/** bit patterns of the constants `pow` compares against (see the PORT-NOTE). */
const P_SIGN = 0x8000000000000000n;
const P_ONE = 0x3ff0000000000000n;
const P_INF = 0x7ff0000000000000n;
const P_MANT = 0x000fffffffffffffn;
/** the u64 `2^52` the subnormal test compares the pattern against (the double 2^-1022). */
const P_2P52 = 0x0010000000000000n;
const P_2P53 = 0x4340000000000000n;
/** the mask the two exponent shifts of the exp assembly end with. */
const P_EXP_FIELD = 0xfff0000000000000n;

/** `1 / x` as the machine code's `fdiv` for a zero or infinite base. */
function pDiv(x: number): number {
  return 1 / x;
}

/** `pow`'s `2^(t/128)` (0x570..0x608), entered with `t` and its exact residual. */
function powExp2(t: number, residual: number, xsign: bigint): number {
  if (t > POW_T_MAX) return pOverflow(xsign);
  if (t < POW_T_MIN) return pUnderflow(xsign);
  const n = Math.floor(t);
  const z = t - n;
  const ni = BigInt(n);
  const tab = POW_EXP_TAB[Number(ni & 127n)]!;
  const r = residual - tab[1] + z;
  let p = fma(POW_EXP_POLY[0]!, z, POW_EXP_POLY[1]!);
  p = fma(p, z, POW_EXP_POLY[2]!);
  p = fma(p, r, POW_EXP_POLY[3]!);
  p = fma(p, r, POW_EXP_POLY[4]!);
  p = r * p;
  // the exponent-field assembly: 2^(n>>8) as a bare pattern (XORed with the negative base's
  // sign), integer-added to the table entry's pattern -- that add is also what supplies the
  // +1023 bias -- then scaled by 2^((n>>7)-(n>>8)), built the same way
  const hiBits = (ni << 44n) & P_EXP_FIELD;
  const loBits = (((ni << 45n) & P_EXP_FIELD) - hiBits) & M64;
  const base = phFrom((phBits(phFrom(hiBits ^ xsign)) + phBits(tab[0])) & M64);
  const scaled = fma(base, p, base);
  return scaled * phFrom((loBits + P_ONE) & M64);
}

/** `pow`'s log2 x (0x444..0x560) followed by its exp2. */
function powLog(ux: bigint, y: number, xsign: bigint): number {
  const mant = ux & P_MANT;
  const i = Number((((mant + 0x100000000000n) & 0x1fe00000000000n) >> 41n) >> 4n);
  const k = Number(BigInt.asIntN(64, ux + POW_K_BIAS) >> 52n);
  const invc = POW_LOG_INVC[i]!;
  const z = phFrom(P_ONE | mant);
  const prod = invc * z;
  const r = prod - 1;
  const zhi = phFrom(phBits(z) & 0xffffffffffe00000n);
  const perr = fma(invc, z - zhi, fma(invc, zhi, -prod));
  let d3 = fma(r, POW_LOG_POLY[0]!, POW_LOG_POLY[1]!);
  d3 = fma(r, d3, POW_LOG_POLY[2]!);
  d3 = fma(r, d3, POW_LOG_POLY[3]!);
  d3 = fma(r, d3, POW_LOG_POLY[4]!);
  let d4 = r * r;
  d4 = d4 * d4;
  d3 = d4 * d3;
  // log2(1+r)/r = A + B r + C r^2 + ..., carried as an accurate two-part value: every fused
  // step's exact error is recovered with an fnmsub and folded into the low part
  let d6 = fma(POW_LOG_H0, r, POW_LOG_H1);
  let d7 = fma(POW_LOG_H0_LO, r, POW_LOG_H1_LO);
  let d5 = d6 - POW_LOG_H1;
  d5 = fma(POW_LOG_H0, r, -d5);
  d7 = fma(POW_LOG_H0, perr, d7);
  d7 = d5 + d7;
  d4 = fma(d6, r, POW_LOG_A);
  d5 = fma(d7, r, POW_LOG_A_LO);
  d7 = d4 - POW_LOG_A;
  d7 = fma(d6, r, -d7);
  d5 = fma(d6, perr, d5);
  d5 = d7 + d5;
  d6 = d4 * r;
  d5 = d5 * r;
  d7 = fma(d4, r, -d6);
  d5 = fma(d4, perr, d5);
  d7 = d7 + d5;
  // the hi/lo split: the shipped code drops loghi's last mantissa bit first
  const tail = POW_LOG_LOGC[i]!;
  const loghi = phFrom(phBits((k + tail + d6) + d3) & POW_LOG_HI_MASK);
  const loglo = (((k - loghi + tail) + d6) + d3) + POW_LOG_LOGC_LO[i]! + d7;
  const y128 = y * POW_SCALE;
  const t = y128 * loghi;
  return powExp2(t, fma(y128, loglo, fma(y128, loghi, -t)), xsign);
}

/** `pow`'s exp2 called with `1/2^1022` squared: the underflow path (0x7ac). */
function pUnderflow(xsign: bigint): number {
  const t = phFrom(POW_UNDER_MUL);
  return t * phFrom(xsign | phBits(t));
}

/** `pow`'s exp2 called with `DBL_MAX` rounded up: the overflow path (0x7d0). */
function pOverflow(xsign: bigint): number {
  const t = phFrom(POW_OVER_MUL);
  return t * phFrom(xsign | phBits(t));
}

/** 0x444: x is a power of two, so log2 x is exact -- no log reduction at all. */
function powPowerOfTwo(ux: bigint, y: number, xsign: bigint): number {
  const d = BigInt.asIntN(64, ux - P_ONE);
  if (d === 0n) return phFrom(xsign | P_ONE);
  const t0 = Number(d) * 2 ** -45; // `scvtf d0, x0, #45` == 128 * log2|x|
  const t = t0 * y;
  return powExp2(t, fma(t0, y, -t), xsign);
}

/** 0x444's entry point: split on the mantissa and take the log or the exact shortcut. */
function powFromBits(ux: bigint, y: number, xsign: bigint): number {
  if ((ux & P_MANT) !== 0n) return powLog(ux, y, xsign);
  return powPowerOfTwo(ux, y, xsign);
}

/** 0x628: everything the fast path excludes. */
function powSpecial(x: number, y: number): number {
  const ux = phBits(x);
  const uy = phBits(y);
  const one = (sign: bigint) => phFrom(sign | P_ONE);
  const invalid = () => Infinity - Infinity;

  if (ux === P_ONE) return x; // 0x62c
  if (uy === P_ONE) return x === x ? x : x + x; // 0x638..0x760

  const axb = ux & 0x7fffffffffffffffn;
  const ayb = uy & 0x7fffffffffffffffn;
  const ax = phFrom(axb);
  const ay = phFrom(ayb);
  const Y_HUGE = phFrom(POW_Y_HUGE);
  const Y_TINY = phFrom(POW_Y_TINY);
  let xsign = 0n;

  /** 0x714: x is +-0 (or +-inf), so the result is +-0 / +-inf or the reciprocal. */
  const xZero = (d0: number): number => {
    if (ay >= 1) {
      const clamp = phFrom(ayb < P_2P53 ? ayb : P_2P53); // 0x71c..0x724
      if (Math.trunc(clamp) === clamp && (BigInt(Math.trunc(clamp)) & 1n) === 1n) {
        return (uy & P_SIGN) === 0n ? d0 : pDiv(d0); // an odd integer keeps x's sign
      }
    }
    const even = phFrom(axb); // 0x740: only |x| survives
    return (uy & P_SIGN) === 0n ? even : pDiv(even);
  };

  /** 0x6a4: the |y| range tests, then the log path (via the subnormal normaliser). */
  const yRange = (uxs: bigint, sign: bigint): number => {
    if (ay > Y_HUGE) {
      // 0x798: |y| > 2^64 -- only the comparison of |x| with 1 decides
      if (y < 0) {
        if (ax === 1) return one(sign);
        return ax > 1 ? pUnderflow(sign) : pOverflow(sign);
      }
      if (ax === 1) return one(sign);
      return ax > 1 ? pOverflow(sign) : pUnderflow(sign);
    }
    if (ay < Y_TINY) {
      // 0x7e8: |y| < 2^-65 -- the result is 1 +- the smallest step, never 1 exactly
      const lo = one(sign);
      const hi = phFrom(sign | 0x3be0000000000000n);
      if (y >= 0) {
        if (ax === 1) return one(sign);
        return ax > 1 ? lo + hi : lo - hi;
      }
      if (ax === 1) return one(sign);
      return ax > 1 ? lo - hi : lo + hi;
    }
    if (uxs >= P_2P52) return powFromBits(uxs, y, sign);
    // 0x6cc: a subnormal base is normalised by folding it into the exponent field
    const norm = phFrom(uxs | P_ONE) - 1;
    return powFromBits((phBits(norm) + POW_ZERO_BIAS) & M64, y, sign);
  };

  if (ayb === 0n) return one(xsign); // 0x64c: pow(x, +-0) == 1, even for NaN x
  if (ayb >= P_INF) {
    // 0x6e4: y is +-inf or NaN
    if (ayb > P_INF) return y + y; // NaN
    if (axb === 0n) return xZero(x);
    if (axb > P_INF) return x + x; // NaN
    const d = BigInt.asIntN(64, axb - P_ONE);
    if (d === 0n) return one(xsign);
    // `bic x0, x4, x0, asr #63`: +inf iff |x| - 1 and y have the same sign, else +0
    const sameSide = ((d ^ uy) >> 63n) & 1n;
    return phFrom(sameSide === 1n ? 0n : P_INF);
  }
  if (axb === 0n) return xZero(x); // 0x65c
  if (axb >= P_INF) {
    // 0x710: |x| is inf (or NaN)
    if (axb > P_INF) return x + x;
    return xZero(x);
  }
  if ((ux & P_SIGN) === 0n) return yRange(ux, xsign); // 0x668: x > 0
  // x < 0: only an integer y has a real result, and only an odd one keeps the sign
  if (ay < 1) return invalid(); // 0x66c
  {
    const clamp = phFrom(ayb < P_2P53 ? ayb : P_2P53); // 0x674..0x680
    if (Math.trunc(clamp) !== clamp) return invalid(); // 0x684..0x68c
    if ((BigInt(Math.trunc(clamp)) & 1n) === 1n) xsign = P_SIGN; // 0x694..0x698
  }
  return yRange(axb, xsign);
}

/**
 * `x ** y`, bit-identical to the oracle's libm `pow()`.
 *
 * Transcribed from the shipped machine code; the algorithm and the three traps are documented
 * in this file's header and in `src/model/rng/native/raw/apple_pow_impl.h`.
 *
 * Edge cases follow the C library: `pow(x, ±0)` and `pow(1, y)` are 1, `pow(±0, y<0)` is
 * ±Infinity (the sign from an odd integer y), `pow(-0, odd integer)` is -0, `pow(x<0, y)` is
 * NaN unless y is an integer, `pow(±Infinity, y<0)` is +0, and the overflow/underflow cases
 * return ±Infinity / ±0 with the odd-integer sign applied.
 */
export function pow(x: number, y: number): number {
  const ux = phBits(x);
  const uy = phBits(y);
  // the dispatch: both guards are unsigned 64-bit compares, so any negative y falls through
  if (BigInt.asUintN(64, ux - P_2P52) >= 0x7fe0000000000000n) return powSpecial(x, y);
  if (BigInt.asUintN(64, uy - 0x3be0000000000000n) > 0x0810000000000000n) return powSpecial(x, y);
  return powFromBits(ux, y, 0n);
}

/* ---------------------------------------------------------------- powf (see above) */

/** FRINTA + FCVTAS: round to nearest, ties away from zero.  `|t| <= 2^15` here, so the
 *  `+ 0.5` is exact and the truncation reproduces the machine's pair. */
function powfRintA(t: number): number {
  return t >= 0 ? Math.floor(t + 0.5) : Math.ceil(t - 0.5);
}

/**
 * 0x168..0x198, the negative-base exponent test: `|y|`, clamped to 2^24, is an integer?
 * Returns -1 when it is not (the machine's 0x244 NaN) and its parity otherwise — so anything
 * at or above 2^24 counts as even, which is a property of the shipped code, not of the model.
 */
function powfYParity(w1: number): number {
  const ay = w1 & 0x7fffffff;
  if (ay < 0x3f800000) return -1;
  const sc = f32From(Math.min(ay, 0x4b800000));       // csel w3, w3, w5, ls + fmov
  const n = Math.trunc(sc);                           // frintz + fcvtzs
  if (n !== sc) return -1;                            // fcmp s2, s1 / b.ne
  return n & 1;                                       // tbz/tbnz w5, #0
}

/** 0x1d0: `x` is `±0` or `±inf` (a NaN `x` is handled by the callers). */
function powfZero(w0: number, w1: number, w7: number): number {
  const sc = f32From(Math.min(w1 & 0x7fffffff, 0x4b800000));
  const n = Math.trunc(sc);
  const keep = n === sc && (n & 1) !== 0;             // an odd integer keeps x's sign
  let s0 = keep ? f32From(w0) : Math.abs(f32From(w0));  // 0x208: fabs
  if ((w1 & 0x80000000) !== 0) s0 = 1 / s0;           // 0x210/0x214: fdiv
  return Math.fround(s0);
}

/** 0x50..0x108: the 128-scaled log reduction, the exp assembly, one narrowing. */
function powfFast(w0: number, y: number, w7: number): number {
  const m = (w0 - POWF_LOG_BIAS) >>> 0;
  const idx = (m >>> 16) & 0x7f;
  const hi = m & 0xff800000;                          // the binade bits of `m`
  const w4 = (w0 - hi) >>> 0;
  const k = hi >> 16;                                 // `asr w2, w2, #16`, sign-extending
  const z = f32From(w4);                              // `fcvt d2, s2`
  const r = fma(z, POWF_LOG_INVC[idx]!, -1);          // `fnmsub`: Dn*Dm - Da
  const d7 = POWF_LOG_LOGC[idx]! + k;                 // `fadd d7, d7, scvtf(k)`
  const r2 = r * r;
  const d3 = fma(r, POWF_LOG_POLY[0]!, POWF_LOG_POLY[1]!);
  const d5 = fma(r, POWF_LOG_POLY[2]!, POWF_LOG_POLY[3]!);
  const l128 = fma(fma(d3, r2, d5), r, d7);           // == 128 * log2(base)
  let t = y * l128;                                   // `fmul d3, d1, d0`
  if (!(t <= POWF_T_CLAMP)) t = POWF_T_CLAMP;         // `fmin d3, d3, 2^15`
  if (!(t >= -POWF_T_CLAMP)) t = -POWF_T_CLAMP;       // `fmax d3, d3, -2^15`
  const nd = powfRintA(t);                            // `frinta` + `fcvtas`
  const n = BigInt(nd);
  const pat = (POWF_EXP_TAB[Number(n & 127n)]! + ((n << 45n) & M64)) & M64;
  const d3v = phFrom(pat);                            // `fmov d3, x1`
  const f = t - nd;
  const p = fma(POWF_EXP_POLY[0]!, f, POWF_EXP_POLY[1]!);
  const res = fma(p * f, d3v, d3v);                   // `d3 + r*poly*d3`
  return f32From((f32Bits(res) ^ w7) >>> 0);          // `fcvt s0, d0` then `eor.8b`
}

/**
 * `x ** y` for float32 operands, bit-identical to the oracle's libm `powf()`.
 *
 * Transcribed from the shipped machine code; the algorithm, the two tables and the three traps
 * are documented in this file's header and in `src/model/rng/native/raw/apple_powf_impl.h`.
 *
 * Edge cases follow the C library: `powf(1, y)` and `powf(±1, ±inf)` are `1.0f`,
 * `powf(x, ±0)` is `1.0f`, `powf(x, ±inf)` is `+inf`/`+0` by `|x|` (the mask path),
 * `powf(±0, y<0)` is `±inf` with the sign from an odd integer `y`, and `powf(x<0, y)` is NaN
 * unless `y` is an integer.
 */
export function powf(x: number, y: number): number {
  if (x === 1) return x;                              // 0x14 -> 0x22c (the `fmul` is skipped)
  if (y === 1) return Math.fround(x * 1);             // 0x1c -> 0x224: x * 1.0f
  let w0 = f32Bits(x);
  const w1 = f32Bits(y);
  let w7 = 0;
  const w2 = ((w1 & 0x7fffffff) - 1) >>> 0;
  if (w2 >= POWF_FLT_MAX_BITS) {
    // 0x10c: y is +-0, +-inf or NaN
    if ((w2 | 0) > 0x7f7fffff) return y;              // signed: NaN y -> return y
    if (w2 > 0x7f7fffff) return f32From(0x3f800000);  // +-0 / +-inf -> 1.0f
    const ax = w0 & 0x7fffffff;
    if (ax === 0) return powfZero(w0, w1, 0);
    if (ax > 0x7f800000) return Math.fround(x * 1);   // NaN x
    if (ax === 0x3f800000) return f32From(0x3f800000); // |x| == 1
    // y = +-inf, |x| neither 0 nor 1: |y| with the sign of ((|x| - 1) ^ y) inverted
    const mask = ((ax - 0x3f800000) ^ w1) >> 31;      // 0 or -1
    return f32From((f32Bits(Math.abs(y)) & ~mask) >>> 0);
  }
  if (((w0 - 0x800000) >>> 0) >= 0x7f000000) {
    // 0x150: x is not a positive normal
    const ax = w0 & 0x7fffffff;
    const w3 = (ax - 1) >>> 0;
    if (w3 >= POWF_FLT_MAX_BITS) {
      if ((w3 | 0) > 0x7f7fffff) return Math.fround(x * 1); // 0x1d0: NaN x
      return powfZero(w0, w1, w7);                          // +-0 / +-inf
    }
    if ((w0 & 0x80000000) !== 0) {
      // x < 0: only an integer y is real, and only an odd one keeps the sign
      const par = powfYParity(w1);
      if (par < 0) return f32From(0x7fc00000);        // 0x244: `inf - inf`
      if (par === 1) w7 = 0x80000000;
    }
    w0 = ax;                                          // 0x1a0: continue with |x|
    if (w0 >= 0x800000) return powfFast(w0, y, w7);
    // 0x1b4: normalise the positive subnormal (`orr.8b` with 1.0f, `fsub`, pattern minus
    // 0.5f's pattern) — all three steps are exact, so the fast path sees a fake binade
    const t = Math.fround(f32From((w0 | 0x3f800000) >>> 0) - 1);
    w0 = (f32Bits(t) - 0x3f000000) >>> 0;
    return powfFast(w0, y, w7);
  }
  return powfFast(w0, y, w7);
}

/* ---------------------------------------------------------------- atan2f (see above) */

/**
 * The oracle's `atan2f`'s polynomial in the reduced ratio `r` (`|r| <= 1`).
 *
 * Nine constants, four quadratics in `u = r*r`, two `fmla.2d`-fused steps per pair and a final
 * `fmul.2d` chain: `T8*(u^2+T0 u+T2)(u^2+T4 u+T6)*(u^2+T1 u+T3)(u^2+T5 u+T7)*r`.  The *grouping
 * and the order of the last three multiplies are load-bearing* (`(F0*F2)*T8` is rounded before
 * it meets `(F1*F3)*r`), and each `fma` is a hardware `fmla.2d`, so `T + (u + A)*u` is one
 * rounding.  `libm.ts`'s `fma` is the exact `a*b + c`, verified against the hardware.
 */
function atan2fPoly(r: number): number {
  const T = ATAN2F_POLY;
  const u = r * r;
  const f0 = fma(u + T[0]!, u, T[2]!); // `T2 + (u + T0)*u`
  const f1 = fma(u + T[1]!, u, T[3]!);
  const f2 = fma(u + T[4]!, u, T[6]!);
  const f3 = fma(u + T[5]!, u, T[7]!);
  return (f0 * f2 * T[8]!) * ((f1 * f3) * r);
}

/**
 * `atan2(y, x)` for float32 operands, bit-identical to the oracle's arm64 `atan2f`.
 *
 * Transcribed from the shipped machine code; the algorithm, the ladder and the three traps are
 * documented in this file's header and in `src/model/rng/native/raw/apple_atan2f_impl.h`.  The
 * constants come from `native/gen_atan2f_table.py`, which decodes the `adr`/`adrp`+`add`/
 * `ldr <label>` displacements that read them out of `raw/atan2f_bytes.bin`.
 *
 * The shape is a four-arm ladder on float comparisons of `y` against `x` and `-x` — the ratio is
 * always the *reduced* one, so `|r| <= 1` in every arm — plus the axis/quadrant boundaries,
 * which answer with a constant:
 *
 *   `-x < y < x`        : `P(y/x)`            (`x > 0`, `|y| < x`)
 *   `y < x <= -y`       : `-pi/2 - P(x/y)`    (and `-pi/4` when `-x === y`)
 *   `y >= x > -y`       : `pi/2 - P(x/y)`
 *   `y > x`, `y >= -x`  : `x <= 0`: `sign(y)*pi + P(y/x)`, or `+-ATAN2F_PI_HI` when
 *                         `|y/x| < 2^-22` (and `+3pi/4` when `-x === y`)
 *   `y === x`           : `pi/4`, `-3pi/4` for `y < 0`, and the origin's `+-0` / `+-pi`
 *   unordered (NaN)     : `y + x`
 *
 * Traps, all measured (see the header): the polynomial is only *float* accurate (0.36 ulp), so
 * this is **not** `f32(atan2)` (they differ by 1 ulp on ~15-20 % of arguments); the `x <= 0`
 * small-`|r|` arm answers `f32(pi)`-toward-zero-ish `+2^-32`, not `pi`, which is where arm64's
 * `atan2f(0, -1) == 0x40490fda` comes from; and the ladder's `b.pl`/`b.mi` are `N`-based, so
 * `!(a < b)` is taken for unordered too — the NaN answer is only reached through the
 * `y >= x` half, which is what the branch order below preserves.
 */
export function atan2f(y: number, x: number): number {
  y = Math.fround(y);
  x = Math.fround(x);
  const wy = f32Bits(y);

  if (!(y < x)) {
    // 0x11c: y >= x, or unordered (the ARM `b.pl` is N-based, so NaN lands here too)
    if (y === x) {
      // 0x20c: the y == x diagonal
      if (!(y >= 0)) return f32From(f32Bits(ATAN2F_NEG_3PI4));
      if (y !== 0) return f32From(f32Bits(ATAN2F_PI4));
      // y == x == 0: +-0, or +-pi when x is a negative zero
      if ((f32Bits(x) & 0x80000000) !== 0) return f32From(f32Bits(smallPi(wy)));
      return y; // `b 0xb0`: s0 is still the argument
    }
    if (y !== y || x !== x) return Math.fround(y + x); // 0x24c: NaN -> fadd s0, s0, s1
    if (!(-x < y)) {
      // 0x188: x <= 0 and y <= -x
      if (-x === y) return f32From(f32Bits(ATAN2F_3PI4)); // 0x204
      const r = y / x;
      if (Math.abs(r) < ATAN2F_SMALL) return f32From(f32Bits(smallPi(wy)));
      return f32From(
        f32Bits(atan2fPoly(r) + ((wy & 0x80000000) !== 0 ? ATAN2F_NEG_PI : ATAN2F_PI)),
      );
    }
    // 0xf0: -x < y, so |x| < y (and y > 0)
    return f32From(f32Bits(ATAN2F_HPI - atan2fPoly(x / y)));
  }

  if (!(-x < y)) {
    // 0xb8: y < x and y <= -x
    if (-x === y) return f32From(f32Bits(ATAN2F_NEG_PI4)); // 0x114
    return f32From(f32Bits(ATAN2F_NEG_HPI - atan2fPoly(x / y)));
  }
  // 0x20: y < x and -x < y
  return f32From(f32Bits(atan2fPoly(y / x)));
}

/** `|r| < 2^-22` in the `x <= 0` arm: `+-ATAN2F_PI_HI`, the sign taken from `y`'s bit pattern. */
function smallPi(wy: number): number {
  return (wy & 0x80000000) !== 0 ? -ATAN2F_PI_HI : ATAN2F_PI_HI;
}
