/**
 * Lane L8 — agent core tests.
 *
 * Three kinds of check, in decreasing strength:
 *
 *  1. **Differential vectors from the native build** (`src/model/agent/native/vectors/*.json`,
 *     regenerated by `src/model/agent/native/agentprobe.sh`). Every case is a real call into
 *     the C++ the goldens came from, with floats emitted as raw IEEE-754 bit patterns; the
 *     replay compares bits, so a 1-ulp divergence fails. This is the lane's byte-exact
 *     evidence — `agent::GetCollisionFixedCoordinates`, the whole `Energy` arithmetic surface
 *     used by eat/mate/carry, `agent::processWorldfile`, and the lifespan name tables.
 *  2. **Oracle-anchored invariants** read from the recorded goldens
 *     (`oracle/minitest_voff/run/**`): every agent's logged energy and position series
 *     bracket its `LifeSpan` exactly. Skipped when the goldens are not present (they are
 *     gitignored, so a fresh worktree may not have them) rather than silently passing.
 *  3. **Behavioural pins** on the ported step (`UpdateBody`) against a literal transcription
 *     of the native expression, over the *real* `minitest_voff` agent configuration (taken
 *     from the config vector), with the lane's seams supplied by local test doubles.
 */

import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { beforeEach, describe, expect, it } from 'vitest';

import { documentFromJs, globals, resetGlobals, type RngSurface, type SimEvent, BirthReason, DeathReason } from '../src/model/types';
import {
  Agent,
  AgentAttachedData,
  AgentStatics,
  BodyBlueChannel,
  BodyGreenChannel,
  BodyRedChannel,
  BodyRedChannel as BRC,
  Energy,
  EnergyMultiplier,
  EnergyPolarity,
  Metabolism,
  agentConfig,
  processWorldfile,
  resetAgentConfig,
  resetAgentStatics,
  energyAdd,
  energySub,
  type AgentDeps,
  type BarrierLike,
  type BarrierListLike,
  type BodyGeometryLike,
  type CarryableLike,
  type FoodLike,
  type GenomeLike,
  type NerveLike,
  type NervousSystemLike,
  type SensorLike,
  type SimulationLike,
  type SortedObjectListLike,
} from '../src/model/agent';
import { GObject } from '../src/model/agent/contracts';
import { DEGTORAD, f32 } from '../src/model/agent/numeric';
import { cos as libmCos, sin as libmSin } from '../src/model/rng/libm';
import { BIRTH_REASON_NAMES, DEATH_REASON_NAMES } from '../src/model/types';

const HERE = dirname(fileURLToPath(import.meta.url));
const WEB_ROOT = join(HERE, '..');
const VECTORS = join(WEB_ROOT, 'src', 'model', 'agent', 'native', 'vectors');
const ORACLE_RUN = join(WEB_ROOT, 'oracle', 'minitest_voff', 'run');

// ---------------------------------------------------------------------------
// float bit helpers — comparisons are on bits, never on `toBe`-ed numbers
// ---------------------------------------------------------------------------

const f32Buffer = new Float32Array(1);
const f32View = new DataView(f32Buffer.buffer);

function bitsOf(value: number): number {
  f32Buffer[0] = value;
  return f32View.getUint32(0, true);
}

function fromBits(bits: number): number {
  f32View.setUint32(0, bits, true);
  return f32Buffer[0]!;
}

interface CollisionVector {
  readonly kind: string;
  readonly cases: readonly { readonly in: readonly number[]; readonly out: readonly number[] }[];
}

interface EnergyVector {
  readonly kind: string;
  readonly cases: readonly {
    readonly n: number;
    readonly op: number;
    readonly a: readonly number[];
    readonly b: readonly number[];
    readonly m: readonly number[];
    readonly p: readonly number[];
    readonly out: readonly number[];
    readonly ov: readonly number[];
    readonly extra: number;
    readonly extra2: number;
    readonly flag: number;
  }[];
}

interface ConfigVector {
  readonly kind: string;
  readonly worldfile: string;
  readonly keys: Record<string, string>;
  readonly config: Record<string, number>;
  readonly longs: Record<string, number>;
  readonly bools: Record<string, boolean>;
  readonly enums: Record<string, number>;
}

interface LifespanVector {
  readonly kind: string;
  readonly birth: readonly string[];
  readonly death: readonly string[];
}

function loadVector<T>(name: string): T {
  return JSON.parse(readFileSync(join(VECTORS, name), 'utf8')) as T;
}

// ---------------------------------------------------------------------------
// 1. differential: agent::GetCollisionFixedCoordinates
// ---------------------------------------------------------------------------

describe('agent::GetCollisionFixedCoordinates — native differential vectors', () => {
  const vector = loadVector<CollisionVector>('collision.json');
  const deps = makeDeps();

  it('has a native-generated case set', () => {
    expect(vector.kind).toBe('agent.GetCollisionFixedCoordinates');
    expect(vector.cases.length).toBeGreaterThan(3000);
  });

  it('reproduces every native case bit-for-bit (3022/3022)', () => {
    // MEASURED 2026-09-28 against the native vectors: bit-exact on all 3022 cases — the 16
    // crafted branch/early-out cases, the 6 crafted *contraction* cases (t_4392393c) and the
    // 3000 random ones. The native trees are compiled with clang `-O2` and its default
    // `-ffp-contract=on`, so every `a*b + c` in the native source is one `fmadd`/`fmsub`
    // rounding rather than the multiply-then-add of the source text; `agent.ts` transcribes
    // the contraction the disassembled `agent::GetCollisionFixedCoordinates` (0x27504)
    // actually performs (`f32Fma` in `numeric.ts`, PORT-NOTE `L8/contraction`, PARITY.md ->
    // the float-contraction rule). Rounding per operation instead leaves 65 of the random
    // cases last-bit inexact (worst |delta| 5.455017e-4) and fails all 6 crafted contraction
    // cases — the tolerance this test used to carry. It is gone: any drift in any case, in
    // either coordinate, now fails here.
    const NATIVE_CASES = 3022;

    let exact = 0;
    const failures: string[] = [];
    for (const [index, testCase] of vector.cases.entries()) {
      const args = testCase.in.map(fromBits);
      const agent = new Agent(deps);
      const result = agent.getCollisionFixedCoordinates(
        args[0]!,
        args[1]!,
        args[2]!,
        args[3]!,
        args[4]!,
        args[5]!,
        args[6]!,
        args[7]!,
      );
      const wantX = fromBits(testCase.out[0]!);
      const wantZ = fromBits(testCase.out[1]!);
      if (bitsOf(result.xf) === testCase.out[0] && bitsOf(result.zf) === testCase.out[1]) {
        exact++;
        continue;
      }
      failures.push(
        `case ${index}: in=[${args.join(',')}] got (${result.xf}, ${result.zf}) ` +
          `want (${wantX}, ${wantZ})`,
      );
    }

    expect(vector.cases.length).toBe(NATIVE_CASES);
    expect(failures.slice(0, 5)).toEqual([]);
    expect(exact, `${exact}/${vector.cases.length} cases bit-exact`).toBe(NATIVE_CASES);
  });
});

// ---------------------------------------------------------------------------
// 2. differential: environment/Energy arithmetic
// ---------------------------------------------------------------------------

describe('Energy arithmetic — native differential vectors', () => {
  const vector = loadVector<EnergyVector>('energy.json');

  it('has a native-generated case set', () => {
    expect(vector.kind).toBe('environment.Energy');
    expect(vector.cases.length).toBeGreaterThan(500);
  });

  it('reproduces every op bit-for-bit', () => {
    const failures: string[] = [];
    for (const [index, testCase] of vector.cases.entries()) {
      const { n, op } = testCase;
      globals.numEnergyTypes = n;

      const a = Energy.fromNumbers(testCase.a.map(fromBits));
      const b = Energy.fromNumbers(testCase.b.map(fromBits));
      const m = EnergyMultiplier.fromNumbers(testCase.m.map(fromBits));
      const polarity = EnergyPolarity.fromNumbers(testCase.p);

      const out = new Energy(0);
      const ov = new Energy(0);
      let extra = 0;
      let extra2 = 0;
      let flag = 0;

      switch (op) {
        case 0: {
          const r = energyAdd(a, b);
          for (let i = 0; i < n; i++) out.set(i, r.get(i));
          break;
        }
        case 1: {
          const r = energySub(a, b);
          for (let i = 0; i < n; i++) out.set(i, r.get(i));
          break;
        }
        case 2: {
          const r = a.mulScalar(fromBits(testCase.b[0]!));
          for (let i = 0; i < n; i++) out.set(i, r.get(i));
          break;
        }
        case 3: {
          const r = a.mulPolarity(polarity);
          for (let i = 0; i < n; i++) out.set(i, r.get(i));
          break;
        }
        case 4: {
          const r = a.mulMultiplier(m);
          for (let i = 0; i < n; i++) out.set(i, r.get(i));
          break;
        }
        case 5: {
          // native: min is b[0] broadcast, max is the M array read as an Energy
          const e = a.clone();
          const overflow = e.constrainOverflow(
            new Energy(fromBits(testCase.b[0]!)),
            Energy.fromNumbers(testCase.m.map(fromBits)),
          );
          for (let i = 0; i < n; i++) {
            out.set(i, e.get(i));
            ov.set(i, overflow.get(i));
          }
          break;
        }
        case 6: {
          extra = a.sum();
          extra2 = a.mean();
          flag = (a.isZero() ? 1 : 0) | (a.isDepleted(b) ? 2 : 0);
          break;
        }
        case 7: {
          const r = Energy.createDepletionThreshold(a, polarity);
          for (let i = 0; i < n; i++) out.set(i, r.get(i));
          break;
        }
        case 8: {
          const r = Energy.fromPolarity(a, b, polarity);
          for (let i = 0; i < n; i++) out.set(i, r.get(i));
          break;
        }
        default: {
          const e = a.clone();
          e.addAssign(b);
          for (let i = 0; i < n; i++) out.set(i, e.get(i));
          break;
        }
      }

      const check = (name: string, actual: number, expected: number): void => {
        // NaN is an expected result (createDepletionThreshold's UNDEFINED polarity);
        // compare its bit pattern like any other value.
        if (bitsOf(actual) !== expected) {
          failures.push(`case ${index} (op ${op}, n ${n}) ${name}: got ${bitsOf(actual)} want ${expected}`);
        }
      };

      for (let i = 0; i < n; i++) {
        check(`out[${i}]`, out.get(i), testCase.out[i]!);
        check(`ov[${i}]`, ov.get(i), testCase.ov[i]!);
      }
      check('extra', extra, testCase.extra);
      check('extra2', extra2, testCase.extra2);
      if (flag !== testCase.flag) failures.push(`case ${index} flag: got ${flag} want ${testCase.flag}`);
    }

    expect(failures.slice(0, 5)).toEqual([]);
    expect(failures.length).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// 3. differential: agent::processWorldfile
// ---------------------------------------------------------------------------

describe('agent::processWorldfile — native config for the recorded worldfile', () => {
  const vector = loadVector<ConfigVector>('config.minitest_voff.json');

  beforeEach(() => {
    resetAgentConfig();
    resetAgentStatics();
  });

  it('reads every key through the same coercion the native build used', () => {
    expect(vector.kind).toBe('agent.processWorldfile');
    expect(vector.worldfile).toContain('minitest.wf');

    // The probe dumped the *evaluated* string of each key from the document the native run
    // configured from, so this replays native's own text, not a re-typed copy of it.
    processWorldfile(documentFromJs(vector.keys));

    const mismatches: string[] = [];
    for (const [name, bits] of Object.entries(vector.config)) {
      const actual = (agentConfig as unknown as Record<string, number>)[name] ?? Number.NaN;
      if (bitsOf(actual) !== bits) {
        mismatches.push(`config.${name}: got ${bitsOf(actual)} want ${bits}`);
      }
    }
    for (const [name, value] of Object.entries(vector.longs)) {
      const actual = (agentConfig as unknown as Record<string, number>)[name] ?? Number.NaN;
      if (actual !== value) mismatches.push(`config.${name}: got ${actual} want ${value}`);
    }
    for (const [name, value] of Object.entries(vector.bools)) {
      const actual = (agentConfig as unknown as Record<string, boolean>)[name];
      if (actual !== value) mismatches.push(`config.${name}: got ${actual} want ${value}`);
    }
    for (const [name, value] of Object.entries(vector.enums)) {
      const actual = (agentConfig as unknown as Record<string, number>)[name];
      if (actual !== value) mismatches.push(`config.${name}: got ${actual} want ${value}`);
    }

    expect(mismatches).toEqual([]);
  });

  it('derives hasLightBehavior from the channel selections, as native does', () => {
    processWorldfile(documentFromJs(vector.keys));
    expect(agentConfig.bodyGreenChannel).toBe(BodyGreenChannel.BGC_ID);
    expect(agentConfig.noseColor).toBe(0); // NC_LIGHT
    expect(agentConfig.hasLightBehavior).toBe(true);
    expect(agentConfig.bodyRedChannel).toBe(BodyRedChannel.BRC_FIGHT);
    expect(agentConfig.bodyBlueChannel).toBe(BodyBlueChannel.BBC_MATE);
    expect(agentConfig.dieAtMaxAge).toBe(true);
  });

  it('reads a constant body channel as a float when it is not a keyword', () => {
    const keys = { ...vector.keys, BodyRedChannel: '0.25', NoseColor: '0.75' };
    processWorldfile(documentFromJs(keys));
    expect(agentConfig.bodyRedChannel).toBe(BRC.BRC_CONST);
    expect(agentConfig.bodyRedChannelConstValue).toBe(f32(0.25));
    expect(agentConfig.noseColor).toBe(2); // NC_CONST
    expect(agentConfig.noseColorConstValue).toBe(f32(0.75));
    // bodyGreenChannel is still 'I' (BGC_ID) and the nose is now a constant, so neither
    // light-behaviour trigger fires.
    expect(agentConfig.bodyGreenChannel).toBe(BodyGreenChannel.BGC_ID);
    expect(agentConfig.hasLightBehavior).toBe(false);
  });

  it('rejects an unknown YawEncoding instead of guessing (native asserts)', () => {
    const keys = { ...vector.keys, YawEncoding: 'Sideways' };
    expect(() => processWorldfile(documentFromJs(keys))).toThrow(/YawEncoding/);
  });
});

// ---------------------------------------------------------------------------
// 4. differential: the lifespan name tables
// ---------------------------------------------------------------------------

describe('LifeSpan name tables — native differential vector', () => {
  const vector = loadVector<LifespanVector>('lifespan.json');

  it('reproduces BR_NAMES / DR_NAMES exactly', () => {
    expect(vector.kind).toBe('agent.LifeSpan');
    expect([...BIRTH_REASON_NAMES]).toEqual([...vector.birth]);
    expect([...DEATH_REASON_NAMES]).toEqual([...vector.death]);
    expect(DEATH_REASON_NAMES[DeathReason.FIGHT]).toBe('FIGHT');
  });
});

// ---------------------------------------------------------------------------
// 5. oracle-anchored invariants (skipped without the goldens)
// ---------------------------------------------------------------------------

const hasGoldens = existsSync(join(ORACLE_RUN, 'lifespans.txt'));
const golden = hasGoldens ? describe : describe.skip;

golden('minitest_voff goldens — per-agent logs bracket the LifeSpan exactly', () => {
  const lifespans = readLifespans();
  const agents = [...lifespans.keys()].sort((a, b) => a - b);

  it('records 87 agents with a SIMINIT or NATURAL birth', () => {
    expect(agents.length).toBe(87);
    for (const [, entry] of lifespans) {
      expect(['SIMINIT', 'NATURAL']).toContain(entry.birthReason);
    }
  });

  it('starts each energy series at the birth step (the step after, for SIMINIT at step 0)', () => {
    for (const number of agents) {
      const entry = lifespans.get(number)!;
      const steps = logSteps(join(ORACLE_RUN, 'energy', 'agents', `agent_${number}.txt`));
      expect(steps.length).toBeGreaterThan(0);
      expect(steps[0]).toBe(entry.birthStep === 0 ? 1 : entry.birthStep);
      expect(steps[steps.length - 1]).toBe(entry.deathStep);
      expect(isContiguous(steps)).toBe(true);
      expect(steps.length).toBe(entry.deathStep - steps[0]! + 1);    }
  });

  it('starts each position series on the step after birth and ends it at death', () => {
    for (const number of agents) {
      const entry = lifespans.get(number)!;
      const steps = logSteps(join(ORACLE_RUN, 'motion', 'position', 'agents', `position_${number}.txt`));
      expect(steps.length).toBeGreaterThan(0);
      expect(steps[0]).toBe(entry.birthStep + 1);
      expect(steps[steps.length - 1]).toBe(entry.deathStep);
      expect(isContiguous(steps)).toBe(true);
    }
  });

  it('ends every agent at or before the final step, with SIMEND only for survivors', () => {
    const finalStep = Math.max(...[...lifespans.values()].map((entry) => entry.deathStep));
    for (const [, entry] of lifespans) {
      expect(entry.deathStep).toBeLessThanOrEqual(finalStep);
      if (entry.deathReason === 'SIMEND') expect(entry.deathStep).toBe(finalStep);
    }
  });
});

// ---------------------------------------------------------------------------
// 6. behaviour pins on the ported step, over the real worldfile's config
// ---------------------------------------------------------------------------

describe('Agent — the ported step (UpdateBody) and lifecycle', () => {
  const configVector = loadVector<ConfigVector>('config.minitest_voff.json');

  beforeEach(() => {
    resetGlobals();
    resetAgentConfig();
    resetAgentStatics();
    // Use the *recorded* worldfile's agent configuration (dumped by the native probe), so
    // these pins exercise the values the goldens were produced with.
    processWorldfile(documentFromJs(configVector.keys));
    globals.worldsize = 100;
    globals.numEnergyTypes = 1; // the recorded world's NumEnergyTypes
  });

  it('moves and drains energy by the native formula', () => {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.setGenomeReady();

    const nerves = deps.testNerves!;
    nerves.set('Eat', 0.25);
    nerves.set('Mate', 0);
    nerves.set('Fight', 0);
    nerves.set('Speed', 0.5);
    nerves.set('Yaw', 0.75); // YE_OPPOSE: yaw - yawOppose
    nerves.set('YawOppose', 0.25);
    nerves.set('Focus', 0);

    const before = agent.energy().clone();
    const maxEnergy = agent.maxEnergy().get(0);
    const genes = deps.testGenes!;
    const ageBefore = agent.age();
    const positionBefore: [number, number, number] = [agent.x(), agent.y(), agent.z()];

    const energyUsed = agent.updateBody(1.0, agentConfig.speed2DPosition, 0, null);

    // --- the native expression, written out independently -------------------
    const dposRaw = f32(f32(0.5 * genes.maxSpeed) * agentConfig.speed2DPosition);
    const dpos = dposRaw > agentConfig.maxVelocity ? agentConfig.maxVelocity : dposRaw;
    const dyaw = f32(0.75 - 0.25);
    const expectedDyaw = f32(f32(dyaw * genes.maxSpeed) * agentConfig.yaw2DYaw);

    let energyused = f32(0.25 * agentConfig.eat2Energy);
    energyused = f32(energyused + f32(0 * agentConfig.mate2Energy));
    energyused = f32(energyused + f32(0 * agentConfig.fight2Energy));
    energyused = f32(energyused + f32(0.5 * agent.speed2Energy()));
    energyused = f32(energyused + f32(Math.abs(dyaw) * agent.yaw2Energy()));
    energyused = f32(energyused + 0); // fCns->getEnergyUse()
    energyused = f32(energyused + agentConfig.fixedEnergyDrain);
    energyused = f32(energyused + f32(0 * agentConfig.light2Energy)); // hasLightBehavior
    let expectedDenergy = f32(energyused * genes.strength * f32(1.0 + f32(agentConfig.ageEnergyMultiplier * ageBefore)));
    expectedDenergy = f32(expectedDenergy + f32(0 * maxEnergy)); // no population penalty
    expectedDenergy = f32(expectedDenergy * 1.0 * 1.0); // scale factors
    expectedDenergy = f32(expectedDenergy * agentConfig.energyUseMultiplier);

    expect(bitsOf(energyUsed)).toBe(bitsOf(expectedDenergy));
    expect(bitsOf(agent.energy().get(0))).toBe(bitsOf(f32(before.get(0) - expectedDenergy)));
    expect(bitsOf(agent.foodEnergy().get(0))).toBe(bitsOf(f32(before.get(0) - expectedDenergy)));

    // motion: `dx = -dpos * sin( yaw * DEGTORAD )` with yaw 0 -> 0; dz -> -dpos
    expect(agent.x()).toBe(positionBefore[0]);
    expect(bitsOf(agent.z())).toBe(bitsOf(f32(positionBefore[2] - dpos)));
    // steering: yaw was 0, so it is now the expected dyaw
    expect(bitsOf(agent.yaw())).toBe(bitsOf(expectedDyaw));
    // the step ages the agent and records its speed
    expect(agent.age()).toBe(ageBefore + 1);
    expect(bitsOf(agent.velocityZ())).toBe(bitsOf(f32(agent.z() - positionBefore[2])));

    // events: exactly one AgentBodyUpdatedEvent, carrying (denergy, energyused)
    const bodyEvents = deps.testEvents!.events.filter((event) => event.type === 32);
    expect(bodyEvents.length).toBe(1);
    expect((bodyEvents[0] as { energyUsed: number }).energyUsed).toBe(energyUsed);
  });

  it('does not move or turn when nothing is driven (yaw 0, speed 0)', () => {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.setGenomeReady();
    const nerves = deps.testNerves!;
    nerves.set('Eat', 0);
    nerves.set('Mate', 0);
    nerves.set('Fight', 0);
    nerves.set('Speed', 0);
    nerves.set('Yaw', 0.5); // squash encoding off: oppose -> dyaw = 0.5 - 0.5 = 0
    nerves.set('YawOppose', 0.5);
    nerves.set('Focus', 0);

    const x = agent.x();
    const z = agent.z();
    const yawBefore = agent.yaw();
    agent.updateBody(1.0, agentConfig.speed2DPosition, 0, null);
    expect(agent.x()).toBe(x);
    expect(agent.z()).toBe(z);
    expect(bitsOf(agent.yaw())).toBe(
      bitsOf(f32(yawBefore + f32(f32(0 * deps.testGenes!.maxSpeed) * agentConfig.yaw2DYaw))),
    );
  });

  it('wraps around the world when the world wraps and dies inside blocked edges', () => {
    const deps = makeDeps();
    globals.wraparound = true;
    globals.worldsize = 100;
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.setGenomeReady();
    const nerves = deps.testNerves!;
    nerves.set('Eat', 0);
    nerves.set('Mate', 0);
    nerves.set('Fight', 0);
    nerves.set('Speed', 1);
    nerves.set('Yaw', 0.5);
    nerves.set('YawOppose', 0.5);
    nerves.set('Focus', 0);

    agent.setZ(-0.01);
    agent.setYaw(0); // heading -z, i.e. toward -worldsize
    agent.saveLastPosition();
    agent.updateBody(1.0, agentConfig.speed2DPosition, 0, null);
    // z went below -worldsize and was wrapped back into [-worldsize, 0]
    expect(agent.z()).toBeGreaterThanOrEqual(-globals.worldsize);
    expect(agent.z()).toBeLessThan(0);
  });

  it('carries and drops objects, tracking the carry radius', () => {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.setGenomeReady();

    const object = makeCarryable(GObject.FOODTYPE, 3, 6.5);
    agent.pickupObject(object);
    expect(agent.numCarries()).toBe(1);
    expect(agent.carryRadius()).toBe(Math.max(agent.radius(), object.radius()));
    expect(object.carriedBy()).toBe(agent);
    expect(bitsOf(agent.carryEnergy())).toBe(
      bitsOf(f32(f32(deps.foodStatics.carryFood2Energy() * object.radius()) / deps.foodStatics.maxFoodRadius())),
    );

    agent.dropMostRecent();
    expect(agent.numCarries()).toBe(0);
    expect(object.carriedBy()).toBeNull();
    expect(bitsOf(agent.carryRadius())).toBe(bitsOf(agent.radius()));
  });

  it('counts lives and notifies listeners on Die()', () => {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.setGenomeReady();
    expect(AgentStatics.agentsLiving).toBe(1);
    expect(agent.number()).toBe(1);

    const died: unknown[] = [];
    agent.addListener({ died: (a) => died.push(a) });
    agent.die();
    expect(died).toEqual([agent]);
    expect(agent.alive()).toBe(false);
    expect(AgentStatics.agentsLiving).toBe(0);
  });

  it('stamps the lifespan record the way lifespans.txt is written', () => {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.setGenomeReady();
    agent.stampBirth(0, 1); // BR_SIMINIT
    agent.lifeSpan().setDeath(218, DeathReason.FIGHT);
    expect(agent.lifeSpan().birthReasonName()).toBe('SIMINIT');
    expect(agent.lifeSpan().deathReasonName()).toBe('FIGHT');
    expect(agent.lifeSpan().birth.step).toBe(0);
    expect(agent.lifeSpan().death.step).toBe(218);
  });

  it('gives an agent its gene budget (max energy, starvation threshold, cost scaling)', () => {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    const sizeRel = f32(deps.testGenes!.size - agentConfig.minAgentSize);
    const expectedMaxEnergy = f32(
      agentConfig.minMaxEnergy +
        f32(f32(sizeRel * f32(agentConfig.maxMaxEnergy - agentConfig.minMaxEnergy)) / f32(agentConfig.maxAgentSize - agentConfig.minAgentSize)),
    );
    expect(bitsOf(agent.maxEnergy().get(0))).toBe(bitsOf(expectedMaxEnergy));
    expect(bitsOf(agent.starvationFoodEnergy().get(0))).toBe(
      bitsOf(f32(agentConfig.starvationEnergyFraction * expectedMaxEnergy)),
    );
    expect(bitsOf(agent.speed2Energy())).toBe(
      bitsOf(
        f32(
          f32(f32(f32(agentConfig.speed2Energy * deps.testGenes!.maxSpeed) * f32(agentConfig.minSizePenalty + sizeRel)) * agentConfig.maxSizePenalty) /
            // Native `agent.cc:741`: `( minSizePenalty + maxAgentSize - minAgentSize )`,
            // left to right — NOT `minSizePenalty + ( maxAgentSize - minAgentSize )`.
            f32(f32(agentConfig.minSizePenalty + agentConfig.maxAgentSize) - agentConfig.minAgentSize),
        ),
      ),
    );
    expect(bitsOf(agent.normalizedEnergy())).toBe(bitsOf(f32(1.0)));
  });

  it('reads a seed’s energy budget and mate wait from the seeding path', () => {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(25, true);
    expect(agent.isSeed()).toBe(true);
    // randomSeedMateWait is false in this world, so `fLastMate = -mateWait` exactly.
    expect(agent.lastMate()).toBe(-25);
    // randomSeedEnergy false -> maxSeedEnergy * maxEnergy
    expect(bitsOf(agent.energy().get(0))).toBe(
      bitsOf(f32(agentConfig.maxSeedEnergy * agent.maxEnergy().get(0))),
    );
  });
});

// ---------------------------------------------------------------------------
// round-1 review pins — the native constants and the per-operand float narrowing
// ---------------------------------------------------------------------------

describe('L8 — native constants and float narrowing (round-1 review fixes)', () => {
  const configVector = loadVector<ConfigVector>('config.minitest_voff.json');

  beforeEach(() => {
    resetGlobals();
    resetAgentConfig();
    resetAgentStatics();
    processWorldfile(documentFromJs(configVector.keys));
    globals.worldsize = 100;
    globals.numEnergyTypes = 1;
  });

  it('hands native’s list directions (NEXT 1 / PREV 2) to anotherObj', () => {
    // Native `utils/objectxsortedlist.h:4-5` is `#define NEXT 1` / `#define PREV 2`, and
    // `objectxsortedlist::anotherObj` (objectxsortedlist.cc:129-139) prints
    // "ERROR--Unknown direction" and `exit(1)`s for anything else. The pre-fix port declared
    // PREV as 0 and passed that to the seam, where the native walk aborts.
    expect(GObject.NEXT).toBe(1);
    expect(GObject.PREV).toBe(2);

    const deps = makeDeps();
    const directions: number[] = [];
    const marks: number[] = [];
    const list: SortedObjectListLike = {
      setMark: (type: number) => marks.push(type),
      toMark: (type: number) => marks.push(type),
      anotherObj: (direction: number) => {
        directions.push(direction);
        return null;
      },
    };
    // `AgentDeps.sortedObjects` is readonly in the frozen contract; the seam is swapped for
    // this pin only (the agent reads `this.deps.sortedObjects` at call time).
    (deps as unknown as { sortedObjects: SortedObjectListLike }).sortedObjects = list;
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.avoidCollisions(GObject.AGENTTYPE);
    expect(directions).toEqual([GObject.PREV, GObject.NEXT]);
    expect(marks).toEqual([GObject.AGENTTYPE, GObject.AGENTTYPE, GObject.AGENTTYPE]);
  });

  it('truncates a randomly seeded mate wait toward zero (native C cast, not nint)', () => {
    const deps = makeDeps();
    agentConfig.randomSeedMateWait = true;
    deps.rng.drand48 = () => 0.44;
    const agent = Agent.getFreeAgent(deps);
    agent.grow(40, true);
    // Native `agent.cc:680` is `fLastMate = (long)( randpw() * -mateWait );` — truncation of
    // the double product. `nint` (the `misc.h:36` macro used for the Metabolism index) rounds
    // negatives away from zero, so the pre-fix port stored -18 for this seed.
    expect(Math.trunc(0.44 * -40)).toBe(-17);
    expect(agent.lastMate()).toBe(-17);
  });

  it('computes fSpeed from narrowed squares, as agent.cc:1435 does', () => {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.setGenomeReady();
    const carrier = Agent.getFreeAgent(deps);
    carrier.grow(0, false);

    // Chosen so the native per-operand form and the single-rounding form differ (they do for
    // ~23% of random float32 pairs). A carried agent is snapped to its carrier by `PickedUp`,
    // so the step's `dx`/`dz` are the carrier's displacement between pickup and the update —
    // here exactly `u` and `v`.
    const u = 0.6874257922172546;
    const v = 0.9004657864570618;
    carrier.setX(0);
    carrier.setZ(0);
    agent.setX(5);
    agent.setZ(5);
    carrier.pickupObject(agent);
    expect(agent.beingCarried()).toBe(true);
    expect(agent.x()).toBe(carrier.x()); // `gobject::PickedUp` snaps the carried object
    carrier.setX(u);
    carrier.setZ(v);

    agent.updateBody(1.0, agentConfig.speed2DPosition, 0, carrier);
    expect(bitsOf(agent.velocityX())).toBe(bitsOf(u));
    expect(bitsOf(agent.velocityZ())).toBe(bitsOf(v));

    const perOperand = f32(Math.sqrt(f32(f32(u * u) + f32(v * v))));
    const singleRounding = f32(Math.sqrt(u * u + v * v));
    expect(bitsOf(perOperand)).not.toBe(bitsOf(singleRounding));
    expect(bitsOf(agent.speed())).toBe(bitsOf(perOperand));
  });

  it('associates the size-penalty denominator left to right, as agent.cc:741 does', () => {
    const deps = makeDeps();
    // Values chosen (by search) so the two associations give different floats.
    agentConfig.minSizePenalty = 4.182470798492432;
    agentConfig.minAgentSize = 1.2145298719406128;
    agentConfig.maxAgentSize = 3.1678273677825928;
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);

    const sizeRel = f32(deps.testGenes!.size - agentConfig.minAgentSize);
    const nativeDenominator = f32(
      f32(agentConfig.minSizePenalty + agentConfig.maxAgentSize) - agentConfig.minAgentSize,
    );
    const reassociated = f32(
      agentConfig.minSizePenalty + f32(agentConfig.maxAgentSize - agentConfig.minAgentSize),
    );
    expect(bitsOf(nativeDenominator)).not.toBe(bitsOf(reassociated));

    const expected = f32(
      f32(
        f32(
          f32(agentConfig.speed2Energy * deps.testGenes!.maxSpeed) *
            f32(agentConfig.minSizePenalty + sizeRel),
        ) * agentConfig.maxSizePenalty,
      ) / nativeDenominator,
    );
    expect(bitsOf(agent.speed2Energy())).toBe(bitsOf(expected));
  });

  it('narrows the collision distance² terms, so the approaching test matches native', () => {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.setGenomeReady();

    // Geometry found by search over float32 inputs: here the native per-operand form says
    // "approaching" and the pre-fix single-rounding (double) form says "not approaching", so
    // the fix changes a collision decision — not just the last bits. The x/z range tests
    // below are re-checked explicitly, so the test cannot pass by the object simply being
    // outside the window.
    const lx = -29.02815055847168;
    const lz = 3.796597719192505;
    const x = -27.680822372436523;
    const z = 4.139699935913086;
    const ox = -28.375471115112305;
    const oz = 1.2617377042770386;
    const objectRadiusValue = 2.1406784057617188;

    agent.setX(lx);
    agent.setZ(lz);
    agent.saveLastPosition();
    agent.setX(x);
    agent.setZ(z);

    const object = makeCarryable(GObject.AGENTTYPE, 2, objectRadiusValue);
    object.setx(ox);
    object.setz(oz);
    let served = false;
    const collisionList: SortedObjectListLike = {
      setMark: () => {},
      toMark: () => {},
      anotherObj: () => {
        if (served) return null;
        served = true;
        return { obj: object };
      },
    };
    (deps as unknown as { sortedObjects: SortedObjectListLike }).sortedObjects = collisionList;

    // The x/z range tests the port runs before the distance test — asserted here so the pin
    // is known to exercise the decision, not the early-out.
    const agtRadius = f32(agent.radius() * 0.9);
    const objRadius = f32(objectRadiusValue * 0.9);
    expect(f32(ox - objRadius) > f32(Math.max(x, lx) + agtRadius)).toBe(false);
    expect(f32(ox + objRadius) < f32(Math.min(x, lx) - agtRadius)).toBe(false);
    expect(f32(oz - objRadius) > f32(Math.max(z, lz) + agtRadius)).toBe(false);
    expect(f32(oz + objRadius) < f32(Math.min(z, lz) - agtRadius)).toBe(false);

    // The step the port takes toward the object (`Math.abs(dx) > Math.abs(dz)` branch, both
    // forms narrow these the same way).
    const dx = f32(x - lx);
    const dz = f32(z - lz);
    expect(Math.abs(dx) > Math.abs(dz)).toBe(true);
    const s = f32(dz / dx);
    const xs = f32(lx + f32(dx / globals.worldsize));
    const zs = f32(lz + f32(s * f32(xs - lx)));

    const narrowed = (a: number, b: number): number => f32(f32(a * a) + f32(b * b));
    const nativeDo = narrowed(f32(ox - lx), f32(oz - lz));
    const nativeDs = narrowed(f32(ox - xs), f32(oz - zs));
    const doubleDo = (ox - lx) ** 2 + (oz - lz) ** 2;
    const doubleDs = (ox - xs) ** 2 + (oz - zs) ** 2;
    expect(nativeDs < nativeDo).toBe(true);
    expect(doubleDs < doubleDo).toBe(false);

    agent.avoidCollisionDirectional(GObject.NEXT, GObject.AGENTTYPE);

    // the port took the native branch: repositioned onto the fixed coordinates + one event
    const expected = agent.getCollisionFixedCoordinates(lx, lz, x, z, ox, oz, agtRadius, objRadius);
    expect(bitsOf(agent.x())).toBe(bitsOf(expected.xf));
    expect(bitsOf(agent.z())).toBe(bitsOf(expected.zf));
    const collisions = deps.testEvents!.events.filter((event) => event.type === 256);
    expect(collisions.length).toBe(1);
    expect((collisions[0] as unknown as { ot: number }).ot).toBe(0); // OT_AGENT
  });
});

// ---------------------------------------------------------------------------
// helpers: test doubles for the lane's seams
// ---------------------------------------------------------------------------

interface TestNerves {
  set(name: string, value: number): void;
  created: string[];
}

interface TestGenes extends GenomeLike {
  maxSpeed: number;
  strength: number;
  size: number;
  lifespan: number;
}

interface TestDeps extends AgentDeps {
  testNerves?: TestNerves;
  testGenes?: TestGenes;
  testEvents?: { events: SimEvent<unknown, unknown, Energy>[] };
}

function makeGenes(): TestGenes {
  return {
    maxSpeed: 1.0,
    strength: 1.0,
    size: 1.25,
    lifespan: 750,
    get(name: string): number {
      switch (name) {
        case 'MaxSpeed':
          return this.maxSpeed;
        case 'Strength':
          return this.strength;
        case 'Size':
          return this.size;
        case 'MateEnergyFraction':
          return 0.5;
        case 'ID':
          return 0.375;
        default:
          return 0;
      }
    },
    getLong(name: string): number {
      return name === 'LifeSpan' ? this.lifespan : 0;
    },
    mateProbability(): number {
      return 1.0;
    },
  };
}

function makeNerves(): { nervousSystem: NervousSystemLike; nerves: TestNerves } {
  const table = new Map<string, NerveLike>();
  const created: string[] = [];
  const nerves: TestNerves = {
    created,
    set(name: string, value: number): void {
      const nerve = table.get(name);
      if (nerve === undefined) throw new Error(`no nerve ${name}`);
      nerve.set(f32(value));
    },
  };
  const nervousSystem: NervousSystemLike = {
    createNerve(_kind, name) {
      const state = { value: 0 };
      const nerve: NerveLike = {
        get: () => state.value,
        set: (v: number) => {
          state.value = v;
        },
      };
      table.set(name, nerve);
      created.push(name);
      return nerve;
    },
    getNerve(name) {
      const nerve = table.get(name);
      if (nerve === undefined) throw new Error(`getNerve(${name}) before createNerve`);
      return nerve;
    },
    addSensor(_sensor: SensorLike) {},
    grow() {},
    prebirth() {},
    update() {},
    getEnergyUse() { return 0; },
    getRNG() { return { drand: () => 0.5, seedIfLocal() {} }; },
    getBrain() { return { freeze() {} }; },
  };
  return { nervousSystem, nerves };
}

function makeGeometry(): BodyGeometryLike {
  const scaled: { lengthX: number; height: number; lengthZ: number } = { lengthX: 0, height: 0, lengthZ: 0 };
  return {
    cloneGeometry() {},
    scaleVertices(lengthX, height, lengthZ) {
      scaled.lengthX = lengthX;
      scaled.height = height;
      scaled.lengthZ = lengthZ;
    },
    // Native `setlen()` takes the bounding box of the scaled mesh; the test box is exactly
    // the scaled extents, so the radius check below is the native formula over them.
    lengths() {
      return [scaled.lengthX, scaled.height, scaled.lengthZ] as const;
    },
    radiusScale() { return 1; },
    scale() { return 1; },
    radiusFixed() { return false; },
  };
}

function makeCarryable(type: number, typeNumber: number, radius: number): CarryableLike & {
  carriedBy(): CarryableLike | null;
} {
  let carried: CarryableLike | null = null;
  const object = {
    xValue: 0,
    zValue: 0,
    getType: () => type,
    getTypeNumber: () => typeNumber,
    x: () => object.xValue,
    z: () => object.zValue,
    setx: (x: number) => { object.xValue = x; },
    setz: (z: number) => { object.zValue = z; },
    radius: () => radius,
    pickedUp: (by: CarryableLike) => { carried = by; },
    dropped: () => { carried = null; },
    carriedBy: () => carried,
    numCarries: () => 0,
  };
  return object as CarryableLike & { carriedBy(): CarryableLike | null };
}

function makeDeps(): TestDeps {
  const { nervousSystem, nerves } = makeNerves();
  const events: SimEvent<unknown, unknown, Energy>[] = [];
  const genes = makeGenes();
  const simulation: SimulationLike = {
    fStep: 1,
    fLowPopulationAdvantageFactor: 1.0,
    fGlobalEnergyScaleFactor: 1.0,
    fPopulationPenaltyFraction: 0.0,
    fDomains: [{ energyScaleFactor: 1.0 }],
    whichDomain: (_x, _z, current) => current,
    switchDomain: () => {},
    agentPovRenderer: () => ({ add() {}, remove() {}, render() {} }),
    lifeFractionSamples: () => 0,
    lifeFractionRecent: () => 0,
    energyFitnessParameter: () => 0,
    ageFitnessParameter: () => 0,
  };
  const barrierList: BarrierListLike = {
    reset: () => {},
    next: () => null,
    stickyBarriers: () => false,
  };
  const sortedObjects: SortedObjectListLike = {
    setMark: () => {},
    toMark: () => {},
    anotherObj: () => null,
  };
  const rng: RngSurface = {
    srand: () => {},
    rand: () => 0,
    srand48: () => {},
    drand48: () => 0.5,
    lrand48: () => 0,
    nrand: () => 0,
    nrandScaled: () => 0,
  };
  Metabolism.clearDefinitions();
  const metabolism = Metabolism.define(
    'Null',
    EnergyPolarity.fromNumbers(new Array<number>(globals.numEnergyTypes).fill(1)),
    EnergyMultiplier.fromNumbers(new Array<number>(globals.numEnergyTypes).fill(1)),
    new Energy(0),
    0,
    null,
  );
  return {
    simulation,
    genomeFactory: {
      createGenome: () => genes,
      getMetabolism: () => metabolism,
    },
    geometry: makeGeometry(),
    bodyTemplate: {},
    stage: {},
    rng,
    events: { postEvent: (event) => events.push(event) },
    barrierList,
    sortedObjects,
    foodStatics: { carryFood2Energy: () => 0.5, maxFoodRadius: () => 10 },
    brickStatics: { carryBrick2Energy: () => 5, numBricks: () => 0 },
    nervousSystemFactory: { create: () => nervousSystem },
    retinaFactory: { create: (width) => ({ sensorName: `Retina(${width})` }) },
    retinaWidth: 2,
    retinaHeight: 2,
    preBirthLearning: false,
    visionCamera: null,
    testNerves: nerves,
    testGenes: genes,
    testEvents: { events },
  };
}

// ---------------------------------------------------------------------------
// helpers: golden readers
// ---------------------------------------------------------------------------

interface LifespanEntry {
  birthStep: number;
  deathStep: number;
  birthReason: string;
  deathReason: string;
}

function readLifespans(): Map<number, LifespanEntry> {
  const entries = new Map<number, LifespanEntry>();
  const text = readFileSync(join(ORACLE_RUN, 'lifespans.txt'), 'latin1');
  for (const line of text.split('\n')) {
    if (line.length === 0 || line.startsWith('#')) continue;
    const parts = line.split('\t');
    if (parts.length !== 5) continue;
    entries.set(Number(parts[0]), {
      birthStep: Number(parts[1]),
      deathStep: Number(parts[3]),
      birthReason: parts[2]!,
      deathReason: parts[4]!,
    });
  }
  return entries;
}

function logSteps(path: string): number[] {
  const steps: number[] = [];
  const text = readFileSync(path, 'latin1');
  for (const line of text.split('\n')) {
    if (line.length === 0 || line.startsWith('#')) continue;
    // datalib `#colformat=fixed` rows are space-padded (single/table schemas both).
    const first = line.trim().split(/\s+/)[0];
    if (first === undefined || first.length === 0) continue;
    const step = Number(first);
    if (!Number.isNaN(step)) steps.push(step);
  }
  return steps;
}

function isContiguous(steps: readonly number[]): boolean {
  for (let i = 1; i < steps.length; i++) {
    if (steps[i] !== steps[i - 1]! + 1) return false;
  }
  return true;
}

// `AgentAttachedData` is exercised through `Agent`'s constructor; keep the import honest.
void AgentAttachedData;

// ---------------------------------------------------------------------------
// 5. agent::setradius() — the shipped contraction (t_981fcace)
// ---------------------------------------------------------------------------

/**
 * `agent::setradius()` as the shipped `__ZN5agent9setradiusEv` computes it:
 *
 *   21f3c:  ldr    s0, [x0, #0x98]      ; fLength[0]
 *   21f40:  ldp    s1, s2, [x0, #0xa0]  ; s1 = fLength[2], s2 = fRadiusScale
 *   21f44:  fmul   s1, s1, s1           ; f32( fLength[2]^2 ) — the ONLY rounded square
 *   21f48:  fmadd  s0, s0, s0, s1       ; fLength[0]^2 + that, ONE rounding
 *   21f4c:  fsqrt  s0, s0               ; the `float` overload
 *   21f50/21f58: fmul × fRadiusScale, × fScale   ; 21f60: fmul × 0.5f
 *
 * i.e. `f32(lx*lx + f32(lz*lz))`, **not** the `f32(f32(lx*lx) + f32(lz*lz))` the source text
 * spells. Every constant below was derived from exact rational arithmetic (Python `Fraction`
 * + explicit binary32 rounding, `dis/gen_radius_cases.py` in t_981fcace's workspace), never
 * from the port's own helpers. The 3-D sibling rule (`gpoly`/`gpolyobj::setradius`, the same
 * `fmul`+`fmadd` shape on three squares) is pinned in `tests/fma-contraction-sweep.test.ts`.
 */
const SETRADIUS_CASES = [
  { lx: 0x3e846cce, lz: 0x3e2e46b7, radius: 0x3e1e85ce, oldRadius: 0x3e1e85cd },
  { lx: 0x3f6e5d2e, lz: 0x3f74d974, radius: 0x3f2adb6d, oldRadius: 0x3f2adb6c },
  { lx: 0x3ff1e575, lz: 0x3fef9a9d, radius: 0x3faa3cec, oldRadius: 0x3faa3ced },
];

describe('agent::setradius() — the shipped contraction', () => {
  it('derives fRadius from the contracted square sum, not the per-operation chain', () => {
    for (const c of SETRADIUS_CASES) {
      const lx = fromBits(c.lx);
      const lz = fromBits(c.lz);
      const deps = makeDeps();
      // `agent::SetGeometry`'s `setlen()` reads the bounding box through this seam; pin it to
      // the case's `(fLength[0], fLength[2])` (`fLength[1]` is unused by the 2-D rule) with
      // the stub's `fRadiusScale = fScale = 1`.
      (deps.geometry as unknown as { lengths: () => readonly [number, number, number] }).lengths =
        () => [lx, 0, lz] as const;
      const agent = new Agent(deps);
      agent.setGeometry();
      agent.setRadius();
      expect(bitsOf(agent.radius()), 'the derived fRadius').toBe(c.radius);
      // non-vacuity: the pre-sweep form (both squares rounded) is a different value here
      const oldRadius = f32(
        f32(f32(Math.sqrt(f32(f32(lx * lx) + f32(lz * lz))) * f32(1)) * f32(1)) * 0.5,
      );
      expect(bitsOf(oldRadius)).toBe(c.oldRadius);
      expect(c.radius).not.toBe(c.oldRadius);
    }
  });
});

// ---------------------------------------------------------------------------
// 6. the contraction sweep — drives for the sites whose pins could not fail
// ---------------------------------------------------------------------------

/**
 * Round 2 of this card's review found that the sweep's pins for `agent::FieldOfView`,
 * `agent::UpdateVision`'s pitch/yaw and `UpdateBody`'s barrier pass composed
 * `f32Fma(a, b, c)` from the pinned constants instead of *calling* the ported site: the cases
 * never ran the code, so reverting a site left the whole suite green (the case only asserted
 * the pre-sweep form different of itself). These drives call the site and compare the bits the
 * port produces, so a revert fails.
 *
 * Every expected value comes from an exact-rational derivation (Python `Fraction` + an
 * explicit correctly-rounded binary32/binary64 round — `dis/gen_pins2.py` and
 * `dis/gen_barrier_drives.py` in t_981fcace's workspace), never from the port's own helpers.
 * The barrier drives were generated by a script that rejects any drive whose shipped and
 * pre-sweep outcomes agree, and each drive is built so the *other* term of the targeted `||`
 * is non-discriminating (so the short-circuit cannot hide a revert).
 */

/** `0xdeadbeef` for a binary32 bit pattern. */
function hex(bits: number): string {
  return '0x' + (bits >>> 0).toString(16).padStart(8, '0');
}

interface BarrierSpec {
  readonly xmax: number;
  readonly xmin: number;
  readonly zmin: number;
  readonly zmax: number;
  /** The two `barrier::dist()` answers, in call order (`x(),z()` then `lastX(),lastZ()`). */
  readonly dist: number;
  readonly disto: number;
  readonly sina: number;
  readonly cosa: number;
}

function makeBarrier(spec: BarrierSpec): BarrierLike {
  let call = 0;
  return {
    xmin: () => fromBits(spec.xmin),
    xmax: () => fromBits(spec.xmax),
    zmin: () => fromBits(spec.zmin),
    zmax: () => fromBits(spec.zmax),
    // `barrier::dist()` is called as `dist( x(), z() )` then `dist( lastX(), lastZ() )`
    dist: () => fromBits(call++ === 0 ? spec.dist : spec.disto),
    sina: () => spec.sina,
    cosa: () => spec.cosa,
  };
}

/** Put exactly one barrier on the cursor for the pass that is about to run. */
function serveOnce(deps: TestDeps, barrier: BarrierLike): void {
  let served = false;
  deps.barrierList.reset = () => {};
  deps.barrierList.next = () => {
    if (served) return null;
    served = true;
    return { barrier };
  };
  deps.barrierList.stickyBarriers = () => false;
}

interface BarrierDrive {
  /** Which ported site the drive is built to kill when reverted. */
  readonly site: string;
  readonly cr: number;
  /** Position before the step (`f32` bits). */
  readonly startX: number;
  readonly startZ: number;
  readonly dpos: number;
  /** `agent.setYaw()` — degrees; the step moves `(-dpos*sin(yaw), -dpos*cos(yaw))`. */
  readonly yaw: number;
  readonly xmax: number;
  readonly xmin: number;
  readonly zmin: number;
  readonly zmax: number;
  readonly dist: number;
  readonly disto: number;
  readonly sina: number;
  readonly cosa: number;
  readonly expectX: number;
  readonly expectZ: number;
}

const D_BARRIER = 0x3d9c14cc; // f32(0.07621154189109802) — `barrier::dist` in every drive

/**
 * `UpdateBody`'s barrier comparisons — `0x26a04`/`0x26a18` (`xmax() > -FF*CarryRadius() +`,
 * `this.x()` and `this.lastX()`), `0x26a2c`/`0x26a40` (`xmin() > +FF*CarryRadius() +` — the
 * inner test that `break`s out of the barrier walk), `0x26a58`/`0x26a6c`
 * (`zmin() < +FF*CarryRadius() +`) and `0x26a80`/`0x26a94` (`zmax() > -FF*CarryRadius() +`).
 * Every drive puts the barrier's own bound exactly one ulp from the shipped `fmadd`'s value
 * (on the *unfused* value), so the shipped form takes one branch and the pre-sweep form the
 * other; the *other* term of the targeted `||` is always built non-discriminating, and for the
 * two `xmin` drives — an `&&` — true in both forms, so neither the short-circuit nor the `&&`
 * can hide a revert. `expectX`/`expectZ` are the bits the shipped code produces (for the
 * `xmin` pair the shipped form `break`s, so only the step's own movement shows).
 */
const BARRIER_BOUND_DRIVES: readonly (BarrierDrive & { readonly name: string })[] = [
  {
    name: 'X1',
    site: 'xmax() > -FF*CarryRadius() + x() (0x26a04)',
    cr: 0x3f000221,
    startX: 0x411551ec,
    startZ: 0xc2480000,
    dpos: 1,
    yaw: 90,
    xmax: 0x40fa7a9e,
    xmin: 0xc2c80000,
    zmin: 0xc2c80000,
    zmax: 0x42c80000,
    dist: D_BARRIER,
    disto: D_BARRIER,
    sina: 1,
    cosa: 0,
    expectX: 0x410551ec,
    expectZ: 0xc24648e3,
  },
  {
    name: 'X2',
    site: 'xmax() > -FF*CarryRadius() + lastX() (0x26a18)',
    cr: 0x3f000221,
    startX: 0x410551ec,
    startZ: 0xc2480000,
    dpos: 1,
    yaw: -90,
    xmax: 0x40fa7a9e,
    xmin: 0xc2c80000,
    zmin: 0xc2c80000,
    zmax: 0x42c80000,
    dist: D_BARRIER,
    disto: D_BARRIER,
    sina: 1,
    cosa: 0,
    expectX: 0x411551ec,
    expectZ: 0xc24648e3,
  },
  {
    name: 'X3',
    site: 'xmin() > +FF*CarryRadius() + x() — the break (0x26a2c)',
    cr: 0x3f000244,
    startX: 0x40eaa3d8,
    startZ: 0xc2480000,
    dpos: 1,
    yaw: -90,
    xmax: 0x42c80000,
    xmin: 0x410d668c,
    zmin: 0xc2c80000,
    zmax: 0x42c80000,
    dist: D_BARRIER,
    disto: D_BARRIER,
    sina: 1,
    cosa: 0,
    expectX: 0x410551ec,
    expectZ: 0xc2480000,
  },
  {
    name: 'X4',
    site: 'xmin() > +FF*CarryRadius() + lastX() — the break (0x26a40)',
    cr: 0x3f000244,
    startX: 0x410551ec,
    startZ: 0xc2480000,
    dpos: 1,
    yaw: 90,
    xmax: 0x42c80000,
    xmin: 0x410d668c,
    zmin: 0xc2c80000,
    zmax: 0x42c80000,
    dist: D_BARRIER,
    disto: D_BARRIER,
    sina: 1,
    cosa: 0,
    expectX: 0x40eaa3d8,
    expectZ: 0xc2480000,
  },
  {
    name: 'Z1',
    site: 'zmin() < +FF*CarryRadius() + z() (0x26a58)',
    cr: 0x3f0c062a,
    startX: 0x410551ec,
    startZ: 0xc24c0000,
    dpos: 1,
    yaw: 180,
    xmax: 0x42c80000,
    xmin: 0xc2c80000,
    zmin: 0xc245ca4e,
    zmax: 0x42c80000,
    dist: D_BARRIER,
    disto: D_BARRIER,
    sina: 1,
    cosa: 0,
    expectX: 0x410551ec,
    expectZ: 0xc2461858,
  },
  {
    name: 'Z2',
    site: 'zmin() < +FF*CarryRadius() + lastZ() (0x26a6c)',
    cr: 0x3f0c062a,
    startX: 0x410551ec,
    startZ: 0xc2480000,
    dpos: 1,
    yaw: 0,
    xmax: 0x42c80000,
    xmin: 0xc2c80000,
    zmin: 0xc245ca4e,
    zmax: 0x42c80000,
    dist: D_BARRIER,
    disto: D_BARRIER,
    sina: 1,
    cosa: 0,
    expectX: 0x410551ec,
    expectZ: 0xc24a1858,
  },
  {
    name: 'Z3',
    site: 'zmax() > -FF*CarryRadius() + z() (0x26a80)',
    cr: 0x3f0c062a,
    startX: 0x410551ec,
    startZ: 0xc2440000,
    dpos: 1,
    yaw: 0,
    xmax: 0x42c80000,
    xmin: 0xc2c80000,
    zmin: 0xc2c80000,
    zmax: 0xc24a35b2,
    dist: D_BARRIER,
    disto: D_BARRIER,
    sina: 1,
    cosa: 0,
    expectX: 0x410551ec,
    expectZ: 0xc2461858,
  },
  {
    name: 'Z4',
    site: 'zmax() > -FF*CarryRadius() + lastZ() (0x26a94)',
    cr: 0x3f0c062a,
    startX: 0x410551ec,
    startZ: 0xc2480000,
    dpos: 1,
    yaw: 180,
    xmax: 0x42c80000,
    xmin: 0xc2c80000,
    zmin: 0xc2c80000,
    zmax: 0xc24a35b2,
    dist: D_BARRIER,
    disto: D_BARRIER,
    sina: 1,
    cosa: 0,
    expectX: 0x410551ec,
    expectZ: 0xc2421858,
  },
];

/**
 * The three fused `p` values — `0x26b34 fnmadd s1, s1, s7, s4` (`f32Fma(FF, cr, -|dist|)`) and
 * `0x26b08`/`0x26b30 fmadd` (`f32Fma(FF, cr, +|dist|)`, on the sign-change and the
 * pass-through paths). `sina = 0`, `cosa = ±1` and `x() = 0` put the movement on `x` exactly,
 * where the p value's own rounding survives: `x = -p * cosa` bit for bit.
 */
const BARRIER_P_DRIVES: readonly (BarrierDrive & { readonly name: string })[] = [
  {
    name: 'P1',
    site: 'p = f32Fma(FF, cr, -|dist|) (0x26b34)',
    cr: 0x3f000221,
    startX: 0,
    startZ: 0xc2480000,
    dpos: 0,
    yaw: 0,
    xmax: 0x42c80000,
    xmin: 0xc2c80000,
    zmin: 0xc2c80000,
    zmax: 0x42c80000,
    dist: D_BARRIER,
    disto: D_BARRIER,
    sina: 0,
    cosa: -1,
    expectX: 0x3edb8e76,
    expectZ: 0xc2480000,
  },
  {
    name: 'P2',
    site: 'p = f32Fma(FF, cr, +|dist|), sign change (0x26b08)',
    cr: 0x3f066fd7,
    startX: 0,
    startZ: 0xc2480000,
    dpos: 0,
    yaw: 0,
    xmax: 0x42c80000,
    xmin: 0xc2c80000,
    zmin: 0xc2c80000,
    zmax: 0x42c80000,
    dist: D_BARRIER,
    disto: 0xbd9c14cc,
    sina: 0,
    cosa: 1,
    expectX: 0x3f1b4a99,
    expectZ: 0xc2480000,
  },
  {
    name: 'P3',
    site: 'p = f32Fma(FF, cr, +|dist|), pass-through (0x26b30)',
    cr: 0x3d35b004,
    startX: 0,
    startZ: 0xc2480000,
    dpos: 0,
    yaw: 0,
    xmax: 0x42c80000,
    xmin: 0xc2c80000,
    zmin: 0xc2c80000,
    zmax: 0x42c80000,
    dist: D_BARRIER,
    disto: 0xbd9c14cc,
    sina: 0,
    cosa: 1,
    expectX: 0x3df7d55d,
    expectZ: 0xc2480000,
  },
];

const SWEEP_CONFIG = loadVector<ConfigVector>('config.minitest_voff.json');

describe('the contraction sweep — drives for the agent sites (t_981fcace)', () => {
  beforeEach(() => {
    resetGlobals();
    resetAgentConfig();
    resetAgentStatics();
    processWorldfile(documentFromJs(SWEEP_CONFIG.keys));
    globals.worldsize = 100;
    globals.numEnergyTypes = 1;
  });

  function steppedAgent(drive: BarrierDrive): Agent {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.setGenomeReady();
    const nerves = deps.testNerves!;
    nerves.set('Eat', 0);
    nerves.set('Mate', 0);
    nerves.set('Fight', 0);
    nerves.set('Speed', drive.dpos);
    nerves.set('Yaw', 0.5); // YE_OPPOSE with YawOppose 0.5 -> dyaw = 0
    nerves.set('YawOppose', 0.5);
    nerves.set('Focus', 0);
    agent.setCarryRadius(fromBits(drive.cr));
    agent.setX(fromBits(drive.startX));
    agent.setZ(fromBits(drive.startZ));
    agent.setYaw(drive.yaw);
    serveOnce(deps, makeBarrier(drive));
    agent.updateBody(1.0, agentConfig.speed2DPosition, 0, null);
    return agent;
  }

  it('UpdateBody drives the fused barrier bounds (0x26a04-0x26a94)', () => {
    for (const drive of BARRIER_BOUND_DRIVES) {
      const agent = steppedAgent(drive);
      expect(
        `${hex(bitsOf(agent.x()))} ${hex(bitsOf(agent.z()))}`,
        `${drive.name}: ${drive.site}`,
      ).toBe(`${hex(drive.expectX)} ${hex(drive.expectZ)}`);
    }
  });

  it('UpdateBody drives the three fused `p` values (0x26b08/0x26b30/0x26b34)', () => {
    for (const drive of BARRIER_P_DRIVES) {
      const agent = steppedAgent(drive);
      expect(
        `${hex(bitsOf(agent.x()))} ${hex(bitsOf(agent.z()))}`,
        `${drive.name}: ${drive.site}`,
      ).toBe(`${hex(drive.expectX)} ${hex(drive.expectZ)}`);
    }
  });

  it('agent::FieldOfView calls the fused double fmadd (0x261d0)', () => {
    // `focus * ( maxFocus - minFocus ) + minFocus`, the bounds' difference a float `fsub`
    // (`0x261c4`), the multiply-add one `fmadd d0, d0, d2, d1` in binary64 (`0x261d0`), the
    // `float` return an `fcvt` (`0x261d4`). Exact-rational: fused 0xbeff3b6f, the pre-sweep
    // form (product rounded to float first) 0xbeff3b6e.
    agentConfig.minFocus = fromBits(0xbf000000);
    agentConfig.maxFocus = fromBits(0x3f34fdf4);
    agentConfig.invertFocus = false;
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    deps.testNerves!.set('Focus', fromBits(0x3aa2db62));
    expect(hex(bitsOf(agent.fieldOfView()))).toBe(hex(0xbeff3b6f));
    // and the drive is not vacuous: the pre-sweep form is a different bit pattern here
    expect(
      hex(
        bitsOf(
          f32(
            f32(fromBits(0x3aa2db62) * f32(fromBits(0x3f34fdf4) - fromBits(0xbf000000))) +
              fromBits(0xbf000000),
          ),
        ),
      ),
    ).toBe(hex(0xbeff3b6e));
  });

  it('agent::UpdateVision drives the fused pitch (0x262f0) and yaw (0x26338)', () => {
    agentConfig.vision = true;
    agentConfig.enableVisionPitch = true;
    agentConfig.enableVisionYaw = true;
    agentConfig.minVisionPitch = fromBits(0xc3340000);
    agentConfig.maxVisionPitch = fromBits(0x43340000);
    agentConfig.minVisionYaw = fromBits(0xc3340000);
    agentConfig.maxVisionYaw = fromBits(0x43340000);
    const deps = makeDeps();
    const seen = { pitch: [] as number[], yaw: [] as number[] };
    (deps as unknown as { visionCamera: unknown }).visionCamera = {
      setFrustum: () => {},
      setAspect: () => {},
      setPitch: (pitch: number) => seen.pitch.push(pitch),
      setYaw: (yaw: number) => seen.yaw.push(yaw),
    };
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    const nerves = deps.testNerves!;
    // `nerve * ( maxVision* - minVision* ) + minVision*`, one binary64 `fmadd` then an `fcvt`
    const PITCH_CASES: readonly (readonly [number, number])[] = [
      [0x3b070111, 0xc3334227],
      [0x3b6410b6, 0xc332bf49],
      [0x3b6d6777, 0xc332b227],
    ];
    for (const [nerve, fused] of PITCH_CASES) {
      nerves.set('VisionPitch', fromBits(nerve));
      nerves.set('VisionYaw', fromBits(nerve));
      seen.pitch.length = 0;
      seen.yaw.length = 0;
      agent.updateVision();
      expect(hex(bitsOf(seen.pitch[0]!)), `pitch ${hex(nerve)}`).toBe(hex(fused));
      expect(hex(bitsOf(seen.yaw[0]!)), `yaw ${hex(nerve)}`).toBe(hex(fused));
      // non-vacuity: the pre-sweep form rounds the product to float first
      const delta = f32(fromBits(0x43340000) - fromBits(0xc3340000));
      expect(hex(bitsOf(f32(f32(fromBits(nerve) * delta) + fromBits(0xc3340000))))).toBe(
        hex(fused === 0xc3334227 ? 0xc3334226 : fused === 0xc332bf49 ? 0xc332bf48 : 0xc332b226),
      );
    }
  });
});

// ---------------------------------------------------------------------------
// 7. the contraction sweep — round 4: the L8 heuristic-fitness sites (t_981fcace)
// ---------------------------------------------------------------------------

/**
 * Review round 3 (contract lens) took this card's own `fused_map2.txt` and found three
 * single-precision fused multiply-adds in L8's own lane that no outcome list mentioned:
 *
 *   `__ZN5agent11lastrewardsEff`                `0x25e3c fmadd s0, s9, s0, s1`
 *   `__ZN5agent25ProjectedHeuristicFitnessEv`   `0x25ed4 fmadd s0, s10, s0, s9`
 *                                               `0x25f00 fmadd s0, s1, s2, s0`
 *
 * Neither is `setradius`-shaped: the age term of `lastrewards` keeps its own `fmul`
 * (`0x25e34`) + `fdiv` (`0x25e38`), and `ProjectedHeuristicFitness`'s `base` keeps its three
 * separate float operations (`0x25e98`/`0x25ea4 fmul`, `0x25eb0 fdiv`) — only the products
 * that are added are contracted. The pre-sweep port rounded each of those products, which
 * differs in the last bit on 2.4 % (`lastrewards`) and 12.0 % / 10.8 % (the two projected
 * sites, 17.6 % together) of 200 000 exact-rational samples.
 *
 * Both drives below call the ported code (`lastRewards`, `projectedHeuristicFitness`), so a
 * revert fails here directly. Every constant is the correctly-rounded binary32 of the exact
 * rational expression, derived in `dis/gen_heur_pins.py` under t_981fcace's workspace — never
 * from the port's helpers — and every case is checked non-vacuous against the pre-sweep form.
 *
 * The runtime scalars the derivation depends on are asserted too, so the pin cannot go stale
 * silently: `MaxAge()` = 750 (`0x443b8000`, `makeGenes().lifespan`), `fMaxEnergy.sum()` = 750
 * (`agent::initenergy` with the voff worldfile, `f32(500 + f32(0.75 * 500) / 1.5)`) and
 * `fAge` = 6 (`0x40c00000`; native's `long fAge`, `scvtf`-ed by the binary).
 */
describe('the contraction sweep — the lastrewards/ProjectedHeuristicFitness sites (t_981fcace)', () => {
  beforeEach(() => {
    resetGlobals();
    resetAgentConfig();
    resetAgentStatics();
    processWorldfile(documentFromJs(SWEEP_CONFIG.keys));
    globals.worldsize = 100;
    globals.numEnergyTypes = 1;
  });

  /** The four `Simulation` seams `ProjectedHeuristicFitness` reads, as mutable stubs. */
  interface SimSeams {
    lifeFractionSamples: () => number;
    lifeFractionRecent: () => number;
    energyFitnessParameter: () => number;
    ageFitnessParameter: () => number;
  }

  function sweepAgent(): { agent: Agent; sim: SimSeams } {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.setGenomeReady();
    // the derived scalars the exact-rational pins assume — asserted, so drift fails loudly
    expect(hex(bitsOf(agent.maxAge())), 'MaxAge()').toBe('0x443b8000'); // 750
    expect(hex(bitsOf(agent.maxEnergy().sum())), 'fMaxEnergy.sum()').toBe('0x443b8000');
    (agent as unknown as { fAge: number }).fAge = 6; // 0x40c00000
    return { agent, sim: deps.simulation as unknown as SimSeams };
  }

  it('agent::lastrewards contracts the energy product (0x25e3c)', () => {
    const { agent } = sweepAgent();
    expect(hex(bitsOf(agent.currentHeuristicFitness())), 'fHeuristicFitness starts at 0').toBe(
      '0x00000000',
    );
    // `fEnergy.sum() / fMaxEnergy.sum()` = 265.1640625 / 750
    agent.setEnergy(new Energy(fromBits(0x43849500)));
    expect(hex(bitsOf(agent.normalizedEnergy())), 'normalizedEnergy()').toBe('0x3eb504c7');
    agent.lastRewards(fromBits(0x4031842a), fromBits(0x3ecd863a));
    expect(hex(bitsOf(agent.currentHeuristicFitness())), 'lastrewards').toBe('0x3f7bddf8');
    // non-vacuity: the pre-sweep form rounds the energy product to float first (0x25e3c is
    // `fmadd s0, s9, s0, s1`, i.e. `f32(ef*ne + ageTerm)` in ONE rounding; the age term itself
    // is `f32(f32(af * 6) / 750)` from `0x25e34`/`0x25e38` and is the same in both forms)
    const ageTerm = f32(f32(fromBits(0x3ecd863a) * 6) / 750);
    expect(hex(bitsOf(ageTerm))).toBe('0x3b5274f8');
    expect(hex(bitsOf(f32(f32(fromBits(0x4031842a) * fromBits(0x3eb504c7)) + ageTerm)))).toBe(
      '0x3f7bddf9',
    );
  });

  it('agent::ProjectedHeuristicFitness contracts both products (0x25ed4/0x25f00)', () => {
    const { agent, sim } = sweepAgent();
    const hf = fromBits(0x42b79cac);
    const lfr = fromBits(0x3f01b6f7);
    const efp = fromBits(0x3e15f501);
    const afp = fromBits(0x3ea63ee3);
    sim.lifeFractionSamples = () => 60; // >= 50 takes the fused `return` arm
    sim.lifeFractionRecent = () => lfr;
    sim.energyFitnessParameter = () => efp;
    sim.ageFitnessParameter = () => afp;
    // no setter for `fHeuristicFitness`; poke the private field (setup only — the site under
    // test is `projectedHeuristicFitness`, and poking keeps this drive independent of
    // `lastRewards`, so a revert there cannot mask a revert here)
    (agent as unknown as { fHeuristicFitness: number }).fHeuristicFitness = hf;
    agent.setEnergy(new Energy(fromBits(0x44219bd9)));
    expect(hex(bitsOf(agent.normalizedEnergy())), 'normalizedEnergy()').toBe('0x3f5ca65d');
    expect(hex(bitsOf(agent.projectedHeuristicFitness())), 'projectedHeuristicFitness').toBe(
      '0x45b5b840',
    );
    // the `base` term is the same in both forms (three separate float ops, all right)
    const base = f32(f32(f32(hf * lfr) * 750) / 6);
    expect(hex(bitsOf(base))).toBe('0x45b5b5ec');
    // non-vacuity: the pre-sweep form rounds both products before the adds
    const ne = fromBits(0x3f5ca65d);
    expect(hex(bitsOf(f32(f32(base + f32(efp * ne)) + f32(afp * lfr))))).toBe('0x45b5b83f');
    // …and it is the *projection* the port returns, not the raw fitness
    expect(agent.projectedHeuristicFitness()).not.toBe(hf);
  });
});

// ---------------------------------------------------------------------------
// The contraction-sweep follow-up (t_2a625bd5) — `agent::LastEatDistance`
// ---------------------------------------------------------------------------

describe('the contraction sweep follow-up — agent::LastEatDistance (t_2a625bd5)', () => {
  beforeEach(() => {
    resetGlobals();
    resetAgentConfig();
    resetAgentStatics();
    processWorldfile(documentFromJs(SWEEP_CONFIG.keys));
    globals.worldsize = 100;
    globals.numEnergyTypes = 1;
  });

  /**
   * `agent::LastEatDistance` (`agent.h:419` — `dist( fPosition[0], fPosition[2],
   * fLastEatPosition[0], fLastEatPosition[2] )`, `dist` = `utils/misc.h:96`), inlined into
   * `TSimulation::GetMatePotential` at 0x9947c-0x9948c:
   *
   *   99480: fsub  s4, s4, s6      ; dz
   *   99484: fmul  s4, s4, s4      ; f32(dz*dz)   <- the one rounded square
   *   99488: fmadd s3, s3, s3, s4  ; dx*dx + that, ONE rounding
   *   9948c: fsqrt s3, s3          ; **float** sqrt
   *
   * The pre-change port used `Math.hypot` — a binary64 hypotenuse whose `f32` narrowing
   * differs from the fused float `sqrt` (this generator, `dis/gen_final.py`, found 3 such
   * pairs in its first 8 candidates). The `hypot` column below is `bitsOf(Math.hypot(dx,
   * dz))` measured in V8 for the same operands, so the non-vacuity assertion is the
   * *revert's* value, not a third form.
   */
  const LAS_CASES = [
    { x: 0x404d6fda, z: 0xc1a20e37, ex: 0x4189fb6a, ez: 0xc173ca1f, fused: 0x416e88f3, hypot: 0x416e88f4 },
    { x: 0x41a75e4c, z: 0xc0db7660, ex: 0x419bb6ad, ez: 0xc191857c, fused: 0x4136cdca, hypot: 0x4136cdc9 },
    { x: 0x4063e453, z: 0xc134939d, ex: 0x4170c2f2, ez: 0xc140ebe7, fused: 0x413833e2, hypot: 0x413833e1 },
    { x: 0x41b6e86c, z: 0xc1358636, ex: 0x40c7316f, ez: 0xc05dc510, fused: 0x4193487c, hypot: 0x4193487d },
  ];

  it('contracts the square sum and takes the float sqrt (0x99488/0x9948c)', () => {
    const deps = makeDeps();
    const agent = Agent.getFreeAgent(deps);
    agent.grow(0, false);
    agent.setGenomeReady();
    const poke = agent as unknown as {
      fPosition: [number, number, number];
      fLastEatPosition: [number, number, number];
    };

    for (const c of LAS_CASES) {
      const label = `${hex(c.x)}/${hex(c.z)}`;
      poke.fPosition[0] = fromBits(c.x);
      poke.fPosition[2] = fromBits(c.z);
      poke.fLastEatPosition[0] = fromBits(c.ex);
      poke.fLastEatPosition[2] = fromBits(c.ez);

      expect(hex(bitsOf(agent.lastEatDistance())), `lastEatDistance ${label}`).toBe(hex(c.fused));

      // non-vacuity: the pre-change `Math.hypot` form (narrowed the way the drive narrows
      // every compared value — the nerve/array store in the site's own callers is a double,
      // but this site *returns* a float and the two forms already differ as floats)
      const dx = f32(fromBits(c.x) - fromBits(c.ex));
      const dz = f32(fromBits(c.z) - fromBits(c.ez));
      expect(hex(bitsOf(Math.hypot(dx, dz))), `pre-change hypot ${label}`).toBe(hex(c.hypot));
      expect(hex(c.hypot), `non-vacuous ${label}`).not.toBe(hex(c.fused));
    }
  });
});

/**
 * Lane L8 — the motion pair in `UpdateBody` (`__sincos_stret`, task t_1263719e).
 *
 * The shipped `agent::UpdateBody` reaches Apple's **double** `__sincos_stret` for
 * `sin/cos( yaw() * DEGTORAD )` (`0x265f8 → bl 0xa3988`, and it is *not* the `sinf`/`cosf` pair —
 * PARITY's `W1d-fu/camera-calls-sincosf-not-sinf-cosf`), so the port calls lane W1d's transcribed
 * `libm.sin`/`libm.cos`. Two measured facts, and the second is why this test has to assert the
 * call site rather than a value:
 *
 *  * the functions disagree on ~4 % of the yaw domain (counts pinned below), and
 *  * narrowing `-dpos * …` to `f32` makes the disagreement **invisible in every recorded
 *    artifact** — 0 flips over the whole (yaw, dpos) grid below — so no golden, farm line or
 *    per-agent trace can catch a silent revert to V8's `Math.sin`/`Math.cos`.
 */
describe('L8 — UpdateBody motion through the oracle’s `__sincos_stret` (t_1263719e)', () => {
  /** `yaw()` is a `float` in [0, 360); 20,000 points, `360 / 20000 = 0.018` exactly. */
  const YAWS: readonly number[] = Array.from({ length: 20000 }, (_, i) => f32(i * 0.018));
  /**
   * `dpos` is native's `f32( speedNerve * MaxSpeed * MotionRate )`, clipped to `MaxVelocity`;
   * these four speeds bracket the band the recorded worlds reach.
   */
  const DPOS: readonly number[] = [0.05, 0.1, 0.25, 0.5].map((v) => f32(v));

  it('disagrees with V8 on 847 (sin) / 953 (cos) of 20,000 yaws, and the narrowing hides all of it', () => {
    const sLibm: number[] = [];
    const sV8: number[] = [];
    const cLibm: number[] = [];
    const cV8: number[] = [];
    let sinDiff = 0;
    let cosDiff = 0;

    for (const yaw of YAWS) {
      // `yaw()` is a float, `DEGTORAD` (0.017453292) is the native double literal, so the call's
      // argument is a double — exactly what `__sincos_stret` received.
      const arg = yaw * DEGTORAD;
      const sl = libmSin(arg);
      const sv = Math.sin(arg);
      const cl = libmCos(arg);
      const cv = Math.cos(arg);
      sLibm.push(sl);
      sV8.push(sv);
      cLibm.push(cl);
      cV8.push(cv);
      if (sl !== sv) sinDiff++;
      if (cl !== cv) cosDiff++;
    }

    let sinFlip = 0;
    let cosFlip = 0;
    let samples = 0;
    for (const dpos of DPOS) {
      for (let i = 0; i < YAWS.length; i++) {
        samples++;
        if (f32(-dpos * sLibm[i]!) !== f32(-dpos * sV8[i]!)) sinFlip++;
        if (f32(-dpos * cLibm[i]!) !== f32(-dpos * cV8[i]!)) cosFlip++;
      }
    }

    expect([sinDiff, cosDiff], 'raw disagreement counts on the yaw domain').toEqual([847, 953]);
    expect([sinFlip, cosFlip], 'flips after the f32 narrowing').toEqual([0, 0]);
    expect(samples, 'the (yaw, dpos) grid').toBe(80000);
  });

  it('the motion site calls the transcribed pair, not V8', () => {
    const source = readFileSync(join(HERE, '..', 'src', 'model', 'agent', 'agent.ts'), 'utf8');

    expect(source).toContain('dx = f32(-dpos * libmSin(this.yaw() * DEGTORAD));');
    expect(source).toContain('dz = f32(-dpos * libmCos(this.yaw() * DEGTORAD));');
    // the pre-change form, so the shortcut cannot come back unnoticed (no golden can see it)
    expect(source).not.toContain('f32(-dpos * Math.sin(');
    expect(source).not.toContain('f32(-dpos * Math.cos(');
  });
});

