/**
 * Lane L6 (brain core) — the lane's acceptance tests.
 *
 * Two layers:
 *
 *   1. **Unit tests** for the pieces that can be pinned without native: the C `%g` rounding
 *      rules, `nint`/`f32`/`toShort`, the nerve activation-buffer indirection (including the
 *      swap the models perform), `SynapseMap`'s std::map ordering, the sheets geometry
 *      (spacing/insets/absolute positions/receptive-field subsets) and the cull.
 *
 *   2. **Differential parity against the oracle's own code** (`brainprobe`, built from the
 *      native tree's `libpolyworld.dylib` by `src/model/brain/core/native/run_brainprobe.sh`).
 *      The probe drives the *real* `FiringRateModel`, `SpikingModel`, `Brain::dumpAnatomical/
 *      startFunctional/writeFunctional/dumpSynapses` over a synthetic brain it describes in a
 *      spec file; this test rebuilds that brain with the port, runs it, and diffs
 *
 *        - `run/brain/function/**`-shaped bytes (`startFunctional` + one `writeFunctional`
 *          per step + `endFunctional`),
 *        - `run/brain/synapses/**`-shaped bytes (`dumpSynapses`, after learning),
 *        - `run/brain/anatomy/**`-shaped bytes (`dumpAnatomical`),
 *        - the raw IEEE-754 bits of every activation and of every final efficacy, so a 1-ulp
 *          divergence cannot hide behind `%g`'s six digits,
 *        - `%g`/`%G`/`%f`/`%+06.4f`/`%hd`/`%ld` formatting against this machine's `printf`.
 *
 *      Three variants are diffed: `firingrate` (learning on), `taugain` (tau/gain model with
 *      a *frozen* brain, i.e. the learning loop skipped) and `spiking` (50 brain steps per
 *      world step, ~2600 `drand48` draws per step, STDP).
 *
 * The native inputs are generated by the probe's own LCG and written to the spec file, so
 * this test needs no reference data checked in; and the harness's `drand48` stand-in is
 * verified against the probe's glibc samples before it is used (see `describe('drand48')`).
 *
 * If the native tree (or its built library) is not present the differential suite is skipped
 * with a message rather than failing: the lane's contract is byte-exact parity *where the
 * oracle exists*, and a developer without the native build should still get the unit tests.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { threadId } from 'node:worker_threads';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import {
  Brain,
  brainConfig,
  BrainArchitecture,
  BrainStepsPerWorldStep,
  Dimensions,
  distortionIndex,
  energyUseOf,
  FiringRateModel,
  LearningMode,
  Nerve,
  NerveType,
  neuronLocalIndexFromBase,
  NeuronModelKind,
  NervousSystem,
  nsynjiPerNeuron,
  remainderUpdate,
  SpikingModel,
  stdevOf,
  Sheet,
  SheetsModel,
  StringTextFile,
  SynapseMap,
  Synapse,
  synapseCountNew,
  Neuron,
  TdAbsBranch,
  tdFromToAbs,
  Vector2f,
  Vector2i,
  Vector3f,
  ActivationBuffer,
  cRound,
  f32,
  fma64,
  logistic,
  nint,
  sprintfC,
  toShort,
  type BrainTextFile,
  type FiringRateNeuronAttrs,
  type NeuronModel,
  type RngSurface,
  type SpikingNeuronAttrs,
} from '../src/model/brain/core';
// lane L1's transcribed libm (the `libm census` block measures the port's own `exp` against
// the oracle's, and asserts it is not `Math.exp`)
import { exp } from '../src/model/rng/libm';

// ---------------------------------------------------------------------------
// native probe plumbing
// ---------------------------------------------------------------------------

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..');
const NATIVE = process.env['POLYWORLD_NATIVE'] ?? resolve(REPO, '..', 'polyworld');

/**
 * Where `run_brainprobe.sh` compiles the probe and writes its eight modes' output.
 *
 * t_d5ed17d8: this used to be ONE fixed directory (`node_modules/.cache/brainprobe`) shared by
 * every process on the checkout. Two lanes verifying at the same time both linked
 * `$OUT/brainprobe`; one `clang++` (with `-g` → `dsymutil`) then read a binary the other was
 * rewriting and the `beforeAll` below threw
 *
 *     error: cannot parse the debug map for '…/node_modules/.cache/brainprobe/brainprobe':
 *     No such file or directory
 *     clang++: error: dsymutil command failed with exit code 1
 *
 * so `tests/brain-core.test.ts` failed as a file and its 76 tests were skipped (~1 pair in 5 with
 * two concurrent full-suite runs, 1 in 2 with two concurrent single-file runs, measured).
 *
 * Keying the directory by process id — plus the vitest worker thread, since `pool: 'threads'` runs
 * every worker in one pid — isolates concurrent runs; this is the same per-process key t_37bf7212
 * gave `tests/logsCorpus.ts`'s candidate root. The directory is passed to the script as its
 * `[outdir]` argument, so the probe cannot end up writing somewhere else. `BRAINPROBE_DIR` still
 * pins a caller's own path (a known location for a human reading the probe's output) and is
 * honoured by the script as well. The only reader of these files is this test file, so no caller
 * needs to know the key.
 */
export function defaultProbeDir(cwd: string, pid: number, thread: number): string {
  const leaf = thread === 0 ? `pid-${pid}` : `pid-${pid}-t${thread}`;
  return join(cwd, 'node_modules', '.cache', 'brainprobe', leaf);
}

const PROBE_DIR_ENV = process.env['BRAINPROBE_DIR'] ?? '';
/** t_d5ed17d8: `false` when the caller pinned `BRAINPROBE_DIR` — then that directory is theirs. */
const PROBE_DIR_IS_OURS = PROBE_DIR_ENV === '';
const PROBE_DIR = PROBE_DIR_IS_OURS ? defaultProbeDir(REPO, process.pid, threadId) : PROBE_DIR_ENV;
const PROBE_SCRIPT = join(REPO, 'src', 'model', 'brain', 'core', 'native', 'run_brainprobe.sh');
const VARIANTS = ['firingrate', 'taugain', 'spiking'] as const;
type Variant = (typeof VARIANTS)[number];

const haveNativeTree = existsSync(join(NATIVE, 'lib', 'libpolyworld.dylib'));

/** t_d5ed17d8: set once `run_brainprobe.sh` has actually produced this run's probe output. */
let probeBuilt = false;

beforeAll(() => {
  if (!haveNativeTree) return;
  // t_d5ed17d8: our own directory starts empty, so a leftover tree (a recycled pid, an interrupted
  // run) cannot be mistaken for this run's output. A caller-pinned `BRAINPROBE_DIR` is left alone:
  // it may hold files the caller put there, and it is the caller's to clean.
  if (PROBE_DIR_IS_OURS) rmSync(PROBE_DIR, { recursive: true, force: true });
  execFileSync('sh', [PROBE_SCRIPT, PROBE_DIR], { cwd: REPO, stdio: 'pipe' });
  for (const variant of VARIANTS) {
    if (!existsSync(join(PROBE_DIR, `spec.${variant}.txt`))) throw new Error(`brainprobe did not write spec.${variant}.txt`);
  }
  probeBuilt = true;

  // provenance for whoever reads these files next: every .txt here is written by the ORACLE
  mkdirSync(PROBE_DIR, { recursive: true });
  writeFileSync(
    join(PROBE_DIR, 'PROVENANCE.txt'),
    [
      `native tree:  ${NATIVE}`,
      `probe dir:    ${PROBE_DIR}`,
      `probe source: src/model/brain/core/native/brainprobe.cc`,
      `probe runner: src/model/brain/core/native/run_brainprobe.sh`,
      '',
      'every .txt in this directory is written by the ORACLE native code (libpolyworld.dylib:',
      'FiringRateModel, SpikingModel, Brain::dumpAnatomical/startFunctional/writeFunctional/',
      'dumpSynapses, loadSynapses, copySynapses, scaleSynapses, AbstractFile::printf) — except',
      'growexpr.txt, whose expressions are a',
      'transcription of GroupsBrain::growSynapses compiled by the native toolchain (the walk',
      'itself needs lanes L5/L8). The learnclamp/learndelta reports are mixed: their `native`',
      'column is the value the shipped model itself stored (the arbiter) while their `before`/',
      '`fused`/`pre` columns are transcriptions, compiled by the same clang that built the',
      'oracle — the probe re-checks its own transcription against the shipped model on every',
      'row and exits non-zero on any disagreement. The `synapses` mode writes three files per',
      'family (spec.<tag>.txt, syndump.<tag>.txt, synapses.<tag>.txt); they are ALSO committed',
      'under src/model/brain/core/native/vectors/ so the reader/writer pair can be replayed',
      'without C++, and the copies here are what that committed corpus is checked against when',
      'the native tree is present (see differential(\'synapses vectors\')).',
      'tests/brain-core.test.ts rebuilds the same brains',
      'with the port and diffs: byte-for-byte for the dump files and the printf vectors,',
      'value-by-value (ulp census) for the raw activation/efficacy bits, and bit-for-bit for',
      'the grow arithmetic.',
    ].join('\n') + '\n',
  );
}, 300_000);

afterAll(() => {
  // t_d5ed17d8: this directory is this process's own build cache and nothing outside this file
  // reads it, so it goes away with the run — otherwise every `npx vitest run` would leave another
  // ~8.5 MB `pid-*` tree under `node_modules/.cache/brainprobe` for good. Best effort by design:
  // cleaning a cache must not be able to red the suite, and a run whose `beforeAll` threw keeps
  // its directory so the failure can be looked at.
  if (!PROBE_DIR_IS_OURS || !probeBuilt) return;
  try {
    rmSync(PROBE_DIR, { recursive: true, force: true });
  } catch {
    /* the directory is a cache; leaving it behind is not a failure */
  }
});

// ---------------------------------------------------------------------------
// the harness's glibc drand48 (lane W1d owns the real one; this is scaffolding, and
// `describe('drand48 stand-in')` checks it against the probe's own glibc draws)
// ---------------------------------------------------------------------------

class GlibcDrand48 implements RngSurface {
  private state = 0n;

  srand48(seed: number): void {
    this.state = ((BigInt(Math.trunc(seed)) << 16n) + 0x330en) & 0xffffffffffffn;
  }

  drand48(): number {
    this.state = (this.state * 0x5deece66dn + 0xbn) & 0xffffffffffffn;
    return Number(this.state) / 281474976710656; // 2^48
  }

  lrand48(): number {
    return Math.floor(this.drand48() * 2147483648);
  }

  srand(): void {
    throw new Error('harness: srand is not used by the brain');
  }

  rand(): number {
    throw new Error('harness: rand is not used by the brain');
  }

  private spare = 0;
  private hasSpare = false;

  nrand(): number {
    if (this.hasSpare) {
      this.hasSpare = false;
      return this.spare;
    }
    let u = 0;
    let v = 0;
    let s = 0;
    do {
      u = 2.0 * this.drand48() - 1.0;
      v = 2.0 * this.drand48() - 1.0;
      s = u * u + v * v;
    } while (s === 0.0 || s >= 1.0);
    const c = Math.sqrt((-2.0 * Math.log(s)) / s);
    this.spare = c * v;
    this.hasSpare = true;
    return c * u;
  }

  nrandScaled(mean: number, stdev: number): number {
    return mean + this.nrand() * stdev;
  }
}

/** A `NervousSystem` whose `Brain *` can be wired up without a genome (native `grow`). */
class ProbeCns extends NervousSystem {
  constructor(rng: RngSurface) {
    super(rng);
  }

  wire(brain: Brain): void {
    this.b = brain;
  }
}

/** A `Brain` whose dims/neural net can be set the way `GroupsBrain::grow` sets them. */
class ProbeBrain extends Brain {
  constructor(cns: NervousSystem) {
    super(cns);
  }

  install(dims: Dimensions, net: NeuronModel): void {
    const target = this.getDimensions();
    target.numNeurons = dims.numNeurons;
    target.numInputNeurons = dims.numInputNeurons;
    target.numOutputNeurons = dims.numOutputNeurons;
    target.numSynapses = dims.numSynapses;
    this._neuralnet = net;
  }
}

interface Spec {
  model: string;
  tauGain: boolean;
  frozen: boolean;
  logisticSlope: number;
  maxWeight: number;
  maxBias: number;
  enableLearning: boolean;
  minlrate: number;
  maxlrate: number;
  decayRate: number;
  scaleLatestSpikes: number;
  drandSeed: number;
  spikingParams: number;
  dims: Dimensions;
  neurons: Array<{ bias: number; tau: number; gain: number; sa: number; sb: number; sc: number; sd: number; start: number; end: number }>;
  synapses: Array<{ from: number; to: number; efficacy: number; lrate: number }>;
  inputs: number[][];
}

function readSpec(tag: string, dir = PROBE_DIR): Spec {
  const text = readFileSync(join(dir, `spec.${tag}.txt`), 'utf8');
  const spec: Spec = {
    model: tag,
    tauGain: false,
    frozen: false,
    logisticSlope: 0,
    maxWeight: 0,
    maxBias: 0,
    enableLearning: false,
    minlrate: 0,
    maxlrate: 0,
    decayRate: 0,
    scaleLatestSpikes: 0,
    drandSeed: 0,
    spikingParams: 0,
    dims: new Dimensions(),
    neurons: [],
    synapses: [],
    inputs: [],
  };

  for (const line of text.split('\n')) {
    if (line.length === 0) continue;
    const f = line.split(' ');
    switch (f[0]) {
      case 'model':
        spec.model = f[1]!;
        break;
      case 'tauGain':
        spec.tauGain = f[1] === '1';
        break;
      case 'frozen':
        spec.frozen = f[1] === '1';
        break;
      case 'logisticSlope':
        spec.logisticSlope = f32(Number(f[1]));
        break;
      case 'maxWeight':
        spec.maxWeight = f32(Number(f[1]));
        break;
      case 'maxBias':
        spec.maxBias = f32(Number(f[1]));
        break;
      case 'enableLearning':
        spec.enableLearning = f[1] === '1';
        break;
      case 'minlrate':
        spec.minlrate = f32(Number(f[1]));
        break;
      case 'maxlrate':
        spec.maxlrate = f32(Number(f[1]));
        break;
      case 'decayRate':
        spec.decayRate = f32(Number(f[1]));
        break;
      case 'scaleLatestSpikes':
        spec.scaleLatestSpikes = f32(Number(f[1]));
        break;
      case 'drandSeed':
        spec.drandSeed = Number(f[1]);
        break;
      case 'spikingParams':
        spec.spikingParams = Number(f[1]);
        break;
      case 'dims':
        spec.dims.numNeurons = Number(f[1]);
        spec.dims.numInputNeurons = Number(f[2]);
        spec.dims.numOutputNeurons = Number(f[3]);
        spec.dims.numSynapses = Number(f[4]);
        break;
      case 'neuron':
        spec.neurons[Number(f[1])!] = {
          bias: f32(Number(f[2])),
          tau: f32(Number(f[3])),
          gain: f32(Number(f[4])),
          sa: f32(Number(f[5])),
          sb: f32(Number(f[6])),
          sc: f32(Number(f[7])),
          sd: f32(Number(f[8])),
          start: Number(f[9]),
          end: Number(f[10]),
        };
        break;
      case 'synapse':
        spec.synapses[Number(f[1])!] = {
          from: Number(f[2]),
          to: Number(f[3]),
          efficacy: f32(Number(f[4])),
          lrate: f32(Number(f[5])),
        };
        break;
      case 'input':
        spec.inputs[Number(f[1])!] = f.slice(2).map(Number);
        break;
      default:
        throw new Error(`unknown spec line: ${line}`);
    }
  }

  return spec;
}

/** Rebuild the probe's brain with the port and run the same steps. */
function runPort(spec: Spec): {
  brain: ProbeBrain;
  model: NeuronModel;
  function: string;
  synapses: string;
  anatomy: string;
  activationBits: string[];
  efficacyBits: string[];
  energyUse: number;
} {
  brainConfig.neuronModel = spec.model === 'spiking'
    ? NeuronModelKind.SPIKING
    : spec.tauGain
      ? NeuronModelKind.TAU_GAIN
      : NeuronModelKind.FIRING_RATE;
  brainConfig.architecture = BrainArchitecture.Groups;
  brainConfig.logisticSlope = spec.logisticSlope;
  brainConfig.maxWeight = spec.maxWeight;
  brainConfig.maxbias = spec.maxBias;
  brainConfig.enableLearning = spec.enableLearning;
  brainConfig.minlrate = spec.minlrate;
  brainConfig.maxlrate = spec.maxlrate;
  brainConfig.decayRate = spec.decayRate;
  brainConfig.learningMode = LearningMode.LEARN_ALL;

  const rng = new GlibcDrand48();
  const cns = new ProbeCns(rng);
  const brain = new ProbeBrain(cns);
  cns.wire(brain);
  if (spec.frozen) brain.freeze();

  const model: NeuronModel = spec.model === 'spiking'
    ? new SpikingModel(cns, spec.scaleLatestSpikes)
    : new FiringRateModel(cns);
  brain.install(spec.dims, model);

  model.init(spec.dims, 0.1);

  // neurons, in the same order and with the same two calls `GroupsBrain::grow` makes
  for (let i = 0; i < spec.dims.numInputNeurons; i++) {
    const neuron = spec.neurons[i]!;
    if (spec.model === 'spiking') {
      const attrs: SpikingNeuronAttrs = { bias: 0, spikingParameterA: 0, spikingParameterB: 0, spikingParameterC: 0, spikingParameterD: 0 };
      model.setNeuron(i, attrs);
    } else {
      const attrs: FiringRateNeuronAttrs = { bias: neuron.bias, tau: 0, gain: 0 };
      attrs.bias = 0;
      model.setNeuron(i, attrs);
    }
  }
  for (let i = spec.dims.numInputNeurons; i < spec.dims.numNeurons; i++) {
    const neuron = spec.neurons[i]!;
    if (spec.model === 'spiking') {
      const attrs: SpikingNeuronAttrs = spec.spikingParams === 1
        ? { bias: neuron.bias, spikingParameterA: neuron.sa, spikingParameterB: neuron.sb, spikingParameterC: neuron.sc, spikingParameterD: neuron.sd }
        : { bias: neuron.bias, spikingParameterA: 0.02, spikingParameterB: 0.2, spikingParameterC: -65, spikingParameterD: 6 };
      model.setNeuron(i, attrs, neuron.start);
    } else {
      const attrs: FiringRateNeuronAttrs = { bias: neuron.bias, tau: neuron.tau, gain: neuron.gain };
      model.setNeuron(i, attrs, neuron.start);
    }
    model.setNeuronEndSynapses(i, neuron.end);
  }
  for (let k = 0; k < spec.synapses.length; k++) {
    const s = spec.synapses[k]!;
    model.setSynapse(k, s.from, s.to, s.efficacy, s.lrate);
  }

  const functional = new StringTextFile();
  brain.startFunctional(functional, 42, 13);

  rng.srand48(spec.drandSeed);
  const activationBits: string[] = [];
  for (let step = 0; step < spec.inputs.length; step++) {
    model.setActivations(spec.inputs[step]!, 0, spec.inputs[step]!.length);
    brain.update(false);
    brain.writeFunctional(functional);

    const activations = brain.getActivations(0, spec.dims.numNeurons);
    for (let i = 0; i < spec.dims.numNeurons; i++) activationBits.push(doubleBits(activations[i]!));
  }
  brain.endFunctional(functional, 1.5);

  const synapseFile = new StringTextFile();
  brain.dumpSynapses(synapseFile, 42);

  const anatomyFile = new StringTextFile();
  brain.dumpAnatomical(anatomyFile, 42, 1.5);

  const efficacyBits: string[] = [];
  for (let k = 0; k < spec.dims.numSynapses; k++) efficacyBits.push(floatBits(model.getSynapse(k).efficacy));

  return {
    brain,
    model,
    function: functional.contents(),
    synapses: synapseFile.contents(),
    anatomy: anatomyFile.contents(),
    activationBits,
    efficacyBits,
    energyUse: brain.getEnergyUse(),
  };
}

function doubleBits(v: number): string {
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, v);
  return (BigInt(view.getUint32(0)) << 32n | BigInt(view.getUint32(4))).toString(16).padStart(16, '0');
}

/** Bits -> value, for the probe's raw-bit dump. */
function bitsToDouble(bits: string): number {
  const view = new DataView(new ArrayBuffer(8));
  view.setUint32(0, Number.parseInt(bits.slice(0, 8), 16));
  view.setUint32(4, Number.parseInt(bits.slice(8), 16));
  return view.getFloat64(0);
}

/**
 * Compare two runs value by value, by ULP distance, treating the sign separately (IEEE-754 is
 * sign-magnitude, so a bit-pattern subtraction would be meaningless across zero).
 */
function censusUlps(expected: readonly string[], got: readonly string[], width = 16): { total: number; exact: number; maxUlp: number; signMismatches: number } {
  let exact = 0;
  let maxUlp = 0;
  let signMismatches = 0;
  for (let i = 0; i < expected.length; i++) {
    const a = expected[i]!;
    const b = got[i]!;
    if (a === b) {
      exact += 1;
      continue;
    }
    const negativeA = Number.parseInt(a[0]!, 16) >= 8;
    const negativeB = Number.parseInt(b[0]!, 16) >= 8;
    if (negativeA !== negativeB) {
      signMismatches += 1;
      continue;
    }
    const ma = BigInt(`0x${a}`);
    const mb = BigInt(`0x${b}`);
    maxUlp = Math.max(maxUlp, Number(ma > mb ? ma - mb : mb - ma));
  }
  return { total: expected.length, exact, maxUlp, signMismatches };
}

/** Distance in representable doubles between two values given as 64-bit hex. */
function ulpDistance(a: string, b: string): number {
  const va = BigInt(`0x${a}`);
  const vb = BigInt(`0x${b}`);
  return Number(va > vb ? va - vb : vb - va);
}

function floatBits(v: number): string {
  const view = new DataView(new ArrayBuffer(4));
  view.setFloat32(0, v);
  return view.getUint32(0).toString(16).padStart(8, '0');
}

/** Bits -> `float`, for the probe's raw-bit dumps. */
function floatFromBits(bits: string): number {
  const view = new DataView(new ArrayBuffer(4));
  view.setUint32(0, Number.parseInt(bits, 16));
  return view.getFloat32(0);
}

// ---------------------------------------------------------------------------
// unit tests
// ---------------------------------------------------------------------------

describe('cformat: C printf', () => {
  it('implements %g the way C99 + glibc do', () => {
    expect(sprintfC('%g', 0)).toBe('0');
    expect(sprintfC('%g', -0)).toBe('-0');
    expect(sprintfC('%g', 1)).toBe('1');
    expect(sprintfC('%g', 0.821122)).toBe('0.821122');
    // 0.0078125 is exactly 2^-7: %g's own %f branch has precision P-1-X = 8 here, so all six
    // significant digits survive (this is *not* the %f tie case, which rounds to '0.007812')
    expect(sprintfC('%.6g', 0.0078125)).toBe('0.0078125');
    expect(sprintfC('%.1g', 0.0078125)).toBe('0.008');
    // a trailing zero after the significant digits is stripped, not printed
    expect(sprintfC('%.3g', 0.5)).toBe('0.5');
    expect(sprintfC('%.3g', 1000)).toBe('1e+03');
    expect(sprintfC('%.3g', 0.821122)).toBe('0.821');
    // exponent switch at -4 and at P
    expect(sprintfC('%g', 1e-5)).toBe('1e-05');
    expect(sprintfC('%g', 0.0001)).toBe('0.0001');
    expect(sprintfC('%g', 1e6)).toBe('1e+06');
    expect(sprintfC('%g', 123456.0)).toBe('123456');
    expect(sprintfC('%g', 0.000123456789)).toBe('0.000123457');
    expect(sprintfC('%+06.4f', 0.2493)).toBe('+0.2493');
    expect(sprintfC('%hd %hd %g %g\n', -8, 3, -0.5461, -1e-10)).toBe('-8 3 -0.5461 -1e-10\n');
    expect(sprintfC('%ld', 1369)).toBe('1369');
    expect(sprintfC('%.9g', f32(0.8))).toBe('0.800000012');
  });

  it('formats the brain dump shapes', () => {
    expect(sprintfC('brain %ld fitness=%g numneurons+1=%d maxWeight=%g maxBias=%g', 42, 0, 38, 8, 8)).toBe(
      'brain 42 fitness=0 numneurons+1=38 maxWeight=8 maxBias=8',
    );
    expect(sprintfC(' %d %d %d %ld', 37, 29, 8, 74)).toBe(' 37 29 8 74');
  });
});

describe('native math', () => {
  it('reproduces nint (the C macro, not Math.round)', () => {
    // `+0.499999999` (not 0.5) is deliberate: an exact half rounds toward zero
    expect(nint(0.5)).toBe(0);
    expect(nint(-0.5)).toBe(0);
    expect(nint(0.51)).toBe(1);
    expect(nint(-0.51)).toBe(-1);
    expect(nint(2.4)).toBe(2);
    expect(nint(-2.6)).toBe(-3);
    expect(nint(1.49999999999)).toBe(1);
    // and Math.round would answer 1 for both halves, which is the bug this guards
    expect(Math.round(0.5)).toBe(1);
  });

  it('narrows to short / int32 the way a C cast does', () => {
    expect(toShort(40000)).toBe(40000 - 65536);
    expect(toShort(-40000)).toBe(-40000 + 65536);
    expect(toShort(321)).toBe(321);
    expect(cRound(0.5)).toBe(1);
    expect(cRound(-0.5)).toBe(-1);
    expect(cRound(2.5)).toBe(3);
  });
});

describe('nerve activation buffers', () => {
  it('follows the model’s buffer swap through the shared record', () => {
    const rng = new GlibcDrand48();
    const cns = new ProbeCns(rng);
    const brain = new ProbeBrain(cns);
    cns.wire(brain);

    const nerve = cns.createNerve(NerveType.INPUT, 'Red');
    const model = new FiringRateModel(cns);
    const dims = new Dimensions();
    dims.numNeurons = 4;
    dims.numInputNeurons = 2;
    dims.numOutputNeurons = 1;
    dims.numSynapses = 0;
    brain.install(dims, model);
    model.init(dims, 0.5);

    nerve.configCount(2, 0);
    expect(nerve.get(0)).toBe(0.5);
    nerve.set(1, 0.25);
    expect(nerve.get(1)).toBe(0.25);
    expect(nerve.get(1, ActivationBuffer.SWAP)).toBe(0);

    // the model copies inputs through and swaps; the nerve must read the new buffer
    model.update(false);
    expect(nerve.get(0)).toBe(0.5);
    expect(nerve.getNeuronCount()).toBe(2);
  });

  it('rejects out-of-range access the way the native asserts do', () => {
    const cns = new ProbeCns(new GlibcDrand48());
    const nerve = cns.createNerve(NerveType.INPUT, 'Energy');
    nerve.configCount(0, 0);
    expect(nerve.get()).toBe(0); // native returns 0.0 for a zero-neuron nerve
    expect(() => nerve.setScalar(1)).not.toThrow();
    const single = cns.createNerve(NerveType.OUTPUT, 'Yaw');
    single.configCount(1, 0);
    expect(() => single.get(3)).toThrow();
  });
});

describe('synapse map ordering', () => {
  it('keeps std::map order by nonCulledId, not insertion order', () => {
    const map = new SynapseMap();
    const neurons = [0, 1, 2, 3].map((id) => {
      const n = new Neuron();
      n.nonCulledId = id;
      return n;
    });
    // insert out of order
    const order = [2, 0, 3, 1];
    for (const i of order) map.set(neurons[i]!, new Synapse(neurons[i]!, neurons[i]!));

    expect(map.size).toBe(4);
    expect(map.entriesInOrder().map((e) => e.key.nonCulledId)).toEqual([0, 1, 2, 3]);

    map.erase(neurons[1]!);
    expect(map.entriesInOrder().map((e) => e.key.nonCulledId)).toEqual([0, 2, 3]);
  });
});

describe('sheets geometry', () => {
  it('lays out neuron spacings, insets and absolute positions', () => {
    const model = new SheetsModel(new Vector3f(10, 20, 30), 1.0);
    const created: Neuron[] = [];
    const sheet = model.createSheet(
      'Red',
      -1,
      Sheet.Input,
      0,
      0.25,
      new Vector2f(0.5, 0.5),
      new Vector2f(0.5, 0.5),
      new Vector2i(2, 2),
      (n) => created.push(n),
    );

    expect(sheet.getNeuronCount().a).toBe(2);
    expect(created.length).toBe(4);
    expect(created[0]!.nonCulledId).toBe(0);
    expect(created[3]!.nonCulledId).toBe(3);
    // spacings 1/2 = 0.5, insets 0.25 -> sheet positions .25/.75
    expect(created[0]!.sheetPosition.a).toBeCloseTo(0.25, 6);
    expect(created[1]!.sheetPosition.b).toBeCloseTo(0.75, 6);
    // sheet position .75 scaled by the sheet size (.5) is .375, translated by
    // center - size/2 = .25 -> .625 in the unit square, then scaled by the model size
    expect(created[3]!.absPosition.x).toBeCloseTo(0.625 * 10, 5);
    expect(created[3]!.absPosition.y).toBeCloseTo(0.625 * 20, 5);
    expect(created[3]!.absPosition.z).toBeCloseTo(0.25 * 30, 5);
    expect(model.getSheet(0)).toBe(sheet);
  });

  it('trims a sheet that overflows the unit square', () => {
    const model = new SheetsModel(new Vector3f(1, 1, 1), 0.0);
    const created: Neuron[] = [];
    const sheet = model.createSheet('Internal', -1, Sheet.Internal, 0, 0.0, new Vector2f(0.9, 0.5), new Vector2f(0.4, 0.5), new Vector2i(1, 1), (n) =>
      created.push(n),
    );
    // center+size/2 = 1.1 > 1, so the sheet is shrunk by the overflow and re-centred
    // (center 0.9 - 0.05 = 0.85, size 0.4 - 0.1 = 0.3); a 1x1 sheet puts its single neuron
    // at the sheet's centre
    expect(sheet.getNeuronCount().a).toBe(1);
    expect(created[0]!.absPosition.x).toBeCloseTo(0.85, 5);
    expect(created[0]!.absPosition.y).toBeCloseTo(0.5, 5);
  });

  it('culls neurons that are not on an input→output path', () => {
    const model = new SheetsModel(new Vector3f(1, 1, 1), 0.0);
    const mk = (name: string, type: number): Neuron[] => {
      const made: Neuron[] = [];
      model.createSheet(name, -1, type, 0, 0.0, new Vector2f(0.5, 0.5), new Vector2f(1, 1), new Vector2i(1, 1), (n) => made.push(n));
      return made;
    };
    const input = mk('Red', Sheet.Input)[0]!;
    const middle = mk('Internal', Sheet.Internal)[0]!;
    const output = mk('Eat', Sheet.Output)[0]!;
    const orphan = mk('InternalOrphan', Sheet.Internal)[0]!;

    const wire = (from: Neuron, to: Neuron): void => {
      const syn = new Synapse(from, to);
      from.synapsesOut.set(to, syn);
      to.synapsesIn.set(from, syn);
    };
    wire(input, middle);
    wire(middle, output);

    model.cull();

    // native cull order is input sheets, then output sheets, then internal sheets - so the
    // flattened id order is input, output, internal, not construction order
    expect(model.getNeurons().map((n) => n.nonCulledId)).toEqual([input.nonCulledId, output.nonCulledId, middle.nonCulledId]);
    expect(model.getNeurons()[1]!.id).toBe(1);
    expect(middle.id).toBe(2);
    // the culled neuron's edges are deleted in both directions
    expect(orphan.synapsesIn.size).toBe(0);
    expect(orphan.synapsesOut.size).toBe(0);
  });

  it('computes the synapse probability the way the native formula does', () => {
    const model = new SheetsModel(new Vector3f(1, 1, 1), 2.0);
    expect(model.getProbabilitySynapse(0)).toBe(f32(0.5 * 1));
    expect(model.getProbabilitySynapse(1)).toBe(f32(0.5 * Math.exp(-0.5)));
    const zero = new SheetsModel(new Vector3f(1, 1, 1), 0.0);
    expect(zero.getProbabilitySynapse(3)).toBe(1.0);
  });
});

// ---------------------------------------------------------------------------
// differential parity against the oracle's own code
// ---------------------------------------------------------------------------

const differential = haveNativeTree ? describe : describe.skip;

differential('drand48 stand-in', () => {
  it('matches the oracle’s glibc drand48 draws', () => {
    const spec = readSpec('spiking');
    const expected = readFileSync(join(PROBE_DIR, `summary.${spec.model}.txt`), 'utf8')
      .split('\n')
      .find((l) => l.startsWith('drand48'))!
      .split(' ')
      .slice(1)
      .map(Number);

    const rng = new GlibcDrand48();
    rng.srand48(spec.drandSeed);
    for (let i = 0; i < expected.length; i++) {
      expect(rng.drand48()).toBe(expected[i]);
    }
  });
});

for (const variant of VARIANTS) {
  differential(`native parity: ${variant}`, () => {
    let spec: Spec;
    let port: ReturnType<typeof runPort>;
    let expectedFunction: string;
    let expectedSynapses: string;
    let expectedAnatomy: string;
    let expectedBits: string[];
    let expectedEfficacyBits: string[];

    beforeAll(() => {
      spec = readSpec(variant);
      expectedFunction = readFileSync(join(PROBE_DIR, `function.${variant}.txt`), 'utf8');
      expectedSynapses = readFileSync(join(PROBE_DIR, `synapses.${variant}.txt`), 'utf8');
      expectedAnatomy = readFileSync(join(PROBE_DIR, `anatomy.${variant}.txt`), 'utf8');

      const summary = readFileSync(join(PROBE_DIR, `summary.${variant}.txt`), 'utf8').split('\n');
      expectedBits = summary.filter((l) => l.startsWith('activations ')).map((l) => l.split(' ')[3]!);
      expectedEfficacyBits = summary.filter((l) => l.startsWith('efficacy ')).map((l) => l.split(' ')[2]!);

      port = runPort(spec);
    });

    it('matches the model geometry the native build reports', () => {
      expect(spec.dims.numNeurons).toBeGreaterThan(0);
      expect(port.model.getActivations(0, spec.dims.numNeurons).length).toBe(spec.dims.numNeurons);
      expect(expectedBits.length).toBe(spec.dims.numNeurons * spec.inputs.length);
      expect(expectedEfficacyBits.length).toBe(spec.dims.numSynapses);
    });

    it('writes byte-identical functional recordings (run/brain/function/**)', () => {
      expect(port.function).toBe(expectedFunction);
    });

    it('writes byte-identical synapse dumps after learning (run/brain/synapses/**)', () => {
      expect(port.synapses).toBe(expectedSynapses);
    });

    it('writes byte-identical anatomy dumps (run/brain/anatomy/**)', () => {
      expect(port.anatomy).toBe(expectedAnatomy);
    });

    /**
     * The activations are compared as a *census*: exact, on every value, for all three
     * variants.
     *
     * The historical residual here (a 1-ulp drift that grew to 13 ulp over six steps) was
     * **closed by `t_da2ab201`**, and it was not the libm: it was clang's `-ffp-contract=on`.
     * The shipped `FiringRateModel::update` accumulates with `fmadd d0, d1, d2, d0` in both
     * neuron loops (`0x5e704`, `0x5e7c8`), mixes tau/gain with `fmadd d0, d10, d11, d0`
     * (`0x5e744`, `0x5e804`) and learns with `fmadd d17, d18, d19, d17` (`0x5e8a8`);
     * `SpikingModel::update` does the same in its accumulation (`0x678cc`), its Izhikevich
     * voltage (`0x67964`, `0x67988`) and recovery (`0x67990-0x67994`) and its smoothed firing
     * rate (`0x67d80`). A rounds-per-operation transcription is ~1 ulp out per site and the
     * recurrence amplifies it — which is exactly the drift the lane used to carry, and exactly
     * what the `Yaw` nerve's ~1e-13 relative residual in the `dyn` growers worlds was.
     * `nativeMath.ts`'s `fma64` is the binary64 FMA the transcription now uses, pinned against
     * hardware on ~40,000 rows by `describe('fma64 (native differential)')` below.
     *
     * The assertions are equality: a missed `fround`, a reordered operand, a dropped
     * contraction or a wrong draw count moves at least one of these 294 bits-off comparisons,
     * so a regression fails here instead of quietly moving a nerve.
     */
    it('matches every activation bit-for-bit', () => {
      const census = censusUlps(expectedBits, port.activationBits);
      // eslint-disable-next-line no-console
      console.log(`activation census ${variant}: ${census.exact}/${census.total} bit-exact, max ${census.maxUlp} ulp`);
      expect(census.total).toBe(spec.dims.numNeurons * spec.inputs.length);
      expect(census.signMismatches).toBe(0);
      expect(census.maxUlp).toBe(0);
      expect(census.exact).toBe(census.total);
    });

    it('matches every learned efficacy bit-for-bit', () => {
      const census = censusUlps(expectedEfficacyBits, port.efficacyBits);
      // eslint-disable-next-line no-console
      console.log(`efficacy census ${variant}: ${census.exact}/${census.total} bit-exact, max ${census.maxUlp} ulp`);
      expect(census.signMismatches).toBe(0);
      expect(census.maxUlp).toBe(0);
      expect(census.exact).toBe(census.total);
    });
  });
}

// ---------------------------------------------------------------------------
// the learning rule's clamp chain — PARITY.md's L6 mutation table's last survivor
//
// `FiringRateModel::update` / `SpikingModel::update` decay an efficacy back toward
// `0.5*maxWeight` once it is above it (0x5e8bc-0x5e8cc / 0x67cb0-0x67cc4), and the shipped code
// computes that chain in `float`, one rounding per operation, with the first product fused
// (`fmadd s16, s0, s6, s18`). The port transcribes exactly that; reverting it to the pre-sweep
// binary64 form
//
//     scaled = 1.0 - (oneMinusDecay * (Math.abs(efficacy) - halfMaxWeight)) / halfMaxWeight;
//     efficacy = f32(efficacy * scaled);
//
// used to pass in every suite, because nothing drove the site: the `models` spec's efficacies
// are all inside the clamp bound, and the hand-built drive of `t_2a625bd5` ran the model with
// the learning block gated *off* (`Brain::config.enableLearning` is derived from `learningMode`
// by `Brain::processWorldfile`, not by the model), so its efficacies came back exactly as set.
//
// `brainprobe learnclamp` now builds the input that is reachable from `update()` alone —
// constructed `|efficacy|` inside `(0.5*maxWeight, maxWeight]`, one step through the model's own
// `set_synapse -> update -> get_synapse` round trip — and writes, per synapse, the pre-clamp
// value, the value the *shipped* model stored, and the value the pre-change form would store.
// The pin below is that comparison, per bit, for all three families.
// ---------------------------------------------------------------------------

const LEARNCLAMP_TAGS = ['clampfiringrate', 'clampfiringrate2', 'clampspiking'] as const;

interface LearnClampRow {
  k: number;
  before: string;
  native: string;
  pre: string;
  differs: boolean;
}

function readLearnClamp(tag: string): {
  rows: LearnClampRow[];
  candidates: number;
  clamped: number;
  differs: number;
  identical: number;
  currentMismatches: number;
} {
  const out = { rows: [] as LearnClampRow[], candidates: 0, clamped: 0, differs: 0, identical: 0, currentMismatches: 0 };
  for (const line of readFileSync(join(PROBE_DIR, `learnclamp.${tag}.txt`), 'utf8').split('\n')) {
    if (line.startsWith('learnclamp ')) {
      const f = line.split(' ');
      out.rows.push({ k: Number(f[1]), before: f[2]!, native: f[3]!, pre: f[4]!, differs: f[5] === 'differs' });
    } else if (line.startsWith('summary ')) {
      const f = line.split(' ');
      out.candidates = Number(f[2]);
      out.clamped = Number(f[4]);
      out.differs = Number(f[6]);
      out.identical = Number(f[8]);
      out.currentMismatches = Number(f[10]);
    }
  }
  return out;
}

/**
 * The learning step with the clamp chain reverted to the pre-sweep binary64 form — the mutation
 * the table names, transcribed here from `git show HEAD:src/model/brain/core/firingRateModel.ts`
 * and `spikingModel.ts`. Every intermediate is its own expression, exactly as the pre-change code
 * wrote them, so the rounding sequence is the mutated one (a single expression would round once).
 */
function learningStepPreChange(args: {
  spiking: boolean;
  efficacyBefore: number;
  lrate: number;
  aTo: number;
  aFrom: number;
  deltaAfterDecay: number;
  maxWeight: number;
  decayRate: number;
}): number {
  const { spiking, efficacyBefore, lrate, aTo, aFrom, deltaAfterDecay, maxWeight, decayRate } = args;
  const halfMaxWeight = f32(0.5 * maxWeight);
  const oneMinusDecay = f32(1.0 - decayRate);

  let efficacy: number;
  if (spiking) {
    // pre-change: `syn.efficacy ± (0.01 + syn.delta * learningrate)`, all binary64, narrowed once
    const increment = 0.01 + deltaAfterDecay * lrate;
    efficacy = efficacyBefore >= 0 ? f32(efficacyBefore + increment) : f32(efficacyBefore - increment);
  } else {
    // pre-change: `syn.efficacy + learningrate * (aTo-0.5) * (aFrom-0.5)`, binary64, narrowed once
    efficacy = f32(efficacyBefore + lrate * (aTo - 0.5) * (aFrom - 0.5));
  }

  if (Math.abs(efficacy) > halfMaxWeight) {
    const scaled = 1.0 - (oneMinusDecay * (Math.abs(efficacy) - halfMaxWeight)) / halfMaxWeight;
    efficacy = f32(efficacy * scaled);
    if (efficacy > maxWeight) efficacy = maxWeight;
    else if (efficacy < -maxWeight) efficacy = -maxWeight;
  } else {
    if (lrate >= 0.0) efficacy = Math.max(0.0, efficacy);
    if (lrate < 0.0) efficacy = Math.min(f32(-1.e-10), efficacy);
  }
  return efficacy;
}

/** The port's own pre-clamp value for one row, from the state the port's learning loop reads. */
function portPreClampValue(args: {
  spiking: boolean;
  efficacyBefore: number;
  lrate: number;
  aTo: number;
  aFrom: number;
  deltaAfterDecay: number;
}): number {
  if (args.spiking) {
    const increment = 0.01 + f32(args.deltaAfterDecay * args.lrate);
    return args.efficacyBefore >= 0
      ? f32(args.efficacyBefore + increment)
      : f32(args.efficacyBefore - increment);
  }
  const delta = (args.aTo - 0.5) * args.lrate;
  return f32(fma64(delta, args.aFrom - 0.5, args.efficacyBefore));
}

for (const tag of LEARNCLAMP_TAGS) {
  differential(`native parity: ${tag} (the learning rule's clamp chain)`, () => {
    let spec: Spec;
    let rows: LearnClampRow[];
    let counts: ReturnType<typeof readLearnClamp>;
    let port: ReturnType<typeof runPort>;
    let spiking: boolean;

    beforeAll(() => {
      spec = readSpec(tag);
      counts = readLearnClamp(tag);
      rows = counts.rows;
      spiking = spec.model === 'spiking';
      port = runPort(spec);
    });

    it('drives a family the clamp fires on, and that is not vacuous', () => {
      expect(rows.length).toBe(spec.dims.numSynapses);
      expect(counts.candidates).toBe(spec.dims.numSynapses);
      // every constructed magnitude is inside (0.5*maxWeight, maxWeight): the clamp fires on all
      // but the exact-threshold rows (the four `band = 0` magnitudes), and neither form saturates
      expect(counts.clamped).toBeGreaterThanOrEqual(spec.dims.numSynapses - 8);
      expect(counts.differs + counts.identical).toBe(counts.candidates);
      // the probe's own transcription of the *shipped* chain, compiled by the native toolchain,
      // agrees with the shipped model on every row — a wrong transcription would show up here
      // rather than as a passing pin
      expect(counts.currentMismatches).toBe(0);
      expect(counts.differs).toBeGreaterThan(0);
      for (const row of rows) expect(row.differs).toBe(row.pre !== row.native);
    });

    it('matches the shipped model bit-for-bit on every driven synapse', () => {
      const mismatches = rows
        .filter((row) => floatBits(port.model.getSynapse(row.k).efficacy) !== row.native)
        .map((row) => `synapse ${row.k}: native 0x${row.native}, port 0x${floatBits(port.model.getSynapse(row.k).efficacy)}`);
      expect(mismatches.slice(0, 8)).toEqual([]);
    });

    it('reads the same pre-clamp value the shipped model did, on every row', () => {
      const activations = port.brain.getActivations(0, spec.dims.numNeurons);
      const rawSynapses = (port.model as unknown as { rawState(): { synapse: Array<{ delta?: number }> } }).rawState().synapse;
      const mismatches: string[] = [];
      for (const row of rows) {
        const synapse = spec.synapses[row.k]!;
        const value = portPreClampValue({
          spiking,
          efficacyBefore: synapse.efficacy,
          lrate: synapse.lrate,
          aTo: activations[synapse.to]!,
          aFrom: spec.inputs[0]![synapse.from]!,
          deltaAfterDecay: rawSynapses[row.k]!.delta ?? 0,
        });
        if (floatBits(value) !== row.before) mismatches.push(`synapse ${row.k}: probe 0x${row.before}, port 0x${floatBits(value)}`);
      }
      expect(mismatches.slice(0, 8)).toEqual([]);
    });

    it('is the mutation the table names: the pre-change form disagrees on every `differs` row, and the port follows the shipped model', () => {
      const activations = port.brain.getActivations(0, spec.dims.numNeurons);
      const rawSynapses = (port.model as unknown as { rawState(): { synapse: Array<{ delta?: number }> } }).rawState().synapse;
      const transcription: string[] = [];
      const missed: string[] = [];
      let mutationDiffers = 0;
      for (const row of rows) {
        const synapse = spec.synapses[row.k]!;
        const mutated = learningStepPreChange({
          spiking,
          efficacyBefore: synapse.efficacy,
          lrate: synapse.lrate,
          aTo: activations[synapse.to]!,
          aFrom: spec.inputs[0]![synapse.from]!,
          deltaAfterDecay: rawSynapses[row.k]!.delta ?? 0,
          maxWeight: spec.maxWeight,
          decayRate: spec.decayRate,
        });
        // (a) the probe's `pre` column *is* this mutation, bit for bit
        if (floatBits(mutated) !== row.pre) {
          transcription.push(`synapse ${row.k}: mutation 0x${floatBits(mutated)}, probe 0x${row.pre}`);
        }
        // (b) the rows the probe calls `differs` are exactly the rows the mutation moves
        const moved = floatBits(mutated) !== row.native;
        if (moved !== row.differs) missed.push(`synapse ${row.k}: mutated 0x${floatBits(mutated)}, native 0x${row.native}, probe verdict ${row.differs}`);
        if (moved) mutationDiffers += 1;
      }
      expect(missed.slice(0, 8)).toEqual([]);
      expect(transcription.slice(0, 8)).toEqual([]);
      expect(mutationDiffers).toBe(counts.differs);
      expect(mutationDiffers).toBeGreaterThan(0);
      // eslint-disable-next-line no-console
      console.log(`learnclamp ${tag}: ${rows.length} driven synapses, ${counts.clamped} clamped, ${mutationDiffers} moved by the pre-change chain`);
    });

    it('runs the learning block only with `enableLearning` set — the unclamped hand drive, reproduced', () => {
      // the drive `t_2a625bd5` wrote and removed: it set an efficacy above the clamp, stepped the
      // model, and got the value back unchanged. That is this — the learning block is gated
      // (`brainConfig.enableLearning && !brain.isFrozen()`) and the model never derives the flag
      // (`processWorldfile` does), so the drive's round trip was fine and the *gate* was the miss.
      const off = runPort({ ...spec, enableLearning: false });
      const unchanged = spec.synapses.filter(
        (synapse, k) => floatBits(off.model.getSynapse(k).efficacy) === floatBits(synapse.efficacy),
      );
      expect(unchanged.length).toBe(spec.dims.numSynapses);
      // and with the gate on, the same brain's efficacies move (the pin above measures how)
      const moved = rows.filter((row) => floatBits(port.model.getSynapse(row.k).efficacy) !== floatBits(spec.synapses[row.k]!.efficacy));
      expect(moved.length).toBeGreaterThan(0);
    });
  });
}

// ---------------------------------------------------------------------------
// the learning step's fused delta (`0x5e890-0x5e8ac`)
// ---------------------------------------------------------------------------
//
// `learnclamp`'s three families pin the clamp *chain*, and by construction they cannot pin the
// contraction that forms its input: their delta is `lrate * (a_to-0.5) * (a_from-0.5)` over live
// activations, and the fused and unfused deltas then differ by at most half an ulp of a product
// bounded by `maxlrate * 0.5 * 0.5` — a f32 store at `|e| ≈ 4` cannot see that. Measured on this
// tree: reverting the delta line alone left the whole suite green, 0 of the clamp family's 3,072
// driven rows separating it.
//
// `brainprobe learndelta` makes the delta exact and the product free instead:
//
//   * the destination neuron is saturated — `bias` alone holds `logistic(.)` at exactly 1.0 — so
//     `a_to - 0.5` is exactly 0.5 and the delta is the exact double `0.5 * lrate`;
//   * each row drives its own input neuron, whose activation the spec's `input` line carries at
//     full double precision, so `db = a_from - 0.5` is a free double;
//   * `lrate` is small enough that one ulp of the input's own grid moves the product by about one
//     ulp of itself, which lets the probe walk `db` onto the f32 midpoint above the stored
//     efficacy — where the fused `fmadd d17, d18, d19, d17` and the round-product-then-sum form
//     narrow to *different* floats.
//
// The mode emits only rows that separate and exits non-zero when it finds none, so this family is
// the contraction's own witness: every row here moves when the delta line is reverted.
// ---------------------------------------------------------------------------

interface LearnDeltaRow {
  k: number;
  fused: string;
  native: string;
  pre: string;
  differs: boolean;
}

function readLearnDelta(): {
  rows: LearnDeltaRow[];
  rowsCount: number;
  differs: number;
  same: number;
  saturated: number;
  currentMismatches: number;
} {
  const out = { rows: [] as LearnDeltaRow[], rowsCount: 0, differs: 0, same: 0, saturated: 0, currentMismatches: 0 };
  for (const line of readFileSync(join(PROBE_DIR, 'learndelta.txt'), 'utf8').split('\n')) {
    if (line.startsWith('learndelta ')) {
      const f = line.split(' ');
      out.rows.push({ k: Number(f[1]), fused: f[2]!, native: f[3]!, pre: f[4]!, differs: f[5] === 'differs' });
    } else if (line.startsWith('summary ')) {
      const f = line.split(' ');
      out.rowsCount = Number(f[2]);
      out.differs = Number(f[4]);
      out.same = Number(f[6]);
      out.saturated = Number(f[8]);
      out.currentMismatches = Number(f[10]);
    }
  }
  return out;
}

differential("native parity: learndelta (the learning rule's fused delta)", () => {
  let spec: Spec;
  let rows: LearnDeltaRow[];
  let counts: ReturnType<typeof readLearnDelta>;
  let port: ReturnType<typeof runPort>;

  beforeAll(() => {
    spec = readSpec('learndelta');
    counts = readLearnDelta();
    rows = counts.rows;
    port = runPort(spec);
  });

  it('drives a family whose every row separates the fused delta, and that is not vacuous', () => {
    expect(rows.length).toBe(counts.rowsCount);
    expect(rows.length).toBe(spec.dims.numSynapses);
    expect(rows.length).toBeGreaterThanOrEqual(8);
    // one input neuron per row: each `db` is its own full-precision double
    expect(spec.dims.numNeurons).toBe(2 * rows.length);
    // the mode emits only rows the contraction moves, so a family that lost its teeth — or a
    // build where the probe's own transcription re-fused the two forms — shows up here
    expect(counts.differs).toBe(rows.length);
    expect(counts.same).toBe(0);
    expect(counts.differs + counts.same).toBe(rows.length);
    // the construction's invariant, measured on the shipped model: every destination activation
    // is exactly 1.0, which is what makes the delta the exact double `0.5 * lrate`
    expect(counts.saturated).toBe(rows.length);
    // and the probe's transcription of the *shipped* arithmetic (compiled by the native
    // toolchain) agrees with the shipped model on every row — a wrong transcription would show
    // up here rather than as a passing pin
    expect(counts.currentMismatches).toBe(0);
    for (const row of rows) expect(row.differs).toBe(row.pre !== row.native);
  });

  it('matches the shipped model bit-for-bit on every driven synapse', () => {
    const mismatches = rows
      .filter((row) => floatBits(port.model.getSynapse(row.k).efficacy) !== row.native)
      .map((row) => `synapse ${row.k}: native 0x${row.native}, port 0x${floatBits(port.model.getSynapse(row.k).efficacy)}`);
    expect(mismatches.slice(0, 8)).toEqual([]);
    // eslint-disable-next-line no-console
    console.log(`learndelta: ${rows.length} driven rows, all ${counts.differs} narrowed differently by the two forms`);
  });

  it('is the mutation the table names: the round-product delta disagrees on every row, and the port follows the shipped model', () => {
    const activations = port.brain.getActivations(0, spec.dims.numNeurons);
    const mismatch: string[] = [];
    const missed: string[] = [];
    let separated = 0;
    for (const row of rows) {
      const synapse = spec.synapses[row.k]!;
      const aFrom = spec.inputs[0]![synapse.from]!;
      const aTo = activations[synapse.to]!;
      // the construction: the destination is saturated, so the delta is exactly `0.5 * lrate`
      if (aTo !== 1.0) mismatch.push(`synapse ${row.k}: destination activation ${aTo} is not exactly 1.0`);
      // (a) the port's own pre-clamp value is the probe's `fused` column, bit for bit — the fused
      // product+add the shipped `fmadd` at 0x5e8a8 performs
      const fused = portPreClampValue({
        spiking: false,
        efficacyBefore: synapse.efficacy,
        lrate: synapse.lrate,
        aTo,
        aFrom,
        deltaAfterDecay: 0,
      });
      if (floatBits(fused) !== row.fused) {
        mismatch.push(`synapse ${row.k}: port fused 0x${floatBits(fused)}, probe 0x${row.fused}`);
      }
      // (b) the mutation — `f32(syn.efficacy + learningrate * (a_to-0.5) * (a_from-0.5))`, the
      // product rounded before the add — is the probe's `pre` column, and it moves *every* row
      const mutated = learningStepPreChange({
        spiking: false,
        efficacyBefore: synapse.efficacy,
        lrate: synapse.lrate,
        aTo,
        aFrom,
        deltaAfterDecay: 0,
        maxWeight: spec.maxWeight,
        decayRate: spec.decayRate,
      });
      if (floatBits(mutated) !== row.pre) {
        mismatch.push(`synapse ${row.k}: mutation 0x${floatBits(mutated)}, probe 0x${row.pre}`);
      }
      if (floatBits(mutated) !== row.native) separated += 1;
      else missed.push(`synapse ${row.k}: the round-product delta leaves 0x${row.native} alone`);
    }
    expect(mismatch.slice(0, 8)).toEqual([]);
    expect(missed.slice(0, 8)).toEqual([]);
    expect(separated).toBe(rows.length);
  });
});

differential('native parity: printf formatting', () => {
  it('matches clang/glibc %g, %G, %f, %+06.4f, %hd and %ld on the model’s own values', () => {
    const lines = readFileSync(join(PROBE_DIR, 'format.txt'), 'utf8').split('\n').filter((l) => l.length > 0);
    const spec = readSpec('firingrate');
    const port = runPort(spec);

    // the extreme-magnitude vectors the probe writes (same order as brainprobe.cc)
    const vectors = [
      0.0, -0.0, 0.5, 1.0, -1.0, 0.821122, 0.0078125, 0.0078124, 1e-5, 1e-4, 9.999999e-5,
      0.000123456789, 123456.789, 999999.5, 999999.4, 0.9999995, 0.99999949, 1.5e-7,
      1.0 / 3.0, 2.0 / 3.0, -2.5e-8, 1234567.0, 1e20, 1e-20, 3.14159265358979,
      0.09999999999999999, 1.0000000000000002, 2147483647.0, -2147483648.0, 4294967296.0,
      0.1, 0.2, 0.30000000000000004, 1e6, 99999.95, 0.049999999999, 4.9999995,
    ];

    let checked = 0;
    for (const line of lines) {
      const label = line.split(' ')[0]!;
      let value: number;
      if (label.startsWith('v')) {
        value = vectors[Number(label.slice(1))]!;
      } else if (label.startsWith('a')) {
        value = port.brain.getActivations(Number(label.slice(1)), 1)[0]!;
      } else if (label.startsWith('s') && label.endsWith('e')) {
        value = port.model.getSynapse(Number(label.slice(1, -1))).efficacy;
      } else if (label.startsWith('s') && label.endsWith('l')) {
        value = port.model.getSynapse(Number(label.slice(1, -1))).lrate;
      } else {
        throw new Error(`unknown format label ${label}`);
      }

      const withInts = label.startsWith('v') ? Math.abs(value) < 1e9 : true;
      const expected =
        `g[${sprintfC('%.6g', value)}] G[${sprintfC('%.6G', value)}] g3[${sprintfC('%.3g', value)}] ` +
        `g10[${sprintfC('%.10g', value)}] f[${sprintfC('%f', value)}] plus06f[${sprintfC('%+06.4f', value)}]` +
        (withInts ? ` d[${sprintfC('%d', value)}] hd[${sprintfC('%hd', value)}] ld[${sprintfC('%ld', value)}]` : '');
      expect(`${label} ${expected}`).toBe(line);
      checked += 1;
    }

    expect(checked).toBeGreaterThan(40);
  });
});

// ---------------------------------------------------------------------------
// the groups grow arithmetic — the expressions `GroupsBrain::growSynapses` is built from
// (PORT_SPEC rule 3: the port has to reproduce the C *operand types*, not just the formula)
// ---------------------------------------------------------------------------

describe('groups grow arithmetic', () => {
  it('rounds `nsynjiperneur + remainder` to FLOAT before the double `1.e-5` promotes it', () => {
    // the case that exposed the all-double reading: 1.0f plus a remainder a hair below the
    // -1e-5 that would cancel the literal. `float( 1.0f + rem )` rounds *down* to
    // 0.99998998641967773, so the double 1.e-5 lifts the sum to just under 1 and `short(...)`
    // truncates to 0; the all-double sum is 1.00000000036 and truncates to 1
    const nsyn = f32(1.0);
    const rem = f32(-9.999636e-6);
    expect(f32(nsyn + rem)).toBe(0.9999899864196777);
    expect(synapseCountNew(nsyn, rem)).toBe(0);
    expect(toShort(nsyn + rem + 1.e-5)).toBe(1); // the arithmetic this replaced
  });

  it('truncates `synapseCount_new` toward zero (not floor) and wraps through short', () => {
    expect(synapseCountNew(f32(1.5), f32(-2.4))).toBe(0); // -0.9 truncates to 0, floor gives -1
    expect(synapseCountNew(f32(0.0), f32(0.0))).toBe(0);
    expect(synapseCountNew(f32(40000.0), f32(0.0))).toBe(40000 - 65536);
  });

  it('keeps the remainder accumulator in float', () => {
    const nsyn = f32(1.0 / 3.0);
    const scn = 0;
    expect(remainderUpdate(0, nsyn, scn)).toBe(f32(1.0 / 3.0));
    // the `nsynjiperneur - synapseCount_new` difference is computed in float too
    expect(remainderUpdate(f32(0.5), f32(7.0), 3)).toBe(f32(0.5 + f32(7.0 - 3)));
  });

  it('clamps the base local index with max<short>/min<short>', () => {
    // 0/4*8 - 6*0.5 = -3 -> clamped up to 0
    expect(neuronLocalIndexFromBase(0, 4, 8, 6)).toBe(0);
    // (3/4)*8 - 2*0.5 = 5
    expect(neuronLocalIndexFromBase(3, 4, 8, 2)).toBe(5);
    // the upper clamp is `neuronCount_from - synapseCount_new`, narrowed through short
    expect(neuronLocalIndexFromBase(3, 4, 4, 2)).toBe(2);
  });

  it('computes `td_fromto_abs` in float for all three native branches', () => {
    expect(tdFromToAbs(0.25, TdAbsBranch.UNMIRRORED)).toBe(f32(0.25));
    expect(tdFromToAbs(0.25, TdAbsBranch.MIRRORED_LOW)).toBe(0.5);
    expect(tdFromToAbs(0.75, TdAbsBranch.MIRRORED_HIGH)).toBe(0.5);
    // the result is always a float store, never a double
    const wide = f32(1.0 / 3.0);
    expect(tdFromToAbs(wide, TdAbsBranch.MIRRORED_HIGH)).toBe(f32(f32(1 - wide) * 2));
  });

  it('narrows the distortion index through `nint` and short, consuming two draws', () => {
    // `nint(a)` mentions `a` twice, and in the walk `a` holds a `range()` *call*, so the compiled
    // walk consumes TWO draws per passing connection: the first feeds the sum, the second only
    // its sign. `distortionIndex( drawForSum, drawForSign, td_fromto_abs, neuronCount_from )`.
    //
    // `nint(0.5)` is 0 — an exact half rounds toward zero (the macro adds 0.499999999)
    expect(distortionIndex(0.5, 0.5, 1, 1)).toBe(0);
    expect(Math.round(0.5)).toBe(1);
    expect(distortionIndex(0.49, 0.49, 1, 2)).toBe(1); // nint(0.98) = 1
    expect(distortionIndex(-0.5, -0.5, 1, 1)).toBe(0);
    // the sign test reads the *second* draw, the sum the first: -0.4*1*3 = -1.2, and the epsilon
    // the macro picks is what decides between trunc(-0.7) = 0 and trunc(-1.7) = -1
    expect(distortionIndex(-0.4, 0.5, 1, 3)).toBe(0);
    expect(distortionIndex(-0.4, -0.5, 1, 3)).toBe(-1);
    // the first draw alone drives the magnitude
    expect(distortionIndex(-0.4, 0.5, 1, 3)).toBe(distortionIndex(-0.4, 0.25, 1, 3));
    expect(distortionIndex(0.5, 0.5, 1, 100000)).toBe(50000 - 65536); // short(...) wraps
  });

  it('stores `stdev` as a float', () => {
    const gene = f32(1.0 / 3.0);
    const stdev = stdevOf(gene, 7.0);
    // f32(1/3) * 7 = 2.3333334028720856, rounded to the float store — *not* the double 7/3
    expect(stdev).toBe(f32(f32(1.0 / 3.0) * 7.0));
    expect(stdev).toBe(2.3333334922790527);
    expect(f32(stdev)).toBe(stdev); // i.e. the store is a float store
  });

  it('evaluates the energy formula as `a * float(n) / float(m)` — product before division', () => {
    // native (GroupsBrain.cc:616-617) is left to right; the pre-review grouping `a * (n / m)`
    // rounds to a *different float* as soon as the denominator is not a power of two
    expect(energyUseOf(12.5, 1234, 1500, 0, 0, 1024)).toBe(10.283333778381348);
    expect(f32(12.5 * f32(1234 / 1500))).toBe(10.283332824707031);
    expect(energyUseOf(0, 0, 32, 0, 0, 1024)).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// telemetry for the lane report
// ---------------------------------------------------------------------------

describe('spiking model constants', () => {
  it('keeps the native brain-step geometry', () => {
    expect(BrainStepsPerWorldStep).toBe(50);
    expect(f32(1.0 - 0.8)).toBeCloseTo(0.2, 6);
    expect(new Nerve(NerveType.INPUT, 'x').getNeuronCount()).toBe(0);
  });

  it('exposes a text file with the same bytes as its latin-1 form', () => {
    const file = new StringTextFile();
    const sink: BrainTextFile = file;
    sink.printf('brain %ld fitness=%g\n', 7, 0.5);
    expect(file.contents()).toBe('brain 7 fitness=0.5\n');
    expect(Array.from(file.bytes())).toEqual([...'brain 7 fitness=0.5\n'].map((c) => c.charCodeAt(0)));
  });
});

// ---------------------------------------------------------------------------
// libm census (PORT_SPEC rule 3)
// ---------------------------------------------------------------------------

differential('libm census', () => {
  it('measures the port’s exp/logistic against the oracle’s libm', () => {
    const lines = readFileSync(join(PROBE_DIR, 'math.txt'), 'utf8').split('\n').filter((l) => l.length > 0);

    let logisticTotal = 0;
    let logisticExact = 0;
    let logisticMaxUlp = 0;
    let expTotal = 0;
    let expExact = 0;
    let expMaxUlp = 0;
    // the same probe replayed through V8's `Math.exp`, i.e. the drift this lane used to
    // carry: it stays in the measurement so the numbers in PARITY.md can be re-derived, and
    // so "the port is not V8" is asserted rather than remembered
    let v8ExpExact = 0;

    for (const line of lines) {
      const f = line.split(' ');
      if (f[0] === 'logistic') {
        const x = bitsToDouble(f[2]!);
        const expected = f[3]!;
        const got = doubleBits(logistic(x, Number(f[1])));
        logisticTotal += 1;
        if (got === expected) logisticExact += 1;
        else logisticMaxUlp = Math.max(logisticMaxUlp, ulpDistance(expected, got));
      } else {
        const x = bitsToDouble(f[1]!);
        const expected = f[2]!;
        const got = doubleBits(exp(x));
        expTotal += 1;
        if (got === expected) expExact += 1;
        else expMaxUlp = Math.max(expMaxUlp, ulpDistance(expected, got));
        if (doubleBits(Math.exp(x)) === expected) v8ExpExact += 1;
      }
    }

    // `exp` is lane L1's transcription of the oracle's libm (W1d follow-up): it is exact on
    // this probe and on its own 8,261-value corpus (`tests/rng.test.ts`), while `Math.exp` is
    // not -- the drift this lane's PARITY row used to quote. The assertions are equality, so a
    // future rewrite that reaches for `Math.exp` again fails here instead of quietly moving
    // the activation bits.
    console.log(
      `libm census: logistic ${logisticExact}/${logisticTotal} bit-exact (max ${logisticMaxUlp} ulp), ` +
        `exp ${expExact}/${expTotal} bit-exact (max ${expMaxUlp} ulp) ` +
        `[Math.exp ${v8ExpExact}/${expTotal}]`,
    );
    expect(logisticTotal).toBe(2048);
    expect(expTotal).toBe(512);
    expect(logisticExact).toBe(logisticTotal);
    expect(expExact).toBe(expTotal);
    expect(expMaxUlp).toBe(0);
    expect(v8ExpExact).toBeLessThan(expTotal);
  });
});

// ---------------------------------------------------------------------------
// the software FMA against the hardware's (`fma` mode)
//
// The shipped models are compiled with clang's `-ffp-contract=on`, so the port has to reproduce
// a hardware `fmadd` on every `a*b + c` it transcribes; JavaScript has no `Math.fma`, so
// `nativeMath.ts`'s `fma64` emulates it (Dekker two-product + round-to-odd final add). This
// block replays the probe's own hardware results through the emulation bit-for-bit. The naive
// two-rounding form is evaluated alongside so the pin's power is measured, not assumed.
// ---------------------------------------------------------------------------

differential('fma64 (native differential)', () => {
  it('reproduces the hardware fused multiply-add bit for bit', () => {
    const lines = readFileSync(join(PROBE_DIR, 'fma.txt'), 'utf8')
      .split('\n')
      .filter((l) => l.length > 0 && !l.startsWith('#'));

    let bad = 0;
    let naiveBad = 0;
    let examples = 0;
    for (const line of lines) {
      const f = line.split(' ');
      if (f[0] !== 'fma') throw new Error(`fma.txt: unknown tag ${f[0]}`);
      const a = bitsToDouble(f[1]!);
      const b = bitsToDouble(f[2]!);
      const c = bitsToDouble(f[3]!);
      const want = f[4]!;
      const got = doubleBits(fma64(a, b, c));
      if (got !== want) {
        if (examples < 5) console.log(`fma64 miss: a=${f[1]} b=${f[2]} c=${f[3]} hw=${want} port=${got}`);
        examples += 1;
        bad += 1;
      }
      // the transcription this replaced: the product rounded, then the sum rounded
      if (doubleBits(a * b + c) !== want) naiveBad += 1;
    }

    // eslint-disable-next-line no-console
    console.log(`fma census: ${lines.length - bad}/${lines.length} bit-exact (naive a*b+c wrong on ${naiveBad})`);
    expect(lines.length).toBeGreaterThan(30_000);
    expect(bad).toBe(0);
    // non-vacuity: a transcription that rounds the product first is wrong on a large fraction
    expect(naiveBad).toBeGreaterThan(1000);
  });
});

// ---------------------------------------------------------------------------
// the grow arithmetic against the native compiler (`growexpr` mode)
//
// `GroupsBrain::growSynapses` cannot be driven end-to-end until lane L5 (a native
// `GroupsGenome`) and lane L8 (`agent::config`) exist, so `brainprobe growexpr` compiles a
// transcription of each of its C expressions with the oracle's own clang++ and evaluates them
// over an enumerated grid; this test replays the inputs through `growArithmetic.ts` and
// compares the results bit-for-bit. The pre-review transcriptions are evaluated alongside, so
// the *grid's* power to catch the defect it was built for is measured rather than assumed.
// ---------------------------------------------------------------------------

differential('groups grow arithmetic (native differential)', () => {
  it('reproduces every native growSynapses expression over the probe grid', () => {
    const lines = readFileSync(join(PROBE_DIR, 'growexpr.txt'), 'utf8')
      .split('\n')
      .filter((l) => l.length > 0 && !l.startsWith('#'));

    // the arithmetic this lane shipped *before* review round 1 (the all-double sum, the extra
    // `f32` before the base-index cast, the double `(1 - td) * 2`, the double `stdev`)
    const legacyBase = (localTo: number, countTo: number, countFrom: number, scn: number): number => {
      const raw = f32(f32(f32(localTo / countTo) * f32(countFrom)) - f32(scn) * 0.5);
      return Math.max(toShort(0), Math.min(toShort(countFrom - scn), toShort(raw)));
    };
    const legacy = {
      synnew: (nsyn: number, rem: number) => toShort(nsyn + rem + 1.e-5),
      baseidx: legacyBase,
      tdabs: (td: number, branch: number) => (branch === 1 ? td * 2 : branch === 2 ? (1 - td) * 2 : td),
      stdev: (gene: number, config: number) => gene * config,
      // the pre-review grouping: `a * (n / m)` instead of native's `(a * n) / m`
      energy: (a: number, n: number, maxn: number, b: number, s: number, maxs: number) =>
        f32(f32(a * f32(n / maxn)) + f32(b * f32(s / maxs))),
      // the round-then-add reading of the `nint` macro's argument (the product materialised,
      // then the ±0.499999999 added) — `distortionIndex` before `t_7d391d0f`, and the form the
      // binary's `0x66dc0 fmadd` contracts away
      distort: (termA: number, termB: number, td: number, count: number) =>
        toShort(Math.trunc(termA * td * count + (termB * td * count < 0.0 ? -0.499999999 : 0.499999999))),
    };

    const tally = new Map<string, { rows: number; bad: number; legacyBad: number }>();
    const note = (tag: string, ok: boolean, legacyOk: boolean | null) => {
      const t = tally.get(tag) ?? { rows: 0, bad: 0, legacyBad: 0 };
      t.rows += 1;
      if (!ok) t.bad += 1;
      if (legacyOk === false) t.legacyBad += 1;
      tally.set(tag, t);
    };

    for (const line of lines) {
      const p = line.split(' ');
      switch (p[0]) {
        case 'synnew': {
          const nsyn = floatFromBits(p[1]!);
          const rem = floatFromBits(p[2]!);
          const want = Number(p[3]);
          note('synnew', synapseCountNew(nsyn, rem) === want, legacy.synnew(nsyn, rem) === want);
          break;
        }
        case 'remupd': {
          // the port's `remainderUpdate` is unchanged from the pre-review revision
          const rem = floatFromBits(p[1]!);
          const nsyn = floatFromBits(p[2]!);
          const scn = Number(p[3]);
          note('remupd', floatBits(remainderUpdate(rem, nsyn, scn)) === p[4], null);
          break;
        }
        case 'baseidx': {
          const [localTo, countTo, countFrom, scn] = p.slice(1, 5).map(Number) as [number, number, number, number];
          const want = Number(p[5]);
          note('baseidx', neuronLocalIndexFromBase(localTo, countTo, countFrom, scn) === want, legacy.baseidx(localTo, countTo, countFrom, scn) === want);
          break;
        }
        case 'tdabs': {
          const td = floatFromBits(p[1]!);
          const branch = Number(p[2]) as 0 | 1 | 2;
          const key = branch === 1 ? TdAbsBranch.MIRRORED_LOW : branch === 2 ? TdAbsBranch.MIRRORED_HIGH : TdAbsBranch.UNMIRRORED;
          note('tdabs', floatBits(tdFromToAbs(td, key)) === p[3], floatBits(legacy.tdabs(td, branch)) === p[3]);
          break;
        }
        case 'distort':
        case 'distortb': {
          // the macro holds a `range()` call, so the walk draws twice per passing connection:
          // row = <drawA_bits> <drawB_bits> <tdabs_bits> <count> <distortion>
          //
          // `distortb` is the probe's *boundary* family (`t_7d391d0f`): draws constructed so the
          // last multiply's exact product lands within ~1 ulp of the truncation boundary, i.e.
          // so that the binary's `0x66dc0 fmadd` and a round-then-add transcription give
          // different indices. The probe emits a row only when the two disagree.
          const termA = bitsToDouble(p[1]!);
          const termB = bitsToDouble(p[2]!);
          const td = floatFromBits(p[3]!);
          const count = Number(p[4]);
          note(
            p[0]!,
            distortionIndex(termA, termB, td, count) === Number(p[5]),
            legacy.distort(termA, termB, td, count) === Number(p[5]),
          );
          break;
        }
        case 'stdev': {
          note('stdev', floatBits(stdevOf(floatFromBits(p[1]!), floatFromBits(p[2]!))) === p[3], floatBits(legacy.stdev(floatFromBits(p[1]!), floatFromBits(p[2]!))) === p[3]);
          break;
        }
        case 'energy': {
          const a = floatFromBits(p[1]!);
          const n = Number(p[2]);
          const maxn = Number(p[3]);
          const b = floatFromBits(p[4]!);
          const s = Number(p[5]);
          const maxs = Number(p[6]);
          const got = energyUseOf(a, n, maxn, b, s, maxs);
          note('energy', floatBits(got) === p[7], floatBits(legacy.energy(a, n, maxn, b, s, maxs)) === p[7]);
          break;
        }
        default:
          throw new Error(`growexpr.txt: unknown tag ${p[0]}`);
      }
    }

    let rows = 0;
    for (const [tag, t] of tally) {
      rows += t.rows;
      // eslint-disable-next-line no-console
      console.log(`grow arithmetic ${tag}: ${t.rows - t.bad}/${t.rows} exact (pre-review form wrong on ${t.legacyBad})`);
      expect(t.rows).toBeGreaterThan(100);
      expect(t.bad).toBe(0);
    }

    expect(tally.size).toBe(8);
    expect(rows).toBe(lines.length);
    expect(rows).toBeGreaterThan(40_000);
    // the grid is not vacuous: it catches the defect it was written for (review round 1's
    // all-double `short( nsynjiperneur + remainder + 1.e-5 )`), which is what makes the zero
    // above evidence rather than an artefact of too few inputs
    expect(tally.get('synnew')!.legacyBad).toBeGreaterThan(0);
    // …and that the energy formula's *grouping* matters too (the product is native's first)
    expect(tally.get('energy')!.legacyBad).toBeGreaterThan(0);
    // `t_7d391d0f`: the *boundary* family, where `0x66dc0 fmadd d0, d9, d11, d0` is visible in
    // the result. The probe emits a row only where the compiled macro and the round-then-add
    // transcription disagree, so every row of it must be one the pre-change form gets wrong —
    // a vacuous family here would mean the family never reached the truncation boundary.
    expect(tally.get('distortb')!.rows).toBeGreaterThan(100);
    expect(tally.get('distortb')!.legacyBad).toBe(tally.get('distortb')!.rows);
  });
});

// ---------------------------------------------------------------------------
// the `SeedSynapsesFromRun` reader/writer pair — `Brain::dumpSynapses` ->
// `Brain::loadSynapses` -> `copySynapses` / `scaleSynapses`
//
// `Logs::brainEnd` writes `run/brain/synapses/synapses_<agent>_<stage>.txt` through
// `Brain::dumpSynapses`, and `analysis::getNervousSystem` / `analysis::copyNervousSystem` /
// `analysis::setMaxWeight` read it back through `Brain::loadSynapses` (with and without a
// rescale) and `Brain::copySynapses`. Every recorded scenario leaves `SeedSynapsesFromRun
// False`, so no golden reaches any of the three.
//
// `brainprobe synapses` drives them from the shipped library itself; its corpus is committed
// under `src/model/brain/core/native/vectors/` (so this block needs no C++ — CI, the browser
// lane and a reviewer without a native build replay the same numbers), and
// `differential('synapses vectors')` below re-runs the mode and fails if the regenerated
// corpus differs. Two families bracket the dump's loss: `synrandom` carries the efficacies a
// real brain holds (which `%g`'s six significant digits do *not* reproduce) and `synexact`
// holds decimals short enough for it to reproduce them exactly. Every value is compared as raw
// IEEE-754 bits; `syndump.<tag>.txt` is compared as bytes.
// ---------------------------------------------------------------------------

const SYNAPSE_VECTORS = join(REPO, 'src', 'model', 'brain', 'core', 'native', 'vectors');
const SYNAPSE_TAGS = ['synrandom', 'synexact'] as const;
type SynapseTag = (typeof SYNAPSE_TAGS)[number];

interface SynapseRow {
  from: number;
  to: number;
  efficacy: string;
  lrate: string;
}

interface SynapseReport {
  dump: string;
  index: number;
  dims: Dimensions;
  maxWeightBits: string;
  fileMaxWeightBits: string;
  src: SynapseRow[];
  rt: SynapseRow[];
  range: Array<{ start: number; end: number }>;
  copy: SynapseRow[];
  copyRange: Array<{ start: number; end: number }>;
  scaleMwBits: string[];
  scaleFactorBits: string[];
  scale: string[][];
  summary: { synapses: number; rtSame: number; copySame: number; scaleRows: number; scaleChanged: number };
}

function readSynapseReport(tag: SynapseTag): SynapseReport {
  const report: SynapseReport = {
    dump: readFileSync(join(SYNAPSE_VECTORS, `syndump.${tag}.txt`), 'utf8'),
    index: 0,
    dims: new Dimensions(),
    maxWeightBits: '',
    fileMaxWeightBits: '',
    src: [],
    rt: [],
    range: [],
    copy: [],
    copyRange: [],
    scaleMwBits: [],
    scaleFactorBits: [],
    scale: [],
    summary: { synapses: 0, rtSame: 0, copySame: 0, scaleRows: 0, scaleChanged: 0 },
  };

  const row = (f: string[]): SynapseRow => ({
    from: Number(f[2]),
    to: Number(f[3]),
    efficacy: f[4]!,
    lrate: f[5]!,
  });

  for (const line of readFileSync(join(SYNAPSE_VECTORS, `synapses.${tag}.txt`), 'utf8').split('\n')) {
    if (line.length === 0 || line.startsWith('#')) continue;
    const f = line.split(' ');
    switch (f[0]) {
      case 'family':
        if (f[1] !== tag) throw new Error(`synapses.${tag}.txt: family ${f[1]}`);
        break;
      case 'dumpindex':
        report.index = Number(f[1]);
        break;
      case 'dims':
        report.dims.numNeurons = Number(f[1]);
        report.dims.numInputNeurons = Number(f[2]);
        report.dims.numOutputNeurons = Number(f[3]);
        report.dims.numSynapses = Number(f[4]);
        break;
      case 'maxweight':
        report.maxWeightBits = f[1]!;
        break;
      case 'filemaxweight':
        report.fileMaxWeightBits = f[1]!;
        break;
      case 'src':
        report.src[Number(f[1])!] = row(f);
        break;
      case 'rt':
        report.rt[Number(f[1])!] = row(f);
        break;
      case 'range':
        report.range[Number(f[1])!] = { start: Number(f[2]), end: Number(f[3]) };
        break;
      case 'copy':
        report.copy[Number(f[1])!] = row(f);
        break;
      case 'copyrange':
        report.copyRange[Number(f[1])!] = { start: Number(f[2]), end: Number(f[3]) };
        break;
      case 'scalemw':
        report.scaleMwBits[Number(f[1])!] = f[2]!;
        break;
      case 'scalefactor':
        report.scaleFactorBits[Number(f[1])!] = f[2]!;
        break;
      case 'scale': {
        const m = Number(f[1]);
        (report.scale[m] ??= [])[Number(f[2])!] = f[3]!;
        break;
      }
      case 'summary':
        report.summary = {
          synapses: Number(f[2]),
          rtSame: Number(f[4]),
          copySame: Number(f[6]),
          scaleRows: Number(f[8]),
          scaleChanged: Number(f[10]),
        };
        break;
      default:
        throw new Error(`synapses.${tag}.txt: unknown tag ${f[0]}`);
    }
  }

  return report;
}

/**
 * The probe's brain, rebuilt with the port — the state `loadSynapses`/`copySynapses` land on.
 *
 * `perturbRanges` reproduces what the probe does to the brain a dump is loaded *into*: the
 * native caller (`analysis::getNervousSystem`) grows that brain from a genome first, so it
 * holds its own ranges until the load overwrites the ones it sees — which is what makes the
 * `range`/`copyrange` rows evidence about `setSynapses` rather than about the construction both
 * sides share.
 */
function buildSynapseBrain(tag: SynapseTag, perturbRanges: boolean): { brain: ProbeBrain; model: FiringRateModel; spec: Spec } {
  const spec = readSpec(tag, SYNAPSE_VECTORS);

  brainConfig.neuronModel = NeuronModelKind.FIRING_RATE;
  brainConfig.architecture = BrainArchitecture.Groups;
  brainConfig.logisticSlope = spec.logisticSlope;
  brainConfig.maxWeight = spec.maxWeight;
  brainConfig.maxbias = spec.maxBias;
  brainConfig.enableLearning = spec.enableLearning;
  brainConfig.minlrate = spec.minlrate;
  brainConfig.maxlrate = spec.maxlrate;
  brainConfig.decayRate = spec.decayRate;
  brainConfig.learningMode = LearningMode.LEARN_ALL;

  const rng = new GlibcDrand48();
  const cns = new ProbeCns(rng);
  const brain = new ProbeBrain(cns);
  cns.wire(brain);

  const model = new FiringRateModel(cns);
  brain.install(spec.dims, model);
  model.init(spec.dims, 0.1);

  // the same two calls per neuron the probe's `initNeuronAttrs(model, spec, false, false)` makes
  for (let i = 0; i < spec.dims.numInputNeurons; i++) {
    const attrs: FiringRateNeuronAttrs = { bias: 0, tau: 0, gain: 0 };
    model.setNeuron(i, attrs);
  }
  for (let i = spec.dims.numInputNeurons; i < spec.dims.numNeurons; i++) {
    const n = spec.neurons[i]!;
    const attrs: FiringRateNeuronAttrs = { bias: n.bias, tau: n.tau, gain: n.gain };
    model.setNeuron(i, attrs, n.start);
    model.setNeuronEndSynapses(i, n.end);
  }
  for (let k = 0; k < spec.dims.numSynapses; k++) {
    const s = spec.synapses[k]!;
    model.setSynapse(k, s.from, s.to, s.efficacy, s.lrate);
  }

  if (perturbRanges) {
    for (let i = 0; i < spec.dims.numNeurons; i++) {
      const n = spec.neurons[i]!;
      const attrs: FiringRateNeuronAttrs = { bias: n.bias, tau: n.tau, gain: n.gain };
      model.setNeuron(i, attrs, i, i + 1);
    }
  }

  return { brain, model, spec };
}

/** A loaded brain: the probe's dump read back through the port's `Brain::loadSynapses`. */
function loadSynapseDump(tag: SynapseTag): { brain: ProbeBrain; model: FiringRateModel; spec: Spec } {
  const built = buildSynapseBrain(tag, true);
  const file = new StringTextFile();
  file.resetForRead(readFileSync(join(SYNAPSE_VECTORS, `syndump.${tag}.txt`), 'utf8'));
  built.brain.loadSynapses(file);
  return built;
}

describe('the SeedSynapsesFromRun reader/writer pair (native vectors)', () => {
  for (const tag of SYNAPSE_TAGS) {
    describe(tag, () => {
      let report: SynapseReport;

      beforeAll(() => {
        report = readSynapseReport(tag);
      });

      it('writes the bytes the native recorder wrote (run/brain/synapses/**)', () => {
        const { brain } = buildSynapseBrain(tag, false);
        const file = new StringTextFile();
        brain.dumpSynapses(file, report.index);
        expect(file.contents()).toBe(report.dump);
      });

      it('rebuilds the probe’s own table bit for bit', () => {
        const { model } = buildSynapseBrain(tag, false);
        for (let k = 0; k < report.dims.numSynapses; k++) {
          const s = model.getSynapse(k);
          expect([s.fromneuron, s.toneuron, floatBits(s.efficacy), floatBits(s.lrate)]).toEqual([
            report.src[k]!.from,
            report.src[k]!.to,
            report.src[k]!.efficacy,
            report.src[k]!.lrate,
          ]);
        }
      });

      it('reproduces the native dump round trip bit for bit', () => {
        const { model } = loadSynapseDump(tag);
        let survived = 0;
        for (let k = 0; k < report.dims.numSynapses; k++) {
          const s = model.getSynapse(k);
          expect([s.fromneuron, s.toneuron]).toEqual([report.rt[k]!.from, report.rt[k]!.to]);
          expect(floatBits(s.efficacy)).toBe(report.rt[k]!.efficacy);
          expect(floatBits(s.lrate)).toBe(report.rt[k]!.lrate);
          if (
            floatBits(s.efficacy) === report.src[k]!.efficacy &&
            floatBits(s.lrate) === report.src[k]!.lrate
          ) {
            survived += 1;
          }
        }

        // the family bracket, measured: `synexact`'s decimals are short enough for `%g` to
        // reproduce, `synrandom`'s are not — so a reader that reformatted the values, or one
        // that kept them instead of re-reading the text, fails on one family or the other
        // eslint-disable-next-line no-console
        console.log(
          `loadSynapses ${tag}: ${survived}/${report.dims.numSynapses} values survive the dump round trip` +
            ` (native ${report.summary.rtSame})`,
        );
        expect(report.summary.synapses).toBe(report.dims.numSynapses);
        expect(survived).toBe(report.summary.rtSame);
        if (tag === 'synexact') expect(survived).toBe(report.dims.numSynapses);
        else expect(survived).toBeLessThan(report.dims.numSynapses);
      });

      it('re-derives the neuron ranges `setSynapses` re-derives, and leaves the unwired neuron alone', () => {
        const { model } = loadSynapseDump(tag);
        const state = model.rawState();
        let rewritten = 0;
        for (let i = 0; i < report.dims.numNeurons; i++) {
          const neuron = state.neuron[i]!;
          expect([neuron.startsynapses, neuron.endsynapses]).toEqual([
            report.range[i]!.start,
            report.range[i]!.end,
          ]);
          // the probe perturbs every range to `[i, i+1]` before the load, so any row that came
          // out different is one `setSynapses` rewrote
          if (report.range[i]!.start !== i || report.range[i]!.end !== i + 1) rewritten += 1;
        }

        expect(rewritten).toBeGreaterThan(0);
        // …and the last neuron has no incoming synapse, so the load must not touch it at all
        const last = report.dims.numNeurons - 1;
        expect([report.range[last]!.start, report.range[last]!.end]).toEqual([last, last + 1]);
      });

      it('copies the loaded table bit for bit, ranges included', () => {
        const loaded = loadSynapseDump(tag);
        const { brain, model } = buildSynapseBrain(tag, true);
        brain.copySynapses(loaded.brain);

        for (let k = 0; k < report.dims.numSynapses; k++) {
          const s = model.getSynapse(k);
          expect([s.fromneuron, s.toneuron, floatBits(s.efficacy), floatBits(s.lrate)]).toEqual([
            report.copy[k]!.from,
            report.copy[k]!.to,
            report.copy[k]!.efficacy,
            report.copy[k]!.lrate,
          ]);
        }

        const state = model.rawState();
        for (let i = 0; i < report.dims.numNeurons; i++) {
          expect([state.neuron[i]!.startsynapses, state.neuron[i]!.endsynapses]).toEqual([
            report.copyRange[i]!.start,
            report.copyRange[i]!.end,
          ]);
        }

        // the copy is the loaded *brain's* table, not a re-read of the file's text: on the
        // lossy family the two differ, so a `copySynapses` that re-parsed the dump would fail
        expect(report.copy.map((r) => r.efficacy)).toEqual(report.rt.map((r) => r.efficacy));
        expect(report.summary.copySame).toBe(report.dims.numSynapses);
      });

      it('rescales by the native float division in `loadSynapses( file, maxWeight )`', () => {
        const loadedState = loadSynapseDump(tag);
        const loadedBits: string[] = [];
        for (let k = 0; k < report.dims.numSynapses; k++) {
          loadedBits.push(floatBits(loadedState.model.getSynapse(k).efficacy));
        }

        // the transcription this card replaced (`t_da2ab201`-style: measure it, don't assume
        // its power): `fileMaxWeight` left as the binary64 the port's `%g` reader returns —
        // native stores the header's field in a `float` — and the quotient then computed in
        // binary64 with the product rounded to `float` only at the store
        const headerMaxWeight = /maxweight=(\S+)/.exec(report.dump)![1]!;
        const legacyFileMaxWeight = Number(headerMaxWeight);
        let legacyBad = 0;
        let rows = 0;

        for (let m = 0; m < report.scaleMwBits.length; m++) {
          const maxWeight = floatFromBits(report.scaleMwBits[m]!);
          // `Brain::loadSynapses( file, maxWeight )` divides `maxWeight` by the header's own
          // `maxweight=` field read back into a *float* and divides in `float`; the corpus
          // carries both the value (`scalefactor`) and the result, so the transcription is
          // checked against the shipped `fdiv` rather than assumed
          expect(floatBits(f32(maxWeight / f32(Number(headerMaxWeight))))).toBe(report.scaleFactorBits[m]!);

          const { brain, model } = buildSynapseBrain(tag, true);
          const file = new StringTextFile();
          file.resetForRead(report.dump);
          const header = brain.loadSynapses(file, maxWeight);
          // the header field the port hands back is the float native stores (not the binary64
          // its own `%g` reader returns)
          expect(floatBits(header.fileMaxWeight)).toBe(report.fileMaxWeightBits);

          for (let k = 0; k < report.dims.numSynapses; k++) {
            const got = floatBits(model.getSynapse(k).efficacy);
            expect(got).toBe(report.scale[m]![k]!);
            const legacy = floatBits(f32(floatFromBits(loadedBits[k]!) * (maxWeight / legacyFileMaxWeight)));
            if (legacy !== got) legacyBad += 1;
            rows += 1;
          }
        }

        // eslint-disable-next-line no-console
        console.log(
          `loadSynapses(${tag}, maxWeight): ${legacyBad}/${rows} rows separate the binary64 transcription` +
            ` (${report.scaleMwBits.length} maxWeight values)`,
        );
        expect(rows).toBe(report.summary.scaleRows);
        // the rescale actually moved efficacies (native's own count), so the rows are not all
        // "scale by a factor of one" cases
        expect(report.summary.scaleChanged).toBeGreaterThan(0);
        // measured, not assumed: the pre-change form is wrong on a large fraction of the rows,
        // which is what makes the zero-mismatch above evidence about the `float` division
        expect(legacyBad).toBeGreaterThan(0);
      });
    });
  }
});

// The committed corpus is the oracle, and this is the check that keeps it honest: the probe
// re-runs the same mode against the shipped library and its output must be byte-identical to
// what is committed. A diff here means the native build's dump/load moved — re-record with
// `src/model/brain/core/native/record_synapses_vectors.sh` and review the new numbers.
differential('synapses vectors (native differential)', () => {
  for (const tag of SYNAPSE_TAGS) {
    it(`regenerates the committed ${tag} corpus byte for byte`, () => {
      for (const name of [`spec.${tag}.txt`, `syndump.${tag}.txt`, `synapses.${tag}.txt`]) {
        expect(readFileSync(join(PROBE_DIR, name), 'utf8')).toBe(readFileSync(join(SYNAPSE_VECTORS, name), 'utf8'));
      }
    });
  }
});
