#!/usr/bin/env python3
"""Emit the oracle's `log2` constants and its 129-entry table from the *shipped* bytes.

The source of truth is `raw/log2_bytes.bin`, the dump of the live
`/usr/lib/system/libsystem_m.dylib` `log2` written by `raw/dump_log2_data.c`. This script
reads that file, checks the layout the disassembly implies, and writes

  * `raw/apple_log2_table.h`      -- the C transcription's constants + table, and
  * `../../appleLog2Table.ts`     -- the TypeScript module the port imports.

Nothing is typed by hand, so the data cannot drift from the machine code:

    clang -O2 raw/dump_log2_data.c -o /tmp/dump_log2_data
    (cd native && /tmp/dump_log2_data)
    python3 native/gen_log2_table.py
"""

import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, 'raw')
BIN = os.path.join(RAW, 'log2_bytes.bin')
TS = os.path.join(os.path.dirname(HERE), 'appleLog2Table.ts')
HDR = os.path.join(RAW, 'apple_log2_table.h')

OFF_BIAS = 0x160
OFF_LOG2E = 0x168
OFF_INF = 0x170
OFF_MASK = 0x178
OFF_ONE = 0x180
OFF_LOG2E_HI = 0x188
OFF_LOG2E_LO = 0x190
OFF_POLY = 0x198          # 6 doubles
OFF_TAB = 0x1c8           # 129 x { 1/c, log2(c) }
N_TAB = 129


def u64(b: bytes, off: int) -> int:
    return struct.unpack_from('<Q', b, off)[0]


def dbl(b: bytes, off: int) -> float:
    return struct.unpack_from('<d', b, off)[0]


def fmt(x: float) -> str:
    s = repr(x)
    return s


def main() -> None:
    with open(BIN, 'rb') as f:
        code = f.read()
    need = OFF_TAB + N_TAB * 16
    if len(code) < need:
        sys.exit(f'{BIN} is only {len(code)} bytes; run raw/dump_log2_data.c first')

    bias = u64(code, OFF_BIAS)
    mask = u64(code, OFF_MASK)
    one = u64(code, OFF_ONE)
    inf = u64(code, OFF_INF)
    log2e = dbl(code, OFF_LOG2E)
    log2e_hi = dbl(code, OFF_LOG2E_HI)
    log2e_lo = dbl(code, OFF_LOG2E_LO)
    poly = [dbl(code, OFF_POLY + 8 * i) for i in range(6)]
    tab = [(dbl(code, OFF_TAB + 16 * i), dbl(code, OFF_TAB + 16 * i + 8)) for i in range(N_TAB)]

    # --- layout checks (fail loudly rather than emit garbage) -----------------------------
    if bias != 0xc018100000000000:
        sys.exit(f'bias constant is 0x{bias:016x}, expected 0xc018100000000000')
    if mask != 0xfffffffff8000000:
        sys.exit(f'mask constant is 0x{mask:016x}, expected 0xfffffffff8000000')
    if one != 0x3ff0000000000000:
        sys.exit(f'one constant is 0x{one:016x}, expected 0x3ff0000000000000')
    if inf != 0x7ff0000000000000:
        sys.exit(f'inf constant is 0x{inf:016x}, expected 0x7ff0000000000000')
    if log2e != 1.4426950408889634:
        sys.exit(f'1/ln2 constant is {log2e!r}, expected 1.4426950408889634')
    if log2e_hi + log2e_lo != log2e:
        sys.exit(f'1/ln2 halves {log2e_hi!r} + {log2e_lo!r} do not sum to {log2e!r}')
    if tab[0] != (1.0, 0.0):
        sys.exit(f'table[0] is {tab[0]!r}, expected (1.0, 0.0)')
    if tab[128] != (0.5, 0.0):
        sys.exit(f'table[128] is {tab[128]!r}, expected (0.5, 0.0)')
    for i, (invc, logc) in enumerate(tab):
        expect_c = 1.0 + i / 128.0
        if abs(1.0 / invc - expect_c) > 1e-3:
            sys.exit(f'table[{i}]: 1/{invc!r} is not the interval centre {expect_c!r}')
        # The stored pair is self-consistent: logc is log2(1/invc), offset by one for
        # i >= 64 (which is why the algorithm's exponent is floor(log2 x) + 1). The table's
        # `invc` itself is stored at reduced precision -- the pair is what the algorithm
        # consumes, so its exact bytes are what matter, not its distance from 1/(1+i/128).
        shift = 1.0 if i >= 64 else 0.0
        expect_logc = __import__('math').log2(1.0 / invc) - shift
        if abs(logc - expect_logc) > 1e-12 * max(1.0, abs(expect_logc)):
            sys.exit(f'table[{i}]: {logc!r} is not log2(1/{invc!r}) - {shift}')

    # --- the C header ---------------------------------------------------------------------
    with open(HDR, 'w') as h:
        h.write('/* GENERATED by gen_log2_table.py from raw/log2_bytes.bin -- do not edit. */\n')
        h.write('#ifndef APPLE_LOG2_TABLE_H\n#define APPLE_LOG2_TABLE_H\n\n')
        h.write(f'#define LOG2_BIAS_BITS 0x{bias:016x}ULL\n')
        h.write(f'#define LOG2_MASK_BITS 0x{mask:016x}ULL\n')
        h.write(f'#define LOG2_ONE_BITS  0x{one:016x}ULL\n')
        h.write(f'#define LOG2_INF_BITS  0x{inf:016x}ULL\n')
        h.write(f'static const double LOG2_LOG2E    = {fmt(log2e)};\n')
        h.write(f'static const double LOG2_LOG2E_HI = {fmt(log2e_hi)};\n')
        h.write(f'static const double LOG2_LOG2E_LO = {fmt(log2e_lo)};\n')
        h.write('static const double LOG2_POLY[6] = {\n')
        for c in poly:
            h.write(f'    {fmt(c)},\n')
        h.write('};\n')
        h.write('static const double LOG2_TAB[%d][2] = {\n' % N_TAB)
        for invc, logc in tab:
            h.write(f'    {{ {fmt(invc)}, {fmt(logc)} }},\n')
        h.write('};\n\n#endif /* APPLE_LOG2_TABLE_H */\n')

    # --- the TypeScript module ------------------------------------------------------------
    with open(TS, 'w') as t:
        t.write('/**\n')
        t.write(" * The oracle's libm `log2` data (macOS 26.5.2, arm64).\n")
        t.write(' *\n')
        t.write(' * GENERATED — do not edit. `log2()` in ./log2.ts is a transcription of the shipped\n')
        t.write(' * libSystem `log2`, and these are the constants and the 129 table entries it reads:\n')
        t.write(' *\n')
        t.write(' *   index i      -> the interval around z = 1 + i/128 for z in [1, 2)\n')
        t.write(' *   entry[0]     -> `invc`, a double near 1/c\n')
        t.write(' *   entry[1]     -> log2(c), one double (the branch that reads it splits it at run\n')
        t.write(' *                   time with `LOG2_MASK_BITS`)\n')
        t.write(' *\n')
        t.write(' * Regenerate with `native/gen_log2_table.py` from `native/raw/log2_bytes.bin`,\n')
        t.write(' * which `native/raw/dump_log2_data.c` copies out of the running libSystem.\n')
        t.write(' */\n\n')
        t.write('/** The 6 polynomial coefficients (r^2 * (c0 + c1 r)(c2 + c3 r + r^2)(c4 + c5 r + r^2)). */\n')
        t.write('export const LOG2_POLY: readonly number[] = [\n')
        for c in poly:
            t.write(f'  {fmt(c)},\n')
        t.write('];\n\n')
        t.write('/** `invc[i]` — one per interval. */\n')
        t.write('export const LOG2_TAB_INVC = new Float64Array([\n')
        for invc, _ in tab:
            t.write(f'  {fmt(invc)},\n')
        t.write(']);\n\n')
        t.write('/** `log2(c)` — one per interval. */\n')
        t.write('export const LOG2_TAB_LOGC = new Float64Array([\n')
        for _, logc in tab:
            t.write(f'  {fmt(logc)},\n')
        t.write(']);\n\n')
        t.write(f"/** `0x{bias:016x}` — the bias added to the argument's bit pattern. */\n")
        t.write(f'export const LOG2_BIAS_BITS = 0x{bias:016x}n;\n')
        t.write(f'/** `0x{mask:016x}` — the mask that keeps a table value top 25 mantissa bits. */\n')
        t.write(f'export const LOG2_MASK_BITS = 0x{mask:016x}n;\n')
        t.write(f'/** `0x{one:016x}` — 1.0. */\n')
        t.write(f'export const LOG2_ONE_BITS = 0x{one:016x}n;\n')
        t.write(f"/** `0x{inf:016x}` — +Infinity, the negative-argument path's `x - x`. */\n")
        t.write(f'export const LOG2_INF_BITS = 0x{inf:016x}n;\n')
        t.write(f'/** 1/ln2 as the general branch uses it. */\n')
        t.write(f'export const LOG2_LOG2E = {fmt(log2e)};\n')
        t.write(f'/** 1/ln2, high half — the `k == 0` branch scales its corrections with this. */\n')
        t.write(f'export const LOG2_LOG2E_HI = {fmt(log2e_hi)};\n')
        t.write(f'/** 1/ln2, low half. */\n')
        t.write(f'export const LOG2_LOG2E_LO = {fmt(log2e_lo)};\n')

    print(f'wrote {HDR}')
    print(f'wrote {TS}')
    print(f'  {N_TAB} table entries, {len(poly)} polynomial coefficients')


if __name__ == '__main__':
    main()
