/* Generated by gen_sincos_table.py from raw/sincos_bytes.bin -- do not edit. */
#ifndef APPLE_SINCOS_TABLE_H
#define APPLE_SINCOS_TABLE_H

/* The dispatch boundaries and the three-part pi/2 the medium reduction uses.
 * `PI2_HI + PI2_MID + PI2_LO` is pi/2 to ~130 bits. */
#define ASC_PI4 0.7853981633974483
#define ASC_THRESH 524288.6169851497
#define ASC_INV_PI2 0.6366197723675814
#define ASC_PI2_HI 1.5707963267923333
#define ASC_PI2_MID 2.5633441515839558e-12
#define ASC_PI2_LO 1.0562999066987428e-23
#define ASC_MAGIC 0xc90fdaa22168c235ull

/* ASC_TAB[j] is the 1/pi word at sin-0x50-8j (j = 0..15); ASC_TAB[i] here is
 * the word at sin-0xc8+8i, so ASC_TAB[15-j] is that word.  ASC_TAB[16..18]
 * are the words *above* sin-0x50 that a k = 0 Payne-Hanek window reads. */
static const uint64_t ASC_TAB[19] = {
  0x35fdafd88fc6ae84ull,
  0x9e839cfbc5294975ull,
  0xba93dd63f5f2f8bdull,
  0xa7a31fb34f2ff516ull,
  0xb69b3f6793e584dbull,
  0xf79788c5ad05368full,
  0x8ffc4bffef02cc07ull,
  0x4e422fc5defc941dull,
  0x9cc8eb1cc1a99cfaull,
  0x74ce38135a2fbf20ull,
  0x74411afa975da242ull,
  0x7f0ef58e5894d39full,
  0x0324977504e8c90eull,
  0xdb92371d2126e970ull,
  0xff28b1d5ef5de2b0ull,
  0x6db14acc9e21c820ull,
  0xfe13abe8fa9a6ee0ull,
  0x517cc1b727220a94ull,
  0x0000000000000000ull,
};

/* sin(r) = r + r^3 * poly(r^2), 6 coefficients in load order */
static const double ASC_SIN_POLY[6] = {
  1.5896230157654656e-10,
  -2.5050747762857807e-08,
  2.7557313621385722e-06,
  -0.0001984126982958954,
  0.008333333333322118,
  -0.1666666666666663,
};

/* cos(r) = 1 + z * poly(z) with z = r^2, 7 coefficients in load order */
static const double ASC_COS_POLY[7] = {
  -1.1358536521387682e-11,
  2.087570084197473e-09,
  -2.755731417929674e-07,
  2.4801587288851704e-05,
  -0.0013888888888873056,
  0.041666666666666595,
  -0.5,
};

#endif
