/* The constants of the oracle's arm64 `atan2f`.
 *
 * GENERATED by `gen_atan2f_table.py` from `raw/atan2f_bytes.bin` -- do not edit by hand.
 * Offsets are `atan2f`-relative (plus the dump's 0x40); see the script and
 * `apple_atan2f_impl.h` for the layout and the checks.
 */
#ifndef APPLE_ATAN2F_TABLE_H
#define APPLE_ATAN2F_TABLE_H

static const double AATAN2F_POLY[9] = {
	2.2971562298314634,
	-2.9466967515109825,
	2.4449692297316408,
	5.472844732445699,
	0.020743200300742098,
	-4.972107237621162,
	3.7888879287802704,
	6.719707622359238,
	0.0029352921857004597,
};

static const double AATAN2F_SMALL = 2.384185791015625e-07; /* 2^-22 */

static const double AATAN2F_PI = 3.141592653589793;
static const double AATAN2F_NEG_PI = -3.141592653589793;
static const double AATAN2F_HPI = 1.5707963267948966;
static const double AATAN2F_NEG_HPI = -1.5707963267948966;
static const double AATAN2F_PI_HI = 3.141592502826825; /* f32(pi)+2^-32 */
static const double AATAN2F_3PI4 = 2.356194490192345;
static const double AATAN2F_NEG_3PI4 = -2.356194490192345;
static const double AATAN2F_PI4 = 0.7853981633974483;
static const double AATAN2F_NEG_PI4 = -0.7853981633974483;

#endif /* APPLE_ATAN2F_TABLE_H */
