#!/usr/bin/env python3
"""Generate the argument corpora for the libm census (exp, pow, sin, cos).

Deterministic: a fixed seed and a fixed procedure, so the committed corpora can be
regenerated byte-for-byte. Arguments are written as raw 64-bit IEEE-754 bit patterns
(hex), never as decimal text -- the census is about bits.

    python3 raw/gen_libm_corpus.py            # writes raw/libm_args_<fn>.txt

Corpora, per function:

* a **stratified 512** sweep over the range the model feeds (`-30..30` for `exp`, the
  motion yaw range for `sin`/`cos`, the genome/distribution exponents for `pow`): the
  same shape the pre-existing `libm census` fixture used, so the old numbers and the new
  ones are comparable;
* a **dense 20,000** sweep with 250 values per octave of the input plus exact values at
  every power of two / half-way point (where the argument-reduction tables change), so
  every table row of a transcription is exercised;
* **model-derived** inputs: the actual arguments each call site computes over the
  scenario's own parameter ranges (logistic's `x*slope`, the spiking bias coin's
  `bias*0.5`, the gaussian pdf, the motion `yaw*DEGTORAD`, the genome `pow` base and
  exponent), so a port cannot pass the sweep and still be wrong where the model calls it.
"""

import json
import math
import os
import random
import struct

HERE = os.path.dirname(os.path.abspath(__file__))


def bits(x: float) -> str:
    return struct.pack('>d', float(x)).hex()


def stratified(lo: float, hi: float, n: int, rng: random.Random) -> list[float]:
    """n values spread over [lo, hi]: one per equal subinterval, jittered inside it."""
    out = []
    for i in range(n):
        a = lo + (hi - lo) * i / n
        b = lo + (hi - lo) * (i + 1) / n
        out.append(rng.uniform(a, b))
    return out


def octaves(lo_exp: int, hi_exp: int, per: int, rng: random.Random) -> list[float]:
    """`per` values in every octave [2^e, 2^(e+1)) (and the sign-mirrored negatives)."""
    out = []
    for e in range(lo_exp, hi_exp + 1):
        for i in range(per):
            m = 1.0 + (i + rng.random()) / per
            out.append(math.ldexp(m, e))
    return out


def po2_neighbourhood(lo_exp: int, hi_exp: int) -> list[float]:
    """Powers of two and their immediate neighbours: the table/rounding boundaries."""
    out = []
    for e in range(lo_exp, hi_exp + 1):
        p = math.ldexp(1.0, e)
        for d in (-2, -1, 0, 1, 2):
            v = p + d * math.ulp(p) if e > -1000 else p
            if v > 0:
                out.append(v)
            out.append(-v)
    return out


def exp_corpus(rng: random.Random) -> list[float]:
    out = []
    # 1. the recorded census' own range, so the old 464/512 number is reproduced
    out += stratified(-30.0, 30.0, 512, rng)
    # 2. octave sweep over exp's live range (subnormal underflow to overflow)
    out += octaves(-60, 9, 40, rng)
    out += octaves(-1074, -60, 4, rng)[:2000]
    # 3. table boundaries and the arguments the model really computes
    out += [0.0, -0.0, 1.0, -1.0, math.log(2), -math.log(2), 709.782712893384,
            -745.1332191019411, 1e-300, -1e-300]
    # 4. the branches of the shipped function, exactly on their thresholds: the machine
    #    code dispatches on the raw bit pattern (>= 0x40862e42fefa39f0, < 0xc0874a0000000000)
    #    and on `n >> 7 + 1022 < 0`, so the boundaries are pinned by construction
    out += [709.78271289338409, 709.7827128933841, 709.79, 709.8, 710.0, 745.0, 745.2,
            745.25, 745.2500000000001, 745.26, -709.0, -709.06, -709.07, -709.1, -709.5,
            -710.0, -720.0, -735.0, -744.0, -745.0, -745.13321910194111, -745.24,
            -745.25, -745.2500000000001, -745.26, -746.0, -750.0, -800.0, -1000.0,
            1000.0, 1e10, -1e10, 1e300, -1e300, math.inf, -math.inf, math.nan,
            1e-310, -1e-310]
    # the subnormal-result window, densely: exp(x) is subnormal for x in (-745.133, -708.4)
    out += stratified(-745.25, -708.0, 400, rng)
    # logistic(x, slope) = 1/(1+exp(-x*slope)): activations run to a few hundred, the
    # slopes the recorded worldfiles use are 0.01..1.0
    for _ in range(1500):
        x = rng.uniform(-500.0, 500.0)
        slope = rng.uniform(0.005, 2.0)
        out.append(-1 * x * slope)
    # the spiking model's bias coin: exp(-bias*0.5), bias in [-MaxBiasWeight, +]
    for _ in range(500):
        out.append(-1 * rng.uniform(-30.0, 30.0) * 0.5)
    # gaussPDF-ish / complexity: exp of small negative numbers
    for _ in range(500):
        out.append(-rng.uniform(0.0, 20.0) ** 2 / rng.uniform(0.01, 100.0))
    return out


def sin_cos_corpus(rng: random.Random) -> list[float]:
    out = []
    # the motion path's argument: yaw (degrees, 0..360) times DEGTORAD
    deg = math.pi / 180.0
    for i in range(2000):
        yaw = 360.0 * i / 2000.0
        f = struct.unpack('>f', struct.pack('>f', yaw * deg))[0]  # float arg promoted
        out.append(f)
    out += stratified(-math.pi, math.pi, 512, rng)
    out += stratified(-2 * math.pi, 2 * math.pi, 512, rng)
    out += stratified(-1e6, 1e6, 1000, rng)          # large: reduction path
    out += stratified(-1e15, 1e15, 500, rng)         # very large: Payne-Hanek path
    out += [0.0, -0.0, 1.0, -1.0, math.pi / 2, math.pi, 3 * math.pi / 2,
            math.pi / 4, 3 * math.pi / 4, 1e-300, 1e300, 1.0e17]
    out += octaves(-40, 40, 6, rng)
    # 4. the two dispatch thresholds, exactly and +-3 ulp, both signs: `sin`/`cos` dispatch
    #    on |x| <= pi/4 (bits 0x3fe921fb54442d18) and on |x| < 524288.61698514968
    #    (bits 0x412000013be57a40, where the medium reduction gives way to Payne-Hanek)
    pio4 = struct.unpack('>d', bytes.fromhex('3fe921fb54442d18'))[0]
    thr = struct.unpack('>d', bytes.fromhex('412000013be57a40'))[0]
    for base in (pio4, thr):
        for k in range(-3, 4):
            v = base
            for _ in range(abs(k)):
                v = math.nextafter(v, math.inf if k > 0 else -math.inf)
            out += [v, -v]
    # 5. the special paths
    out += [0.0, -0.0, math.inf, -math.inf, math.nan]
    return out


def pow_corpus(rng: random.Random) -> list[tuple[float, float]]:
    out = []
    # genome: pow(ratio, interpolationPower), ratio in [0,1], power an int gene
    for _ in range(600):
        out.append((rng.uniform(0.0, 1.0), float(rng.randint(1, 8))))
    # Genome::mateProbability: pow(a, miscbias) with a in [0,1], miscbias in [-5,5]
    for _ in range(600):
        out.append((rng.uniform(0.0, 1.0), rng.uniform(-5.0, 5.0)))
    # pow(fabs(cosa), MISC_INVIS_SLOPE)
    for _ in range(400):
        out.append((rng.uniform(0.0, 1.0), rng.uniform(0.0, 4.0)))
    # distributions.cc: pow(sigma, 2), pow(x-mu, 2), pow(e, ...)
    for _ in range(400):
        sigma = rng.uniform(0.001, 1e4)
        out.append((sigma, 2.0))
        out.append((rng.uniform(-1e3, 1e3), 2.0))
        out.append((math.e, rng.uniform(-50.0, 0.0)))
    # Simulation.cc: pow(fraction, 4.0); Logs.cc: pow(x, 2)
    for _ in range(400):
        out.append((rng.uniform(0.0, 1.0), 4.0))
        out.append((rng.uniform(-1e6, 1e6), 2.0))
    # generic: bases and exponents over the double range, both signs (pow's odd/even
    # integer-exponent paths differ, so integers and halves are both included)
    for _ in range(800):
        base = math.ldexp(rng.uniform(-2.0, 2.0), rng.randint(-40, 40))
        e = rng.choice([rng.randint(-8, 8), rng.uniform(-8.0, 8.0), 0.5, 2.0, 3.0])
        out.append((base, float(e)))
    # 5. the special-case ladder: y integral or not, |y| large/tiny, negative bases with an
    #    odd/even integer exponent, zeros, infinities and NaNs, and the (1, y) / (x, 0) rows
    out += [
        (1.0, 1.0), (1.0, 1e300), (1.0, -1e300), (1.0, math.nan), (1.0, math.inf),
        (2.0, 0.0), (-2.0, 0.0), (0.0, 0.0), (-0.0, 0.0), (math.inf, 0.0),
        (0.0, 1.0), (0.0, -1.0), (0.0, 3.0), (0.0, 4.0), (-0.0, 3.0), (-0.0, 4.0),
        (-0.0, 3.5), (0.0, 3.5), (0.0, 0.5), (0.0, -0.5), (-0.0, -3.0),
        (-2.0, 3.0), (-2.0, 2.0), (-2.0, 2.5), (-2.0, -3.0), (-2.0, -2.0), (-1.0, 0.5),
        (4.0, 0.5), (-4.0, 0.5), (2.0, 3.0), (2.0, 0.5), (0.5, 0.5), (9.0, 0.5),
        (2.0, 1e300), (0.5, 1e300), (2.0, -1e300), (0.5, -1e300), (2.0, math.inf),
        (0.5, math.inf), (-2.0, math.inf), (-0.5, math.inf), (1.5, -math.inf),
        (0.5, -math.inf), (math.inf, math.inf), (math.inf, -math.inf), (0.0, math.inf),
        (0.0, -math.inf), (2.0, 1075.0), (2.0, -1075.0), (2.0, 1024.0), (2.0, 1023.0),
        (2.0, 1024.5), (-1.0, 1e300), (-1.0, 1e301), (1e-310, 2.0), (-1e-310, 2.0),
        (1e-320, 2.0), (1e308, 2.0), (1e-308, 1e300), (1.0000000000000002, 1e15),
        (0.9999999999999999, 1e15), (1.0000000000000002, -1e15), (math.nan, 1.0),
        (math.nan, math.nan), (math.inf, math.nan), (math.nan, math.inf), (2.0, math.nan),
        (0.5, math.nan), (0.0, math.nan), (1e-310, 0.5), (1e-310, -0.5),
    ]
    return out


def main() -> None:
    rng = random.Random(20260928)
    written = {}

    exp_args = exp_corpus(rng)
    sin_cos = sin_cos_corpus(rng)
    pow_args = pow_corpus(rng)

    def write(name: str, lines: list[str]) -> None:
        path = os.path.join(HERE, f'libm_args_{name}.txt')
        with open(path, 'w') as f:
            f.write('\n'.join(lines) + '\n')
        written[name] = len(lines)

    write('exp', [f'exp {bits(x)}' for x in exp_args])
    write('sin', [f'sin {bits(x)}' for x in sin_cos])
    write('cos', [f'cos {bits(x)}' for x in sin_cos])
    write('pow', [f'pow {bits(a)} {bits(b)}' for a, b in pow_args])

    meta = {'seed': 20260928, 'counts': written}
    with open(os.path.join(HERE, 'libm_args_meta.json'), 'w') as f:
        json.dump(meta, f, indent=2, sort_keys=True)
        f.write('\n')
    print(json.dumps(meta, indent=2, sort_keys=True))


if __name__ == '__main__':
    main()
